import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;

/**
 * Reading a review process honestly: one accuracy figure hides the weak segment, and a confidence score is only worth what a calibration table says it is.
 *
 * <p>The exam guide (task 5.5) says that stratified random sampling of high-confidence extractions measures the error rate and catches new patterns, that aggregate accuracy can mask poor performance on specific document types or fields,
 * and that field-level confidence scores should be calibrated using labelled validation sets. Below, 200 extractions are generated by a fixed rule (nothing here calls a model): the invoices are mostly right, the handwritten
 * documents are wrong more often, and the confidence says one thing while the labels say another. The numbers are invented for the illustration; the arithmetic is the lesson.
 */
public final class CalibrationTable {
    private static final System.Logger LOG = System.getLogger(CalibrationTable.class.getName());
    record Rec(String docType, int confidence, boolean correct) {}

    record TypeRow(String docType, int correct, int total, int percent) {}

    record Bucket(String label, int count, int said, int right) {}

    record Kept(int count, int precision) {}

    /** (document type, stated confidence, was it correct) for n extractions, from a fixed rule. */
    static List<Rec> makeRecords(int n) {
        List<Rec> records = new ArrayList<>();
        for (int i = 0; i < n; i++) {
            String docType = i % 5 == 0 ? "handwritten" : "invoice";
            int confidence = 50 + (i * 37) % 51;
            int penalty = docType.equals("handwritten") ? 30 : 0;
            records.add(new Rec(docType, confidence, (i * 53) % 100 < confidence - 12 - penalty));
        }
        return records;
    }

    /** A whole-number percentage, rounded half up; 0 for an empty whole. */
    static int ratio(int part, int whole) {
        return whole > 0 ? (200 * part + whole) / (2 * whole) : 0;
    }

    static int overallAccuracy(List<Rec> records) {
        return ratio((int) records.stream().filter(Rec::correct).count(), records.size());
    }

    static List<TypeRow> accuracyByType(List<Rec> records) {
        Map<String, int[]> groups = new TreeMap<>();
        for (Rec r : records) {
            int[] g = groups.computeIfAbsent(r.docType(), k -> new int[2]);
            if (r.correct()) g[0]++;
            g[1]++;
        }
        List<TypeRow> rows = new ArrayList<>();
        for (Map.Entry<String, int[]> e : groups.entrySet()) rows.add(new TypeRow(e.getKey(), e.getValue()[0], e.getValue()[1], ratio(e.getValue()[0], e.getValue()[1])));
        return rows;
    }

    /** One row per non-empty confidence bucket: label, count, confidence it claimed, how often it was right. */
    static List<Bucket> calibrationTable(List<Rec> records) {
        Map<Integer, int[]> buckets = new TreeMap<>();
        for (Rec r : records) {
            int[] b = buckets.computeIfAbsent(Math.min(r.confidence() / 10 * 10, 90), k -> new int[3]);
            b[0]++;
            b[1] += r.confidence();
            if (r.correct()) b[2]++;
        }
        List<Bucket> rows = new ArrayList<>();
        for (Map.Entry<Integer, int[]> e : buckets.entrySet()) {
            int low = e.getKey();
            int[] b = e.getValue();
            rows.add(new Bucket(low == 90 ? "90-100" : low + "-" + (low + 9), b[0], ratio(b[1], 100 * b[0]), ratio(b[2], b[0])));
        }
        return rows;
    }

    /** How many extractions would be accepted without review, and how often those are right. */
    static Kept precisionAbove(List<Rec> records, int threshold) {
        int kept = 0;
        int right = 0;
        for (Rec r : records) {
            if (r.confidence() >= threshold) {
                kept++;
                if (r.correct()) right++;
            }
        }
        return new Kept(kept, ratio(right, kept));
    }

    public static void main(String[] args) {
        List<Rec> records = makeRecords(200);
        System.out.println("overall accuracy: " + overallAccuracy(records) + "%");
        for (TypeRow t : accuracyByType(records)) System.out.println(t.docType() + ": " + t.correct() + " of " + t.total() + " correct, " + t.percent() + "%");
        for (Bucket b : calibrationTable(records)) System.out.println("bucket " + b.label() + ": " + b.count() + " extractions, said " + b.said() + "%, right " + b.right() + "%");
        for (int threshold : new int[] {60, 70, 80, 90}) {
            Kept k = precisionAbove(records, threshold);
            System.out.println("accept at " + threshold + " or above: " + k.count() + " extractions, " + k.precision() + "% right");
        }
    }
}
