/**
 * Reading a review process honestly: one accuracy figure hides the weak segment, and a confidence score is only worth what a calibration table says it is.
 *
 * The exam guide (task 5.5) says that stratified random sampling of high-confidence extractions measures the error rate and catches new patterns, that aggregate accuracy can mask poor performance on specific document types or fields,
 * and that field-level confidence scores should be calibrated using labelled validation sets. Below, 200 extractions are generated by a fixed rule (nothing here calls a model): the invoices are mostly right, the handwritten
 * documents are wrong more often, and the confidence says one thing while the labels say another. The numbers are invented for the illustration; the arithmetic is the lesson.
 */
data class Rec(val docType: String, val confidence: Int, val correct: Boolean)

data class TypeRow(val docType: String, val correct: Int, val total: Int, val percent: Int)

data class Bucket(val label: String, val count: Int, val said: Int, val right: Int)

data class Kept(val count: Int, val precision: Int)

/** (document type, stated confidence, was it correct) for n extractions, from a fixed rule. */
fun makeRecords(n: Int = 200): List<Rec> = List(n) { i ->
    val docType = if (i % 5 == 0) "handwritten" else "invoice"
    val confidence = 50 + (i * 37) % 51
    val penalty = if (docType == "handwritten") 30 else 0
    Rec(docType, confidence, (i * 53) % 100 < confidence - 12 - penalty)
}

/** A whole-number percentage, rounded half up; 0 for an empty whole. */
fun ratio(part: Int, whole: Int): Int = if (whole > 0) (200 * part + whole) / (2 * whole) else 0

fun overallAccuracy(records: List<Rec>): Int = ratio(records.count { it.correct }, records.size)

fun accuracyByType(records: List<Rec>): List<TypeRow> =
    records.groupBy { it.docType }.toSortedMap().map { (t, rs) -> TypeRow(t, rs.count { it.correct }, rs.size, ratio(rs.count { it.correct }, rs.size)) }

/** One row per non-empty confidence bucket: label, count, confidence it claimed, how often it was right. */
fun calibrationTable(records: List<Rec>): List<Bucket> =
    records.groupBy { minOf(it.confidence / 10 * 10, 90) }.toSortedMap().map { (low, rs) ->
        Bucket(if (low == 90) "90-100" else "$low-${low + 9}", rs.size, ratio(rs.sumOf { it.confidence }, 100 * rs.size), ratio(rs.count { it.correct }, rs.size))
    }

/** How many extractions would be accepted without review, and how often those are right. */
fun precisionAbove(records: List<Rec>, threshold: Int): Kept {
    val kept = records.filter { it.confidence >= threshold }
    return Kept(kept.size, ratio(kept.count { it.correct }, kept.size))
}

fun main() {
    val records = makeRecords()
    println("overall accuracy: ${overallAccuracy(records)}%")
    for (t in accuracyByType(records)) println("${t.docType}: ${t.correct} of ${t.total} correct, ${t.percent}%")
    for (b in calibrationTable(records)) println("bucket ${b.label}: ${b.count} extractions, said ${b.said}%, right ${b.right}%")
    for (threshold in listOf(60, 70, 80, 90)) {
        val k = precisionAbove(records, threshold)
        println("accept at $threshold or above: ${k.count} extractions, ${k.precision}% right")
    }
}
