# Case lists of module 27-choosing-an-extension: one entry per practice (see tools/make_cases.py).
# Runs with PRACTICES and X in scope; names defined here are local to this file.

PRACTICES[f"{X}/27-choosing-an-extension/unit-01/practice-1"] = {
    "name": "extension_choice", "suite": "ExtensionChoiceTest", "langs": ["python", "typescript", "java", "kotlin"],
    "cases": [
        ("m1", "main", "every situation of the bank gets its mechanism and its reason"),
        ("e1", "edge", "a rule that must hold goes to a hook whatever else is true"),
        ("e2", "edge", "an outside system needs a server and noisy work alone needs a subagent"),
        ("e3", "edge", "knowledge goes to the file or skill that loads it at the right time"),
        ("e4", "edge", "a plugin carries a skill hook subagent or server to a second repository and nothing else"),
        ("e5", "edge", "in an application the platform may supply the schema and only a remote server replaces your own tool"),
        ("e6", "edge", "an unknown value is an error and a missing key takes its default"),
        ("e7", "edge", "a pipeline a condition a long command and an event are not intervals"),
        ("e8", "edge", "an interval is a loop in the session and a routine or desktop task when it must outlive it"),
        ("e9", "edge", "a personal preference goes to a style a status line or a key binding and knowledge keeps its own rules"),
    ],
    "plants": {
        "wrong-guarantee-yields-to-timing": (["e1"], "lets a schedule or an event decide before a rule that must hold every time"),
        "wrong-guarantee-yields-to-scope": (["e1"], "does not make a hook of a rule that comes with a path-scoped convention"),
        "wrong-server-yields-to-timing": (["e2"], "lets a schedule or an event decide before an outside system that needs a server"),
        "wrong-noisy-yields-to-pipeline": (["e2"], "lets a pipeline or an away run decide before noisy work that needs its own context"),
        "wrong-scope-without-convention": (["e3"], "sends a path scope with no convention to the path rules"),
        "wrong-reference-follows-scope": (["e3"], "drops reference material when it is also path scoped"),
        "wrong-hook-not-carried": (["e4"], "leaves a hook out of what a plugin carries"),
        "wrong-path-rule-carried": (["e4"], "packages a path rule as a plugin, which cannot carry one"),
        "wrong-server-beats-builtin": (["e5"], "prefers a remote server to the schema the platform supplies"),
        "wrong-server-without-remote": (["e5"], "uses the connector in an application when no outside system needs it or no remote server exists"),
        "wrong-no-validation": (["e6"], "accepts a knowledge kind it does not know"),
        "wrong-no-timing-validation": (["e6"], "accepts a timing it does not know"),
        "wrong-away-sees-local-files": (["e6"], "lets a run with the computer off read local files"),
        "wrong-pipeline-needs-no-timing": (["e7"], "treats a pipeline job that also has an interval as a loop"),
        "wrong-condition-needs-session": (["e7"], "does not make a goal of a condition when nobody is at the session"),
        "wrong-event-always-monitor": (["e7"], "watches an event in the session even when the computer is off"),
        "wrong-expiry-inclusive": (["e8"], "moves a job of exactly seven days off the loop that still holds it"),
        "wrong-desktop-without-local-files": (["e8"], "makes a desktop task of every long interval job, local files or not"),
        "wrong-knowledge-beats-personal": (["e9"], "answers a personal preference with the knowledge file when one is also given"),
        "wrong-personal-beats-timing": (["e9"], "answers a personal preference before a timed job"),
    },
}
