# Case lists of module 91-stakeholders-and-the-project-lifecycle: one entry per practice (see tools/make_cases.py).
# Runs with PRACTICES and X in scope; names defined here are local to this file.

PRACTICES[f"{X}/91-stakeholders-and-the-project-lifecycle/unit-01/practice-1"] = {
    "name": "design_record", "suite": "DesignRecordTest", "langs": ["python", "typescript", "java", "kotlin"],
    "cases": [
        ("m1", "main", "the eight sections are present in order and filled"),
        ("e1", "edge", "the decision statement carries the volume the latency the error cost and the accountable role"),
        ("e2", "edge", "the options include a recommended one that is the cheapest to meet the service levels and a reason for each rejection"),
        ("e3", "edge", "the break even accuracy is 98 percent and the recommendation states the cost"),
        ("e4", "edge", "each service level has a target within the case limits and a named owner"),
        ("e5", "edge", "segments are listed by error cost and handled by the break even"),
        ("e6", "edge", "the pilot to scale table has four assumptions each with a test and a stop trigger with a number"),
        ("e7", "edge", "the hand off names an owner a runbook a rollback and monitors"),
        ("e8", "edge", "the sponsor summary has at most 80 words and states the cost and the decision and no file holds personal data"),
    ],
    "plants": {
        "wrong-section-renamed": (['e4', 'm1'], "renames a required section, so the record no longer has its eight sections"),
        "wrong-todo-left": (["m1"], "leaves a TODO in the record"),
        "wrong-no-role": (["e1"], "does not name the role accountable for each credit"),
        "wrong-no-error-cost": (["e1"], "does not give the cost of a wrong credit or of a check"),
        "wrong-cheapest-not-recommended": (["e2", "e3", "e8"], "recommends an option that is not the cheapest one that meets the service levels"),
        "wrong-two-recommended": (['e2', 'e3', 'e8'], "recommends two options at once"),
        "wrong-rejection-no-reason": (["e2"], "rejects an option with a reason of two words"),
        "wrong-three-options": (["e2"], "compares only three options"),
        "wrong-breakeven-97": (["e3"], "states a break-even accuracy of 97 percent for costs that give 98"),
        "wrong-latency-2500": (["e4"], "promises a latency of 2500 ms against a limit of 2000"),
        "wrong-availability-99": (["e4"], "promises an availability of 99.0 percent against a floor of 99.5"),
        "wrong-sla-no-owner": (["e4"], "gives a service level the owner TBD"),
        "wrong-status-reviewed": (["e5"], "sends a segment at the break-even accuracy to a person"),
        "wrong-status-97-auto": (["e5"], "lets a segment below the break-even accuracy go out unreviewed"),
        "wrong-segment-order": (["e5"], "lists the cheapest segment before a costlier one"),
        "wrong-shape-unnamed": (["e5"], "describes a failure shape in a word that names no shape"),
        "wrong-pilot-three": (["e6"], "names three assumptions of the pilot and not four"),
        "wrong-trigger-no-number": (["e6"], "gives a stop trigger with no number in it"),
        "wrong-no-runbook": (["e7"], "does not say who owns a runbook"),
        "wrong-no-rollback": (["e7"], "has no rollback and no previous model kept"),
        "wrong-summary-81-words": (["e8"], "writes a sponsor summary of 81 words"),
        "wrong-summary-no-cost": (["e8"], "leaves the monthly cost out of the sponsor summary"),
        "wrong-summary-no-decision": (["e8"], "does not ask the sponsor for a decision"),
        "wrong-home-path": (["e8"], "writes a personal home path into the record"),
    },
}
