# Case lists of module 92-enabling-teams-and-operations: one entry per practice (see tools/make_cases.py).
# Runs with PRACTICES and X in scope; names defined here are local to this file.

PRACTICES[f"{X}/92-enabling-teams-and-operations/unit-01/practice-1"] = {
    "name": "rollout", "suite": "RolloutTest", "langs": ["python", "typescript", "java", "kotlin"],
    "cases": [
        ("m1", "main", "the managed file locks permissions and protects the environment file"),
        ("e1", "edge", "keys only an organisation can set live in the managed file and never in the project file"),
        ("e2", "edge", "plugins come only from the companys marketplace and cannot be sideloaded"),
        ("e3", "edge", "only the managed mcp allowlist applies and a server is never allowed and denied"),
        ("e4", "edge", "the model choice is locked by a list and the effort cap is at most high"),
        ("e5", "edge", "the group spend limits add up to the organisation limit and no more"),
        ("e6", "edge", "adoption is measured by outcomes against a baseline of at least 4 weeks"),
        ("e7", "edge", "the precedence table is in the documented order and no file holds personal data"),
    ],
    "plants": {
        "wrong-managed-rules-open": (["m1"], "lets user and project files add permission rules beside the managed ones"),
        "wrong-bypass-allowed": (["m1"], "leaves the bypass permissions mode available"),
        "wrong-env-readable": (["m1"], "does not deny reading the environment file"),
        "wrong-hooks-in-project": (["e1"], "puts a managed-only lock in the shared project file, where it has no effect"),
        "wrong-marketplaces-in-project": (["e1"], "puts the marketplace allowlist in the shared project file"),
        "wrong-hooks-open": (["e1"], "lets any hook run"),
        "wrong-marketplace-empty": (["e2"], "allows no marketplace at all, the official one included"),
        "wrong-marketplace-foreign": (["e2"], "allows a marketplace the company does not own"),
        "wrong-sideload-open": (["e2"], "lets a plugin be loaded from a folder with a flag"),
        "wrong-mcp-not-exclusive": (["e3"], "lets a user's own allowlist widen the managed one"),
        "wrong-mcp-two-keys": (["e3"], "writes an allowlist entry with two keys"),
        "wrong-mcp-bad-name": (["e3"], "allows a server whose name has a space"),
        "wrong-mcp-allowed-and-denied": (["e3"], "allows and denies the same server"),
        "wrong-no-model-list": (["e4"], "sets a default model and leaves the choice open"),
        "wrong-model-outside-list": (["e4"], "sets a default model that the list does not allow"),
        "wrong-effort-xhigh": (["e4"], "caps the effort one level above high"),
        "wrong-effort-max": (["e4"], "sets the effort cap to max, which sets no cap"),
        "wrong-groups-over-org": (["e5"], "gives the groups a total one unit over the organisation limit"),
        "wrong-member-over-group": (["e5"], "gives a member a limit above the smallest group's"),
        "wrong-no-usage-credits": (["e5"], "does not say that usage credits are on"),
        "wrong-baseline-3-weeks": (["e6"], "takes a baseline of three weeks"),
        "wrong-activity-target": (["e6"], "sets lines accepted as a target"),
        "wrong-one-target": (["e6"], "sets one outcome target and not two"),
        "wrong-precedence-order": (["e7"], "puts the shared project file above the project local file"),
        "wrong-no-group-note": (["e7"], "does not say that server-managed settings cannot target a group yet"),
        "wrong-home-path": (["e7"], "writes a personal home path into the plan"),
    },
}
