# Case lists of module 93-professional-capstone: one entry per practice (see tools/make_cases.py).
# Runs with PRACTICES and X in scope; names defined here are local to this file.

PRACTICES[f"{X}/93-professional-capstone/unit-01/practice-1"] = {
    "name": "launch_review", "suite": "LaunchReviewTest", "langs": ["python", "typescript", "java", "kotlin"],
    "cases": [
        ("m1", "main", "a design that sits exactly at every threshold has no findings and is approved"),
        ("e1", "edge", "a missing feedback loop a filter after ranking or no way back is a high finding and the design is rejected"),
        ("e2", "edge", "medium findings revise the design and low findings alone approve it"),
        ("e3", "edge", "findings are ordered by severity then domain then rule id"),
        ("e4", "edge", "each numeric threshold passes exactly at its value and fails one step beyond"),
        ("e5", "edge", "the scorecard counts the findings of each domain from P1 to P7"),
        ("e6", "edge", "the accuracy a design needs is the break even rounded up from the two costs"),
        ("e7", "edge", "rules that depend on a second fact fire only when both hold"),
        ("e8", "edge", "retrieval and privacy flaws are high findings in domains P3 and P5"),
        ("e9", "edge", "a design with every flaw gets all 22 findings and a scorecard that adds up"),
    ],
    "plants": {
        "wrong-feedback-rule-dropped": (['e1', 'e2', 'e3', 'e9'], "does not flag a design with no feedback loop"),
        "wrong-autonomy-ignores-path": (['e1', 'e2', 'e3', 'e4', 'e7', 'e8', 'm1'], "flags an agent even when the path is not known to be fixed"),
        "wrong-team-price-15": (['e1', 'e2', 'e3', 'e4', 'e7', 'e8', 'm1'], "flags a team whose value is exactly at the break-even of 15 chats"),
        "wrong-tool-tokens-10000": (["e4"], "flags tool definitions of exactly 10000 tokens"),
        "wrong-deferral-ignored": (["e4"], "flags a large tool set although tool search defers it"),
        "wrong-eval-20": (['e1', 'e2', 'e3', 'e4', 'e7', 'e8', 'm1'], "flags an evaluation set of exactly 20 cases as small"),
        "wrong-stages-3": (['e1', 'e2', 'e4', 'e7', 'e8', 'm1'], "flags a roll-out of exactly three stages as a big bang"),
        "wrong-retain-floor": (["e4"], "flags a retention of exactly the floor"),
        "wrong-retain-ceiling": (['e1', 'e2', 'e3', 'e4', 'e7', 'e8', 'm1'], "flags a retention of exactly the ceiling"),
        "wrong-filter-rule-dropped": (['e1', 'e8', 'e9'], "does not flag a filter applied after ranking"),
        "wrong-stale-rule-dropped": (['e8', 'e9'], "does not flag an index with no replacement on change"),
        "wrong-rights-rule-dropped": (['e8', 'e9'], "does not flag an agent that holds the rights and not the user"),
        "wrong-pii-always": (['e1', 'e2', 'e3', 'e4', 'e7', 'e8', 'm1'], "flags identifiers reaching the model for every design"),
        "wrong-residency-always": (['e1', 'e2', 'e3', 'e4', 'e7', 'e8', 'm1'], "flags unmet residency for every design"),
        "wrong-irreversible-medium": (["e7"], "grades an irreversible action with no person as medium"),
        "wrong-human-step-ignored": (['e1', 'e2', 'e3', 'e4', 'e7', 'e8', 'm1'], "flags every irreversible action even with a human step"),
        "wrong-team-size-10": (["e4"], "flags a team of exactly 10 without managed settings"),
        "wrong-sla-and": (["e4"], "flags a service level only when both numbers are missing"),
        "wrong-owner-rule-dropped": (['e2', 'e3', 'e9'], "does not flag a design with no accountable owner"),
        "wrong-order-by-domain": (['e3', 'e8', 'e9'], "orders findings by domain and not by severity first"),
        "wrong-verdict-any-finding": (["e2"], "revises a design that has only low findings"),
        "wrong-scorecard-no-p7": (['e5', 'e9', 'm1'], "leaves domain P7 out of the scorecard"),
        "wrong-ceil-floor": (["e6"], "rounds the review cost percent down"),
        "wrong-no-floor-at-zero": (["e6"], "returns a negative accuracy when a check costs more than an error"),
        "wrong-rollback-medium": (["e1"], "grades a missing way back as medium and not high"),
        "wrong-volatile-low": (["e3"], "grades a volatile prefix as low, so it sorts among the low findings"),
        "wrong-scorecard-known-rules": (["e5"], "counts in the scorecard only the findings whose rule id has a hyphen"),
        "wrong-stale-medium": (["e8"], "grades an index that is not replaced on change as medium and not high"),
        "wrong-report-truncated": (["e9"], "returns at most 21 findings"),
    },
}
