# Planted wrong solutions of module 06-prompting-fundamentals: exact replacements against the practice's reference (see tools/make_plants.py).
# Runs with PLANTS, X and both() in scope; names defined here are local to this file.

PLANTS[f"{X}/06-prompting-fundamentals/unit-01/practice-1"] = {
    "python": ("prompt_builder.py", {
        "wrong-task-first": [('    parts.append(_block("task", _fill(task or "", variables)))\n', ""),
                              ("    parts = []\n", '    parts = [_block("task", _fill(task, variables))]\n')],
        "wrong-empty-sections": [('    if _present(spec.get("role")):', '    if "role" in spec:')],
        "wrong-missing-variable-silent": [('raise ValueError(f"missing variable: {name}")', 'return "{{" + name + "}}"')],
        "wrong-blank-task-accepted": [("    if not _present(task):", "    if task is None:")],
        "wrong-no-escape": [('{_escape(doc["text"])}', '{doc["text"]}')],
        "wrong-fill-documents": [("def _render_document(index, doc):", "def _render_document(index, doc, variables={}):"),
                                 ('{_escape(doc["text"])}', '{_escape(_fill(doc["text"], variables))}'),
                                 ("_render_document(i, doc) for", "_render_document(i, doc, variables) for")],
        "wrong-documents-sorted": [("enumerate(documents, start=1)", 'enumerate(sorted(documents, key=lambda d: d["name"]), start=1)')],
    }),
    "typescript": ("promptBuilder.ts", {
        "wrong-task-first": [('  parts.push(block("task", fill(task, variables)));\n', ""),
                              ("  const parts: string[] = [];\n", '  const parts: string[] = [block("task", fill(task, variables))];\n')],
        "wrong-empty-sections": [("if (present(spec.role)) parts.push(", "if (spec.role !== undefined && spec.role !== null) parts.push(")],
        "wrong-missing-variable-silent": [("throw new Error(`missing variable: ${name}`);", 'return "{{" + name + "}}";')],
        "wrong-blank-task-accepted": [('if (!present(task)) throw new Error("task is required");', 'if (task === null || task === undefined) throw new Error("task is required");')],
        "wrong-no-escape": [("${escapeText(doc.text)}", "${doc.text}")],
        "wrong-fill-documents": [("function renderDocument(index: number, doc: Doc): string {", "function renderDocument(index: number, doc: Doc, variables: Record<string, string> = {}): string {"),
                                 ("${escapeText(doc.text)}", "${escapeText(fill(doc.text, variables))}"),
                                 ("renderDocument(i + 1, doc))", "renderDocument(i + 1, doc, variables))")],
        "wrong-documents-sorted": [("documents.map((doc, i) =>", "[...documents].sort((a, b) => a.name.localeCompare(b.name)).map((doc, i) =>")],
    }),
    "java": ("PromptBuilder.java", {
        "wrong-task-first": [('        parts.add(block("task", fill(spec.task(), variables)));\n        return join(parts);', "        return join(parts);"),
                              ("        List<String> parts = new ArrayList<>();\n", '        List<String> parts = new ArrayList<>();\n        parts.add(block("task", fill(spec.task(), variables)));\n')],
        "wrong-empty-sections": [("if (present(spec.role())) parts.add(", "if (spec.role() != null) parts.add(")],
        "wrong-missing-variable-silent": [('if (!variables.containsKey(name)) throw new IllegalArgumentException("missing variable: " + name);', 'if (!variables.containsKey(name)) return "{{" + name + "}}";')],
        "wrong-blank-task-accepted": [("if (!present(task)) throw", "if (task == null) throw")],
        "wrong-no-escape": [('+ escape(doc.text()) +', '+ doc.text() +')],
        "wrong-fill-documents": [("renderDocument(int index, Doc doc) {", "renderDocument(int index, Doc doc, Map<String, String> variables) {"),
                                 ('+ escape(doc.text()) +', '+ escape(fill(doc.text(), variables)) +'),
                                 ("renderDocument(i++, doc)", "renderDocument(i++, doc, variables)")],
        "wrong-documents-sorted": [("for (Doc doc : spec.documents()) rendered.add(", "for (Doc doc : spec.documents().stream().sorted(java.util.Comparator.comparing(Doc::name)).toList()) rendered.add(")],
    }),
    "kotlin": ("PromptBuilder.kt", {
        "wrong-task-first": [('    parts += block("task", fill(spec.task!!, variables))\n', ""),
                              ("    val parts = mutableListOf<String>()\n", '    val parts = mutableListOf(block("task", fill(spec.task!!, variables)))\n')],
        "wrong-empty-sections": [("if (present(spec.role)) parts +=", "if (spec.role != null) parts +=")],
        "wrong-missing-variable-silent": [('    require(name in variables) { "missing variable: $name" }\n    return variables.getValue(name)\n', '    return variables[name] ?: "{{$name}}"\n')],
        "wrong-blank-task-accepted": [("require(present(task))", "require(task != null)")],
        "wrong-no-escape": [("${escape(doc.text)}", "${doc.text}")],
        "wrong-fill-documents": [("renderDocument(index: Int, doc: Doc): String {", "renderDocument(index: Int, doc: Doc, variables: Map<String, String>): String {"),
                                 ("${escape(doc.text)}", "${escape(fill(doc.text, variables))}"),
                                 ("renderDocument(i + 1, doc)", "renderDocument(i + 1, doc, variables)")],
        "wrong-documents-sorted": [("spec.documents.mapIndexed {", "spec.documents.sortedBy { it.name }.mapIndexed {")],
    }),
}
