# Planted wrong solutions of module 18-model-choice-cost-and-migration: exact replacements against the practice's reference (see tools/make_plants.py).
# Runs with PLANTS, X and both() in scope; names defined here are local to this file.

PLANTS[f"{X}/18-model-choice-cost-and-migration/unit-01/practice-1"] = {
    "python": ("router.py", {
        "wrong-flat-cache-read": [('usage.get("cache_read_input_tokens", 0) * price * model["cache_read_multiplier"]', 'usage.get("cache_read_input_tokens", 0) * price * 0.1')],
        "wrong-batch-output-only": [('+ usage.get("output_tokens", 0) * model["output"]\n    return round(_apply_batch(total, batch), 6)',
                                     '+ usage.get("output_tokens", 0) * model["output"] * (0.5 if batch else 1)\n    return round(total, 6)')],
        "wrong-first-eligible": [('best = min(models, key=lambda m: (request_cost(m, usage, batch), m["tier"], m["id"]))', "best = models[0]")],
        "wrong-ignore-context": [('\n            and input_tokens <= model["context"]\n            and task.get("max_tokens", 0) <= model["max_output"])', ")")],
        "wrong-tie-high-tier": [('m["tier"], m["id"]))', '-m["tier"], m["id"]))')],
        "wrong-deprecated-allowed": [('return (not model.get("deprecated", False)\n            and model["tier"]', 'return (model["tier"]')],
        "wrong-empty-choice-allowed": [("    if not models:\n        raise NoModelError", "    if False:\n        raise NoModelError")],
        "wrong-unsplit-write-ignored": [('return usage.get("cache_creation_input_tokens", 0), 0', "return 0, 0")],
        "wrong-batch-picks-priciest": [('best = min(models, key=lambda m: (request_cost(m, usage, batch), m["tier"], m["id"]))', 'best = min(models, key=lambda m: ((-1 if batch else 1) * request_cost(m, usage, False), m["tier"], m["id"]))')],
        "wrong-ignore-output-limit": [('\n            and task.get("max_tokens", 0) <= model["max_output"])', ")")],
    }),
    "typescript": ("router.ts", {
        "wrong-flat-cache-read": [("(usage.cache_read_input_tokens ?? 0) * price * model.cache_read_multiplier", "(usage.cache_read_input_tokens ?? 0) * price * 0.1")],
        "wrong-batch-output-only": [("(usage.output_tokens ?? 0) * model.output;\n  return Math.round(applyBatch(total, batch) * 1e6) / 1e6;",
                                     "(usage.output_tokens ?? 0) * model.output * (batch ? 0.5 : 1);\n  return Math.round(total * 1e6) / 1e6;")],
        "wrong-first-eligible": [("return scored[0].m.id;", "return models[0].id;")],
        "wrong-ignore-context": [(" && tokens <= model.context && (task.max_tokens ?? 0) <= model.max_output;", ";")],
        "wrong-tie-high-tier": [("a.m.tier - b.m.tier ||", "b.m.tier - a.m.tier ||")],
        "wrong-deprecated-allowed": [("return !model.deprecated && model.tier", "return model.tier")],
        "wrong-empty-choice-allowed": [("if (models.length === 0) throw", "if (false) throw")],
        "wrong-unsplit-write-ignored": [("if (!created) return [usage.cache_creation_input_tokens ?? 0, 0];", "if (!created) return [0, 0];")],
        "wrong-batch-picks-priciest": [("cost: requestCost(m, usage, batch) }", "cost: (batch ? -1 : 1) * requestCost(m, usage, false) }")],
        "wrong-ignore-output-limit": [(" && (task.max_tokens ?? 0) <= model.max_output;", ";")],
    }),
    "java": ("Router.java", {
        "wrong-flat-cache-read": [('d(model, "cache_read_multiplier")', "0.1")],
        "wrong-batch-output-only": [('n(usage, "output_tokens") * d(model, "output");\n        return Math.round(applyBatch(total, batch) * 1e6) / 1e6;',
                                     'n(usage, "output_tokens") * d(model, "output") * (batch ? 0.5 : 1.0);\n        return Math.round(total * 1e6) / 1e6;')],
        "wrong-first-eligible": [('.min(Comparator.<Map<String, Object>>comparingDouble(m -> requestCost(m, usage, batch))\n                        .thenComparingLong(m -> n(m, "tier"))\n                        .thenComparing(m -> (String) m.get("id")))', ".findFirst()")],
        "wrong-ignore-context": [(' && tokens <= n(model, "context") && n(task, "max_tokens") <= n(model, "max_output");', ";")],
        "wrong-tie-high-tier": [('.thenComparingLong(m -> n(m, "tier"))', '.thenComparingLong(m -> -n(m, "tier"))')],
        "wrong-deprecated-allowed": [('return !Boolean.TRUE.equals(model.get("deprecated")) && n(model, "tier")', 'return n(model, "tier")')],
        "wrong-empty-choice-allowed": [("if (models.isEmpty()) throw", "if (false) throw")],
        "wrong-unsplit-write-ignored": [('return new long[] {n(usage, "cache_creation_input_tokens"), 0};', "return new long[] {0, 0};")],
        "wrong-batch-picks-priciest": [("comparingDouble(m -> requestCost(m, usage, batch))", "comparingDouble(m -> (batch ? -1 : 1) * requestCost(m, usage, false))")],
        "wrong-ignore-output-limit": [(' && n(task, "max_tokens") <= n(model, "max_output");', ";")],
    }),
    "kotlin": ("Router.kt", {
        "wrong-flat-cache-read": [('d(model, "cache_read_multiplier")', "0.1")],
        "wrong-batch-output-only": [('n(usage, "output_tokens") * d(model, "output")\n    return Math.round(applyBatch(total, batch) * 1e6) / 1e6',
                                     'n(usage, "output_tokens") * d(model, "output") * (if (batch) 0.5 else 1.0)\n    return Math.round(total * 1e6) / 1e6')],
        "wrong-first-eligible": [('val best = models.minWithOrNull(compareBy<Map<String, Any?>> { requestCost(it, usage, batch) }.thenBy { n(it, "tier") }.thenBy { it["id"] as String })', "val best = models.firstOrNull()")],
        "wrong-ignore-context": [(' && tokens <= n(model, "context") && n(task, "max_tokens") <= n(model, "max_output")', "")],
        "wrong-tie-high-tier": [('.thenBy { n(it, "tier") }', ".thenByDescending { n(it, \"tier\") }")],
        "wrong-deprecated-allowed": [('return model["deprecated"] != true && n(model, "tier")', 'return n(model, "tier")')],
        "wrong-empty-choice-allowed": [("if (models.isEmpty()) throw", "if (false) throw")],
        "wrong-unsplit-write-ignored": [('?: return Pair(n(usage, "cache_creation_input_tokens"), 0L)', "?: return Pair(0L, 0L)")],
        "wrong-batch-picks-priciest": [("{ requestCost(it, usage, batch) }", "{ (if (batch) -1 else 1) * requestCost(it, usage, false) }")],
        "wrong-ignore-output-limit": [(' && n(task, "max_tokens") <= n(model, "max_output")', "")],
    }),
}
