# Planted wrong solutions of module 27-choosing-an-extension: exact replacements against the practice's reference (see tools/make_plants.py).
# Runs with PLANTS, X and both() in scope; names defined here are local to this file.

PLANTS[f"{X}/27-choosing-an-extension/unit-01/practice-1"] = {
    "python": ("extension_choice.py", {
        "wrong-guarantee-needs-no-knowledge": [('if situation.get("guarantee", False):', 'if situation.get("guarantee", False) and knowledge == "none":')],
        "wrong-server-skipped-when-noisy": [('elif situation.get("external_system", False):', 'elif situation.get("external_system", False) and not situation.get("noisy", False):')],
        "wrong-scope-ignored": [('if situation.get("path_scoped", False) else', "if False else")],
        "wrong-one-reason-for-skills": [('_pick("skill", "repeatable-procedure")', '_pick("skill", "on-demand-reference")')],
        "wrong-plugin-at-one-repo": [("if repos >= 2 and", "if repos >= 1 and")],
        "wrong-plugin-for-conventions": [(' and choice["mechanism"] in CARRIED:', ":")],
        "wrong-api-provided-schema-ignored": [('if situation.get("builtin_covers", False):', "if False:")],
        "wrong-api-server-without-remote": [(' and situation.get("remote_server", False):', ":")],
        "wrong-no-validation": [("if knowledge not in KNOWLEDGE:", "if False:")],
        "wrong-fallthrough-skill": [('_pick("builtin-tool", "built-in-covers")', '_pick("skill", "on-demand-reference")')],
        "wrong-timing-outranks-hook": [('if situation.get("guarantee", False):', 'if situation.get("guarantee", False) and situation.get("timing", "none") == "none":')],
        "wrong-timing-outranks-noisy": [('elif situation.get("noisy", False):', 'elif situation.get("noisy", False) and situation.get("timing", "none") == "none":')],
        "wrong-no-timing-validation": [('if situation.get("timing", "none") not in TIMINGS:', "if False:")],
        "wrong-away-sees-local-files": [('if situation.get("presence", "session") == "away" and situation.get("local_files", False):', "if False:")],
        "wrong-pipeline-as-loop": [('if presence == "pipeline":', "if False:")],
        "wrong-event-polled": [('else _pick("monitor", "push-not-poll")', 'else _pick("loop", "session-rhythm")')],
        "wrong-no-expiry": [('if situation.get("lasts_days", 1) > LOOP_EXPIRY_DAYS:', "if False:")],
        "wrong-loop-while-away": [('        if presence == "away":\n            return _pick("routine", "runs-unattended")\n', "")],
        "wrong-voice-in-instruction-file": [('_pick("output-style", "response-voice")', '_pick("claude-md", "always-known")')],
        "wrong-display-as-style": [('_pick("status-line", "personal-display")', '_pick("output-style", "response-voice")')],
    }),
    "typescript": ("extensionChoice.ts", {
        "wrong-guarantee-needs-no-knowledge": [("if (s.guarantee ?? false) choice", 'if ((s.guarantee ?? false) && knowledge === "none") choice')],
        "wrong-server-skipped-when-noisy": [("else if (s.external_system ?? false) choice", "else if ((s.external_system ?? false) && !(s.noisy ?? false)) choice")],
        "wrong-scope-ignored": [("(s.path_scoped ?? false) ?", "false ?")],
        "wrong-one-reason-for-skills": [('pick("skill", "repeatable-procedure")', 'pick("skill", "on-demand-reference")')],
        "wrong-plugin-at-one-repo": [("if (repos >= 2 && CARRIED", "if (repos >= 1 && CARRIED")],
        "wrong-plugin-for-conventions": [(" && CARRIED.includes(choice.mechanism)", "")],
        "wrong-api-provided-schema-ignored": [("if (s.builtin_covers ?? false) return", "if (false) return")],
        "wrong-api-server-without-remote": [(" && (s.remote_server ?? false)", "")],
        "wrong-no-validation": [("if (!KNOWLEDGE.includes(knowledge)) throw", "if (false) throw")],
        "wrong-fallthrough-skill": [('pick("builtin-tool", "built-in-covers")', 'pick("skill", "on-demand-reference")')],
        "wrong-timing-outranks-hook": [("if (s.guarantee ?? false) choice", 'if ((s.guarantee ?? false) && (s.timing ?? "none") === "none") choice')],
        "wrong-timing-outranks-noisy": [("else if (s.noisy ?? false) choice", 'else if ((s.noisy ?? false) && (s.timing ?? "none") === "none") choice')],
        "wrong-no-timing-validation": [('if (!TIMINGS.includes(s.timing ?? "none")) throw', "if (false) throw")],
        "wrong-away-sees-local-files": [('if ((s.presence ?? "session") === "away" && (s.local_files ?? false)) throw', "if (false) throw")],
        "wrong-pipeline-as-loop": [('if (presence === "pipeline") return', "if (false) return")],
        "wrong-event-polled": [(': pick("monitor", "push-not-poll");', ': pick("loop", "session-rhythm");')],
        "wrong-no-expiry": [("if ((s.lasts_days ?? 1) > LOOP_EXPIRY_DAYS) return", "if (false) return")],
        "wrong-loop-while-away": [('    if (presence === "away") return pick("routine", "runs-unattended");\n', "")],
        "wrong-voice-in-instruction-file": [('pick("output-style", "response-voice")', 'pick("claude-md", "always-known")')],
        "wrong-display-as-style": [('pick("status-line", "personal-display")', 'pick("output-style", "response-voice")')],
    }),
    "java": ("ExtensionChoice.java", {
        "wrong-guarantee-needs-no-knowledge": [('if (flag(situation, "guarantee")) choice', 'if (flag(situation, "guarantee") && knowledge.equals("none")) choice')],
        "wrong-server-skipped-when-noisy": [('else if (flag(situation, "external_system")) choice', 'else if (flag(situation, "external_system") && !flag(situation, "noisy")) choice')],
        "wrong-scope-ignored": [('flag(situation, "path_scoped") ?', "false ?")],
        "wrong-one-reason-for-skills": [('new Choice("skill", "repeatable-procedure")', 'new Choice("skill", "on-demand-reference")')],
        "wrong-plugin-at-one-repo": [("if (repos >= 2 &&", "if (repos >= 1 &&")],
        "wrong-plugin-for-conventions": [(" && CARRIED.contains(choice.mechanism())", "")],
        "wrong-api-provided-schema-ignored": [('if (flag(situation, "builtin_covers")) return', "if (false) return")],
        "wrong-api-server-without-remote": [(' && flag(situation, "remote_server")', "")],
        "wrong-no-validation": [("if (!KNOWLEDGE.contains(knowledge)) throw", "if (false) throw")],
        "wrong-fallthrough-skill": [('new Choice("builtin-tool", "built-in-covers")', 'new Choice("skill", "on-demand-reference")')],
        "wrong-timing-outranks-hook": [('if (flag(situation, "guarantee")) choice', 'if (flag(situation, "guarantee") && text(situation, "timing", "none").equals("none")) choice')],
        "wrong-timing-outranks-noisy": [('else if (flag(situation, "noisy")) choice', 'else if (flag(situation, "noisy") && text(situation, "timing", "none").equals("none")) choice')],
        "wrong-no-timing-validation": [('if (!TIMINGS.contains(text(situation, "timing", "none"))) throw', "if (false) throw")],
        "wrong-away-sees-local-files": [('if (text(situation, "presence", "session").equals("away") && flag(situation, "local_files")) throw', "if (false) throw")],
        "wrong-pipeline-as-loop": [('if (presence.equals("pipeline")) return', "if (false) return")],
        "wrong-event-polled": [(': new Choice("monitor", "push-not-poll");', ': new Choice("loop", "session-rhythm");')],
        "wrong-no-expiry": [("if (days > LOOP_EXPIRY_DAYS) return", "if (false) return")],
        "wrong-loop-while-away": [('            if (presence.equals("away")) return new Choice("routine", "runs-unattended");\n', "")],
        "wrong-voice-in-instruction-file": [('new Choice("output-style", "response-voice")', 'new Choice("claude-md", "always-known")')],
        "wrong-display-as-style": [('new Choice("status-line", "personal-display")', 'new Choice("output-style", "response-voice")')],
    }),
    "kotlin": ("ExtensionChoice.kt", {
        "wrong-guarantee-needs-no-knowledge": [('flag(situation, "guarantee") ->', 'flag(situation, "guarantee") && knowledge == "none" ->')],
        "wrong-server-skipped-when-noisy": [('flag(situation, "external_system") -> Choice("mcp", "external-system")', 'flag(situation, "external_system") && !flag(situation, "noisy") -> Choice("mcp", "external-system")')],
        "wrong-scope-ignored": [('if (flag(situation, "path_scoped")) Choice("path-rule"', 'if (false) Choice("path-rule"')],
        "wrong-one-reason-for-skills": [('Choice("skill", "repeatable-procedure")', 'Choice("skill", "on-demand-reference")')],
        "wrong-plugin-at-one-repo": [("repos >= 2 &&", "repos >= 1 &&")],
        "wrong-plugin-for-conventions": [(" && choice.mechanism in CARRIED", "")],
        "wrong-api-provided-schema-ignored": [('if (flag(situation, "builtin_covers")) return', "if (false) return")],
        "wrong-api-server-without-remote": [(' && flag(situation, "remote_server")', "")],
        "wrong-no-validation": [("require(knowledge in KNOWLEDGE)", "require(true)")],
        "wrong-fallthrough-skill": [('else -> Choice("builtin-tool", "built-in-covers")', 'else -> Choice("skill", "on-demand-reference")')],
        "wrong-timing-outranks-hook": [('flag(situation, "guarantee") ->', 'flag(situation, "guarantee") && (situation["timing"] ?: "none") == "none" ->')],
        "wrong-timing-outranks-noisy": [('flag(situation, "noisy") ->', 'flag(situation, "noisy") && (situation["timing"] ?: "none") == "none" ->')],
        "wrong-no-timing-validation": [('require((situation["timing"]?.toString() ?: "none") in TIMINGS)', "require(true)")],
        "wrong-away-sees-local-files": [('require(!((situation["presence"]?.toString() ?: "session") == "away" && flag(situation, "local_files")))', "require(true)")],
        "wrong-pipeline-as-loop": [('if (presence == "pipeline") return', "if (false) return")],
        "wrong-event-polled": [('else Choice("monitor", "push-not-poll")', 'else Choice("loop", "session-rhythm")')],
        "wrong-no-expiry": [("if (days > LOOP_EXPIRY_DAYS) return", "if (false) return")],
        "wrong-loop-while-away": [('        if (presence == "away") return Choice("routine", "runs-unattended")\n', "")],
        "wrong-voice-in-instruction-file": [('Choice("output-style", "response-voice")', 'Choice("claude-md", "always-known")')],
        "wrong-display-as-style": [('Choice("status-line", "personal-display")', 'Choice("output-style", "response-voice")')],
    }),
}
