# Planted wrong solutions of module 27-choosing-an-extension: exact replacements against the practice's reference (see tools/make_plants.py).
# Runs with PLANTS, X and both() in scope; names defined here are local to this file.
# Every plant fails exactly one edge case; the case it fails is named in tools/cases.d/27-choosing-an-extension.py.

PLANTS[f"{X}/27-choosing-an-extension/unit-01/practice-1"] = {
    "python": ("extension_choice.py", {
        "wrong-guarantee-yields-to-timing": [('if situation.get("guarantee", False):', 'if situation.get("guarantee", False) and situation.get("timing", "none") == "none":')],
        "wrong-guarantee-yields-to-scope": [('if situation.get("guarantee", False):', 'if situation.get("guarantee", False) and not situation.get("path_scoped", False):')],
        "wrong-server-yields-to-timing": [('if situation.get("external_system", False):', 'if situation.get("external_system", False) and situation.get("timing", "none") == "none":')],
        "wrong-noisy-yields-to-pipeline": [('if situation.get("noisy", False):', 'if situation.get("noisy", False) and situation.get("presence", "session") == "session":')],
        "wrong-scope-without-convention": [('if knowledge == "convention":', 'if knowledge == "convention" or path_scoped:')],
        "wrong-reference-follows-scope": [('if knowledge == "reference":', 'if knowledge == "reference" and not path_scoped:')],
        "wrong-hook-not-carried": [('CARRIED = ("skill", "hook", "subagent", "mcp")', 'CARRIED = ("skill", "subagent", "mcp")')],
        "wrong-path-rule-carried": [('CARRIED = ("skill", "hook", "subagent", "mcp")', 'CARRIED = ("skill", "hook", "subagent", "mcp", "path-rule")')],
        "wrong-server-beats-builtin": [('if situation.get("builtin_covers", False):', 'if situation.get("builtin_covers", False) and not situation.get("remote_server", False):')],
        "wrong-server-without-remote": [('situation.get("external_system", False) and situation.get("remote_server", False)', 'situation.get("external_system", False) or situation.get("remote_server", False)')],
        "wrong-no-validation": [("if knowledge not in KNOWLEDGE:", "if False:")],
        "wrong-no-timing-validation": [('if situation.get("timing", "none") not in TIMINGS:', "if False:")],
        "wrong-away-sees-local-files": [(' or (presence == "away" and local_files)', "")],
        "wrong-pipeline-needs-no-timing": [('if presence == "pipeline":', 'if presence == "pipeline" and timing == "none":')],
        "wrong-condition-needs-session": [('if timing == "condition":', 'if timing == "condition" and presence == "session":')],
        "wrong-event-always-monitor": [('if presence == "away" else _pick("monitor", "push-not-poll")', 'if False else _pick("monitor", "push-not-poll")')],
        "wrong-expiry-inclusive": [('situation.get("lasts_days", 1) > LOOP_EXPIRY_DAYS', 'situation.get("lasts_days", 1) >= LOOP_EXPIRY_DAYS')],
        "wrong-desktop-without-local-files": [('if situation.get("local_files", False) else _pick("routine", "runs-unattended")', 'if True else _pick("routine", "runs-unattended")')],
        "wrong-knowledge-beats-personal": [('        or _personal_choice(situation.get("personal", "none"))\n        or _knowledge_choice(knowledge, situation.get("path_scoped", False))\n',
                                           '        or _knowledge_choice(knowledge, situation.get("path_scoped", False))\n        or _personal_choice(situation.get("personal", "none"))\n')],
        "wrong-personal-beats-timing": [('        or _rhythm(situation)\n        or _personal_choice(situation.get("personal", "none"))\n',
                                        '        or _personal_choice(situation.get("personal", "none"))\n        or _rhythm(situation)\n')],
    }),
    "typescript": ("extensionChoice.ts", {
        "wrong-guarantee-yields-to-timing": [("if (s.guarantee ?? false)", 'if ((s.guarantee ?? false) && (s.timing ?? "none") === "none")')],
        "wrong-guarantee-yields-to-scope": [("if (s.guarantee ?? false)", "if ((s.guarantee ?? false) && !(s.path_scoped ?? false))")],
        "wrong-server-yields-to-timing": [("if (s.external_system ?? false) return", 'if ((s.external_system ?? false) && (s.timing ?? "none") === "none") return')],
        "wrong-noisy-yields-to-pipeline": [("if (s.noisy ?? false)", 'if ((s.noisy ?? false) && (s.presence ?? "session") === "session")')],
        "wrong-scope-without-convention": [('if (knowledge === "convention")', 'if (knowledge === "convention" || pathScoped)')],
        "wrong-reference-follows-scope": [('if (knowledge === "reference")', 'if (knowledge === "reference" && !pathScoped)')],
        "wrong-hook-not-carried": [('const CARRIED = ["skill", "hook", "subagent", "mcp"];', 'const CARRIED = ["skill", "subagent", "mcp"];')],
        "wrong-path-rule-carried": [('const CARRIED = ["skill", "hook", "subagent", "mcp"];', 'const CARRIED = ["skill", "hook", "subagent", "mcp", "path-rule"];')],
        "wrong-server-beats-builtin": [("if (s.builtin_covers ?? false) return", "if ((s.builtin_covers ?? false) && !(s.remote_server ?? false)) return")],
        "wrong-server-without-remote": [("(s.external_system ?? false) && (s.remote_server ?? false)", "(s.external_system ?? false) || (s.remote_server ?? false)")],
        "wrong-no-validation": [("if (!KNOWLEDGE.includes(knowledge))", "if (false)")],
        "wrong-no-timing-validation": [('if (!TIMINGS.includes(s.timing ?? "none"))', "if (false)")],
        "wrong-away-sees-local-files": [(' || (presence === "away" && localFiles)', "")],
        "wrong-pipeline-needs-no-timing": [('if (presence === "pipeline")', 'if (presence === "pipeline" && timing === "none")')],
        "wrong-condition-needs-session": [('if (timing === "condition")', 'if (timing === "condition" && presence === "session")')],
        "wrong-event-always-monitor": [('presence === "away" ? pick("routine", "runs-unattended")', 'false ? pick("routine", "runs-unattended")')],
        "wrong-expiry-inclusive": [("(s.lasts_days ?? 1) > LOOP_EXPIRY_DAYS", "(s.lasts_days ?? 1) >= LOOP_EXPIRY_DAYS")],
        "wrong-desktop-without-local-files": [('(s.local_files ?? false) ? pick("desktop-task"', 'true ? pick("desktop-task"')],
        "wrong-knowledge-beats-personal": [('    personalChoice(s.personal ?? "none") ??\n    knowledgeChoice(knowledge, s.path_scoped ?? false) ??\n',
                                           '    knowledgeChoice(knowledge, s.path_scoped ?? false) ??\n    personalChoice(s.personal ?? "none") ??\n')],
        "wrong-personal-beats-timing": [('    rhythm(s) ??\n    personalChoice(s.personal ?? "none") ??\n',
                                        '    personalChoice(s.personal ?? "none") ??\n    rhythm(s) ??\n')],
    }),
    "java": ("ExtensionChoice.java", {
        "wrong-guarantee-yields-to-timing": [('if (flag(s, "guarantee")) return', 'if (flag(s, "guarantee") && text(s, "timing", "none").equals("none")) return')],
        "wrong-guarantee-yields-to-scope": [('if (flag(s, "guarantee")) return', 'if (flag(s, "guarantee") && !flag(s, "path_scoped")) return')],
        "wrong-server-yields-to-timing": [('if (flag(s, "external_system")) return', 'if (flag(s, "external_system") && text(s, "timing", "none").equals("none")) return')],
        "wrong-noisy-yields-to-pipeline": [('if (flag(s, "noisy")) return', 'if (flag(s, "noisy") && text(s, "presence", "session").equals("session")) return')],
        "wrong-scope-without-convention": [('if (knowledge.equals("convention"))', 'if (knowledge.equals("convention") || pathScoped)')],
        "wrong-reference-follows-scope": [('if (knowledge.equals("reference"))', 'if (knowledge.equals("reference") && !pathScoped)')],
        "wrong-hook-not-carried": [('List.of("skill", "hook", "subagent", "mcp")', 'List.of("skill", "subagent", "mcp")')],
        "wrong-path-rule-carried": [('List.of("skill", "hook", "subagent", "mcp")', 'List.of("skill", "hook", "subagent", "mcp", "path-rule")')],
        "wrong-server-beats-builtin": [('if (flag(s, "builtin_covers")) return', 'if (flag(s, "builtin_covers") && !flag(s, "remote_server")) return')],
        "wrong-server-without-remote": [('flag(s, "external_system") && flag(s, "remote_server")', 'flag(s, "external_system") || flag(s, "remote_server")')],
        "wrong-no-validation": [("if (!KNOWLEDGE.contains(knowledge))", "if (false)")],
        "wrong-no-timing-validation": [('if (!TIMINGS.contains(text(situation, "timing", "none")))', "if (false)")],
        "wrong-away-sees-local-files": [(' || (presence.equals("away") && localFiles)', "")],
        "wrong-pipeline-needs-no-timing": [('if (presence.equals("pipeline")) return', 'if (presence.equals("pipeline") && timing.equals("none")) return')],
        "wrong-condition-needs-session": [('if (timing.equals("condition")) return', 'if (timing.equals("condition") && presence.equals("session")) return')],
        "wrong-event-always-monitor": [('return presence.equals("away") ? new Choice("routine"', 'return false ? new Choice("routine"')],
        "wrong-expiry-inclusive": [('number(s, "lasts_days") > LOOP_EXPIRY_DAYS', 'number(s, "lasts_days") >= LOOP_EXPIRY_DAYS')],
        "wrong-desktop-without-local-files": [('return flag(s, "local_files") ? new Choice("desktop-task"', 'return true ? new Choice("desktop-task"')],
        "wrong-knowledge-beats-personal": [('        if (choice == null) choice = personalChoice(text(situation, "personal", "none"));\n        if (choice == null) choice = knowledgeChoice(knowledge, flag(situation, "path_scoped"));\n',
                                           '        if (choice == null) choice = knowledgeChoice(knowledge, flag(situation, "path_scoped"));\n        if (choice == null) choice = personalChoice(text(situation, "personal", "none"));\n')],
        "wrong-personal-beats-timing": [('        if (choice == null) choice = rhythm(situation);\n        if (choice == null) choice = personalChoice(text(situation, "personal", "none"));\n',
                                        '        if (choice == null) choice = personalChoice(text(situation, "personal", "none"));\n        if (choice == null) choice = rhythm(situation);\n')],
    }),
    "kotlin": ("ExtensionChoice.kt", {
        "wrong-guarantee-yields-to-timing": [('if (flag(s, "guarantee")) return', 'if (flag(s, "guarantee") && text(s, "timing", "none") == "none") return')],
        "wrong-guarantee-yields-to-scope": [('if (flag(s, "guarantee")) return', 'if (flag(s, "guarantee") && !flag(s, "path_scoped")) return')],
        "wrong-server-yields-to-timing": [('if (flag(s, "external_system")) return', 'if (flag(s, "external_system") && text(s, "timing", "none") == "none") return')],
        "wrong-noisy-yields-to-pipeline": [('if (flag(s, "noisy")) return', 'if (flag(s, "noisy") && text(s, "presence", "session") == "session") return')],
        "wrong-scope-without-convention": [('"procedure" -> Choice("skill", "repeatable-procedure")\n    else -> null', '"procedure" -> Choice("skill", "repeatable-procedure")\n    else -> if (pathScoped) Choice("path-rule", "scoped-convention") else null')],
        "wrong-reference-follows-scope": [('"reference" -> Choice("skill", "on-demand-reference")', '"reference" -> if (pathScoped) null else Choice("skill", "on-demand-reference")')],
        "wrong-hook-not-carried": [('listOf("skill", "hook", "subagent", "mcp")', 'listOf("skill", "subagent", "mcp")')],
        "wrong-path-rule-carried": [('listOf("skill", "hook", "subagent", "mcp")', 'listOf("skill", "hook", "subagent", "mcp", "path-rule")')],
        "wrong-server-beats-builtin": [('if (flag(s, "builtin_covers")) return', 'if (flag(s, "builtin_covers") && !flag(s, "remote_server")) return')],
        "wrong-server-without-remote": [('flag(s, "external_system") && flag(s, "remote_server")', 'flag(s, "external_system") || flag(s, "remote_server")')],
        "wrong-no-validation": [("require(knowledge in KNOWLEDGE) {", "require(true) {")],
        "wrong-no-timing-validation": [('require(text(situation, "timing", "none") in TIMINGS) {', "require(true) {")],
        "wrong-away-sees-local-files": [(' && !(presence == "away" && localFiles)', "")],
        "wrong-pipeline-needs-no-timing": [('if (presence == "pipeline") return', 'if (presence == "pipeline" && timing == "none") return')],
        "wrong-condition-needs-session": [('if (timing == "condition") return', 'if (timing == "condition" && presence == "session") return')],
        "wrong-event-always-monitor": [('if (presence == "away") Choice("routine", "runs-unattended") else', 'if (false) Choice("routine", "runs-unattended") else')],
        "wrong-expiry-inclusive": [('number(s, "lasts_days") > LOOP_EXPIRY_DAYS', 'number(s, "lasts_days") >= LOOP_EXPIRY_DAYS')],
        "wrong-desktop-without-local-files": [('return if (flag(s, "local_files")) Choice("desktop-task"', 'return if (true) Choice("desktop-task"')],
        "wrong-knowledge-beats-personal": [('        ?: personalChoice(text(situation, "personal", "none"))\n        ?: knowledgeChoice(knowledge, flag(situation, "path_scoped"))\n',
                                           '        ?: knowledgeChoice(knowledge, flag(situation, "path_scoped"))\n        ?: personalChoice(text(situation, "personal", "none"))\n')],
        "wrong-personal-beats-timing": [('        ?: rhythm(situation)\n        ?: personalChoice(text(situation, "personal", "none"))\n',
                                        '        ?: personalChoice(text(situation, "personal", "none"))\n        ?: rhythm(situation)\n')],
    }),
}
