# Planted wrong solutions of module 30-vision-and-documents: exact replacements against the practice's reference (see tools/make_plants.py).
# Runs with PLANTS, X and both() in scope; names defined here are local to this file.

PLANTS[f"{X}/30-vision-and-documents/unit-01/practice-1"] = {
    "python": ("vision.py", {
        "wrong-edge-only-resize": [(" and visual_tokens(w, h) <= max_tokens", "")],
        "wrong-text-first": [('content.append({"type": "text", "text": question})', 'content.insert(0, {"type": "text", "text": question})')],
        "wrong-no-labels": [("if image_count > 1:", "if False:")],
        "wrong-padded-coordinates": [("return (x / resized_w * width, y / resized_h * height)", "return (x / resized_w * width, y / (math.ceil(resized_h / 28) * 28) * height)")],
        "wrong-same-limit-all-models": [("if len(images) > _max_count(context):", "if len(images) > 600:")],
        "wrong-many-image-rule": [('if many and max(it["width"], it["height"]) > 2000:', "if False:")],
        "wrong-exact-silent": [('            if exact:\n                raise RequestError(f"items[{i}].dimensions", f"would be resized to {seen[0]}x{seen[1]}")\n', "")],
        "wrong-pdf-pages-ignored": [('if sum(it["pages"] for _, it in pdfs) > _max_count(context):', "if False:")],
        "wrong-pdfs-after-images": [("for _, it in sorted(images + pdfs, key=lambda p: p[0]):", "for _, it in images + pdfs:")],
        "wrong-cloud-url-allowed": [('if cloud and it["source"] != "base64":', "if False:")],
        "wrong-cloud-image-size": [("    return (5 if cloud else 10) * MIB", "    return 10 * MIB")],
        "wrong-no-clamp": [("    x, y = min(max(x, 0), resized_w), min(max(y, 0), resized_h)\n", "")],
    }),
    "typescript": ("vision.ts", {
        "wrong-edge-only-resize": [(" && visualTokens(w, h) <= maxTokens", "")],
        "wrong-text-first": [('content.push({ type: "text", text: question });', 'content.unshift({ type: "text", text: question });')],
        "wrong-no-labels": [("if (imageCount > 1) blocks.push", "if (false) blocks.push")],
        "wrong-padded-coordinates": [("return [(cx / resizedW) * width, (cy / resizedH) * height];", "return [(cx / resizedW) * width, (cy / (Math.ceil(resizedH / 28) * 28)) * height];")],
        "wrong-same-limit-all-models": [("if (images.length > limit)", "if (images.length > 600)")],
        "wrong-many-image-rule": [("if (many && Math.max(w, h) > 2000)", "if (false && Math.max(w, h) > 2000)")],
        "wrong-exact-silent": [("      if (exact) throw new RequestError(`items[${i}].dimensions`, `would be resized to ${seen[0]}x${seen[1]}`);\n", "")],
        "wrong-pdf-pages-ignored": [("if (pdfs.reduce((n, it) => n + (it.pages as number), 0) > limit)", "if (false)")],
        "wrong-pdfs-after-images": [('for (const it of items) {\n    if (it.kind === "image") {', 'for (const it of [...items.filter((x) => x.kind === "image"), ...items.filter((x) => x.kind !== "image")]) {\n    if (it.kind === "image") {')],
        "wrong-cloud-url-allowed": [('if (cloud && it.source !== "base64") throw', 'if (false && it.source !== "base64") throw')],
        "wrong-cloud-image-size": [("return (cloud ? 5 : 10) * MIB;", "return 10 * MIB;")],
        "wrong-no-clamp": [("const cx = Math.min(Math.max(x, 0), resizedW);", "const cx = x;"), ("const cy = Math.min(Math.max(y, 0), resizedH);", "const cy = y;")],
    }),
    "java": ("Vision.java", {
        "wrong-edge-only-resize": [(" && visualTokens(w, h) <= maxTokens", "")],
        "wrong-text-first": [('content.add(map("type", "text", "text", question));', 'content.add(0, map("type", "text", "text", question));')],
        "wrong-no-labels": [("if (imageCount > 1) blocks.add", "if (imageCount > 1000) blocks.add")],
        "wrong-padded-coordinates": [("return new double[] {cx / r[0] * width, cy / r[1] * height};", "return new double[] {cx / r[0] * width, cy / (Math.ceilDiv(r[1], 28) * 28) * height};")],
        "wrong-same-limit-all-models": [("if (images > limit)", "if (images > 600)")],
        "wrong-many-image-rule": [("if (many && Math.max(w, h) > 2000)", "if (false && Math.max(w, h) > 2000)")],
        "wrong-exact-silent": [('                if (exact) throw new RequestError("items[" + i + "].dimensions", "would be resized to " + seen[0] + "x" + seen[1]);\n', "")],
        "wrong-pdf-pages-ignored": [("if (pages > limit)", "if (false)")],
        "wrong-pdfs-after-images": [('for (Map<String, Object> it : items) {\n            if (it.get("kind").equals("image")) {\n                n++;', 'for (Map<String, Object> it : items.stream().sorted(java.util.Comparator.comparing(x -> !x.get("kind").equals("image"))).toList()) {\n            if (it.get("kind").equals("image")) {\n                n++;')],
        "wrong-cloud-url-allowed": [('if (cloud && !it.get("source").equals("base64")) throw', 'if (false && !it.get("source").equals("base64")) throw')],
        "wrong-cloud-image-size": [("return (cloud ? 5 : 10) * MIB;", "return 10 * MIB;")],
        "wrong-no-clamp": [("double cx = Math.min(Math.max(x, 0), r[0]);", "double cx = x;"), ("double cy = Math.min(Math.max(y, 0), r[1]);", "double cy = y;")],
    }),
    "kotlin": ("Vision.kt", {
        "wrong-edge-only-resize": [(" && visualTokens(w, h) <= maxTokens", "")],
        "wrong-text-first": [('content.add(mapOf("type" to "text", "text" to question))', 'content.add(0, mapOf("type" to "text", "text" to question))')],
        "wrong-no-labels": [("if (imageCount > 1) blocks.add(", "if (imageCount > 1000) blocks.add(")],
        "wrong-padded-coordinates": [("return Pair(cx / rw * width, cy / rh * height)", "return Pair(cx / rw * width, cy / (ceil(rh / 28.0).toInt() * 28) * height)")],
        "wrong-same-limit-all-models": [("if (images > limit)", "if (images > 600)")],
        "wrong-many-image-rule": [("if (many && max(w, h) > 2000)", "if (false && max(w, h) > 2000)")],
        "wrong-exact-silent": [('            if (exact) throw RequestError("items[$i].dimensions", "would be resized to ${seen.first}x${seen.second}")\n', "")],
        "wrong-pdf-pages-ignored": [("if (pages > limit)", "if (false)")],
        "wrong-pdfs-after-images": [('for (it in items) {\n        if (it["kind"] == "image") {', 'for (it in items.sortedBy { x -> x["kind"] != "image" }) {\n        if (it["kind"] == "image") {')],
        "wrong-cloud-url-allowed": [('if (cloud && it["source"] != "base64") throw', 'if (false && it["source"] != "base64") throw')],
        "wrong-cloud-image-size": [("= (if (cloud) 5 else 10) * MIB", "= 10 * MIB")],
        "wrong-no-clamp": [("val cx = min(max(x, 0.0), rw.toDouble())", "val cx = x"), ("val cy = min(max(y, 0.0), rh.toDouble())", "val cy = y")],
    }),
}
