# Planted wrong solutions of module 31-computer-use: exact replacements against the practice's reference (see tools/make_plants.py).
# Runs with PLANTS, X and both() in scope; names defined here are local to this file.

PLANTS[f"{X}/31-computer-use/unit-01/practice-1"] = {
    "python": ("computer.py", {
        "wrong-scale-no-edge-cap": [("min(1.0, 1568 / max(width, height), math.sqrt(1_150_000 / (width * height)))", "min(1.0, math.sqrt(1_150_000 / (width * height)))")],
        "wrong-no-clamp": [('return (min(max(round(x / scale), 0), screen["width"] - 1), min(max(round(y / scale), 0), screen["height"] - 1))', "return (round(x / scale), round(y / scale))")],
        "wrong-no-confirm": [('if not element or element.get("risk", "none") == "none": return None', "if True: return None")],
        "wrong-continue-after-failure": [("                        failed = True\n", "")],
        "wrong-key-repeat-unbounded": [("1 <= repeat <= 100", "1 <= repeat")],
        "wrong-wait-unbounded": [("not 0 <= duration <= 300", "not 0 <= duration")],
        "wrong-scroll-zero": [('args.get("scroll_amount") >= 1', 'args.get("scroll_amount") >= 0')],
        "wrong-extra-turn": [("for turn in range(1, max_turns + 1):", "for turn in range(1, max_turns + 2):")],
        "wrong-pause-ends": [('if stop == "pause_turn": return None', 'if stop == "pause_turn": return "done"')],
        "wrong-prune-oldest-kept": [("images[:-keep] if keep > 0 else images", "images[keep:] if keep > 0 else images")],
        "wrong-prune-keep-zero": [("images[:-keep] if keep > 0 else images", "images[:-keep]")],
        "wrong-zoom-full-size": [("render(screen, x1 - x0, y1 - y0)", "render(screen, *shot)")],
        "wrong-screenshot-full-size": [("render(screen, *shot)", 'render(screen, screen["width"], screen["height"])')],
        "wrong-result-per-message": [('            messages.append({"role": "user", "content": results})\n', '            for r in results:\n                messages.append({"role": "user", "content": [r]})\n')],
    }),
    "typescript": ("computer.ts", {
        "wrong-scale-no-edge-cap": [("Math.min(1.0, 1568 / Math.max(width, height), Math.sqrt(1_150_000 / (width * height)))", "Math.min(1.0, Math.sqrt(1_150_000 / (width * height)))")],
        "wrong-no-clamp": [("return [Math.min(Math.max(roundHalfEven(x / scale), 0), screen.width - 1), Math.min(Math.max(roundHalfEven(y / scale), 0), screen.height - 1)];", "return [roundHalfEven(x / scale), roundHalfEven(y / scale)];")],
        "wrong-no-confirm": [('if (!element || (element.risk ?? "none") === "none") return null;', "if (true) return null;")],
        "wrong-continue-after-failure": [("            failed = true;\n", "")],
        "wrong-key-repeat-unbounded": [("repeat >= 1 && repeat <= 100", "repeat >= 1")],
        "wrong-wait-unbounded": [(" || d > 300", "")],
        "wrong-scroll-zero": [("args.scroll_amount >= 1;", "args.scroll_amount >= 0;")],
        "wrong-extra-turn": [("turn <= maxTurns; turn++", "turn <= maxTurns + 1; turn++")],
        "wrong-pause-ends": [('if (stop === "pause_turn") return null;', 'if (stop === "pause_turn") return "done";')],
        "wrong-prune-oldest-kept": [("keep > 0 ? images.slice(0, Math.max(images.length - keep, 0)) : images", "keep > 0 ? images.slice(keep) : images")],
        "wrong-prune-keep-zero": [("keep > 0 ? images.slice(0, Math.max(images.length - keep, 0)) : images", "images.slice(0, -keep)")],
        "wrong-zoom-full-size": [("render(screen, x1 - x0, y1 - y0)", "render(screen, shot[0], shot[1])")],
        "wrong-screenshot-full-size": [("data: render(screen, shot[0], shot[1])", "data: render(screen, screen.width, screen.height)")],
        "wrong-result-per-message": [('messages.push({ role: "user", content: results });', 'for (const r of results) messages.push({ role: "user", content: [r] });')],
    }),
    "java": ("Computer.java", {
        "wrong-scale-no-edge-cap": [("Math.min(1.0, Math.min(1568.0 / Math.max(width, height), Math.sqrt(1_150_000.0 / ((double) width * height))))", "Math.min(1.0, Math.sqrt(1_150_000.0 / ((double) width * height)))")],
        "wrong-no-clamp": [('int sx = (int) Math.min(Math.max(Math.rint(x / scale), 0), num(screen.get("width")) - 1);', "int sx = (int) Math.rint(x / scale);"),
                           ('int sy = (int) Math.min(Math.max(Math.rint(y / scale), 0), num(screen.get("height")) - 1);', "int sy = (int) Math.rint(y / scale);")],
        "wrong-no-confirm": [('if (element == null || "none".equals(element.getOrDefault("risk", "none"))) return null;', "if (true) return null;")],
        "wrong-continue-after-failure": [("                            failed = true;\n", "")],
        "wrong-key-repeat-unbounded": [("num(repeat) >= 1 && num(repeat) <= 100", "num(repeat) >= 1")],
        "wrong-wait-unbounded": [(" || n.doubleValue() > 300", "")],
        "wrong-scroll-zero": [('num(args.get("scroll_amount")) >= 1', 'num(args.get("scroll_amount")) >= 0')],
        "wrong-extra-turn": [("turn <= maxTurns; turn++", "turn <= maxTurns + 1; turn++")],
        "wrong-pause-ends": [('if ("pause_turn".equals(stop)) return null;', 'if ("pause_turn".equals(stop)) return "done";')],
        "wrong-prune-oldest-kept": [("for (int k = 0; k < upTo; k++)", "for (int k = keep; k < images.size(); k++)")],
        "wrong-prune-keep-zero": [("return keep > 0 ? Math.max(total - keep, 0) : total;", "return keep > 0 ? Math.max(total - keep, 0) : 0;")],
        "wrong-zoom-full-size": [("render(screen, b[0] - a[0], b[1] - a[1])", "render(screen, shot[0], shot[1])")],
        "wrong-screenshot-full-size": [("return image(render(screen, shot[0], shot[1]));", 'return image(render(screen, num(screen.get("width")), num(screen.get("height"))));')],
        "wrong-result-per-message": [('messages.add(map("role", "user", "content", results));', 'for (Object r : results) messages.add(map("role", "user", "content", List.of(r)));')],
    }),
    "kotlin": ("Computer.kt", {
        "wrong-scale-no-edge-cap": [("min(1.0, min(1568.0 / max(width, height), sqrt(1_150_000.0 / (width.toDouble() * height))))", "min(1.0, sqrt(1_150_000.0 / (width.toDouble() * height)))")],
        "wrong-no-clamp": [('Pair(min(max(Math.rint(x / scale), 0.0), (num(screen["width"]) - 1).toDouble()).toInt(), min(max(Math.rint(y / scale), 0.0), (num(screen["height"]) - 1).toDouble()).toInt())', "Pair(Math.rint(x / scale).toInt(), Math.rint(y / scale).toInt())")],
        "wrong-no-confirm": [('if (element == null || (element["risk"] ?: "none") == "none") return null', "if (true) return null")],
        "wrong-continue-after-failure": [("                        failed = true\n", "")],
        "wrong-key-repeat-unbounded": [("num(repeat) >= 1 && num(repeat) <= 100", "num(repeat) >= 1")],
        "wrong-wait-unbounded": [(" || d.toDouble() > 300", "")],
        "wrong-scroll-zero": [('num(args["scroll_amount"]) >= 1', 'num(args["scroll_amount"]) >= 0')],
        "wrong-extra-turn": [("for (turn in 1..maxTurns) {", "for (turn in 1..maxTurns + 1) {")],
        "wrong-pause-ends": [('if (stop == "pause_turn") return null', 'if (stop == "pause_turn") return "done"')],
        "wrong-prune-oldest-kept": [("images.take(upTo)", "images.drop(keep)")],
        "wrong-prune-keep-zero": [("if (keep > 0) max(total - keep, 0) else total", "if (keep > 0) max(total - keep, 0) else 0")],
        "wrong-zoom-full-size": [("image(render(screen, b.first - a.first, b.second - a.second))", "image(render(screen, shot.first, shot.second))")],
        "wrong-screenshot-full-size": [("return image(render(screen, shot.first, shot.second))", 'return image(render(screen, num(screen["width"]), num(screen["height"])))')],
        "wrong-result-per-message": [('messages.add(mapOf("role" to "user", "content" to results))', 'for (r in results) messages.add(mapOf("role" to "user", "content" to listOf(r)))')],
    }),
}
