# Planted wrong solutions of module 33-mcp-advanced: exact replacements against the practice's reference (see tools/make_plants.py).
# Runs with PLANTS, X and both() in scope; names defined here are local to this file.

PLANTS[f"{X}/33-mcp-advanced/unit-01/practice-1"] = {
    "python": ("mrtr.py", {
        "wrong-no-expiry": [('    if now > state.get("exp", 0):\n        return _error(-32602, "Expired requestState")\n', "")],
        "wrong-any-principal": [('if state.get("sub") != principal or state.get("tool") != name or', 'if state.get("tool") != name or')],
        "wrong-no-digest": [(' or state.get("digest") != args_digest(arguments)', "")],
        "wrong-bad-state-restarts": [('    token = request.get("requestState")\n', '    token = request.get("requestState")\n    if token is not None and read_state(secret, token) is None:\n        token = None\n')],
        "wrong-elicit-without-capability": [('    return elicitation is not None and (elicitation == {} or "form" in elicitation)', "    return True")],
        "wrong-list-uncacheable": [('"ttlMs": 300000', '"ttlMs": 0')],
        "wrong-version-ignored": [("    if version != VERSION:", "    if version is None:")],
        "wrong-answer-alone-skips": [('answers = request.get("inputResponses") if token is not None else None', 'answers = request.get("inputResponses")')],
        "wrong-decline-continues": [('return answer["action"] == "accept" and (answer.get("content") or {}).get("confirm") is True', 'return (answer.get("content") or {}).get("confirm") is True')],
        "wrong-error-on-missing-input": [('return _ask(_confirm_request(service), "confirm", secret, name, arguments, principal, now)', 'return _ask(_confirm_request(service), "confirm", secret, name, arguments, principal, now) if token is None else _error(-32602, "Missing inputResponses")')],
    }),
    "typescript": ("mrtr.ts", {
        "wrong-no-expiry": [('  if (now > (state.exp ?? 0)) return error(-32602, "Expired requestState");\n', "")],
        "wrong-any-principal": [("if (state.sub !== principal || state.tool !== name ||", "if (state.tool !== name ||")],
        "wrong-no-digest": [(" || state.digest !== argsDigest(args)", "")],
        "wrong-bad-state-restarts": [("const token = request.requestState;", "const token = request.requestState !== undefined && readState(secret, request.requestState) === null ? undefined : request.requestState;")],
        "wrong-elicit-without-capability": [('  return elicitation !== undefined && elicitation !== null && (Object.keys(elicitation).length === 0 || "form" in elicitation);', "  return true;")],
        "wrong-list-uncacheable": [("ttlMs: 300000", "ttlMs: 0")],
        "wrong-version-ignored": [("if (request._meta?.[META_VERSION] !== VERSION)", "if (request._meta?.[META_VERSION] === undefined)")],
        "wrong-answer-alone-skips": [("const given = token !== undefined && token !== null ? request.inputResponses : undefined;", "const given = request.inputResponses;")],
        "wrong-decline-continues": [('answer.action === "accept" && ', "")],
        "wrong-error-on-missing-input": [('return ask(confirmRequest(service), "confirm", secret, name, args, principal, now);', 'return token === undefined || token === null ? ask(confirmRequest(service), "confirm", secret, name, args, principal, now) : error(-32602, "Missing inputResponses");')],
    }),
    "java": ("Mrtr.java", {
        "wrong-no-expiry": [('        if (now > (state.get("exp") instanceof Number e ? e.longValue() : 0)) return error(-32602, "Expired requestState", null);\n', "")],
        "wrong-any-principal": [('if (!principal.equals(state.get("sub")) || !name.equals(state.get("tool"))', 'if (!name.equals(state.get("tool"))')],
        "wrong-no-digest": [(' || !argsDigest(arguments).equals(state.get("digest"))', "")],
        "wrong-bad-state-restarts": [('Object token = request.get("requestState");', 'Object token = request.get("requestState") != null && readState(secret, String.valueOf(request.get("requestState"))) == null ? null : request.get("requestState");')],
        "wrong-elicit-without-capability": [('return elicitation instanceof Map<?, ?> m && (m.isEmpty() || m.containsKey("form"));', "return true;")],
        "wrong-list-uncacheable": [('"ttlMs", 300000', '"ttlMs", 0')],
        "wrong-version-ignored": [("if (!VERSION.equals(meta(request).get(META_VERSION)))", "if (meta(request).get(META_VERSION) == null)")],
        "wrong-answer-alone-skips": [('Map<String, Object> answers = token != null && request.get("inputResponses")', 'Map<String, Object> answers = request.get("inputResponses")')],
        "wrong-decline-continues": [('"accept".equals(answer.get("action")) && ', "")],
        "wrong-error-on-missing-input": [('return ask(confirmRequest(s), "confirm", secret, "deploy", arguments, principal, now);', 'return token == null ? ask(confirmRequest(s), "confirm", secret, "deploy", arguments, principal, now) : error(-32602, "Missing inputResponses", null);')],
    }),
    "kotlin": ("Mrtr.kt", {
        "wrong-no-expiry": [('    if (now > ((state["exp"] as? Number)?.toLong() ?: 0L)) return error(-32602, "Expired requestState")\n', "")],
        "wrong-any-principal": [('if (state["sub"] != principal || state["tool"] != name ||', 'if (state["tool"] != name ||')],
        "wrong-no-digest": [(' || state["digest"] != argsDigest(arguments)', "")],
        "wrong-bad-state-restarts": [('val token = request["requestState"]', 'val token = request["requestState"]?.takeIf { readState(secret, it.toString()) != null }')],
        "wrong-elicit-without-capability": [('return elicitation != null && (elicitation.isEmpty() || elicitation.containsKey("form"))', "return true")],
        "wrong-list-uncacheable": [('"ttlMs" to 300000', '"ttlMs" to 0')],
        "wrong-version-ignored": [("if (meta(request)[META_VERSION] != VERSION) error(", "if (meta(request)[META_VERSION] == null) error(")],
        "wrong-answer-alone-skips": [('val answers = if (token != null) (request["inputResponses"] as? Map<String, Any?>) ?: emptyMap() else emptyMap()', 'val answers = (request["inputResponses"] as? Map<String, Any?>) ?: emptyMap()')],
        "wrong-decline-continues": [('answer["action"] == "accept" && ', "")],
        "wrong-error-on-missing-input": [('return ask(confirmRequest(service), "confirm", secret, "deploy", arguments, principal, now)', 'return if (token == null) ask(confirmRequest(service), "confirm", secret, "deploy", arguments, principal, now) else error(-32602, "Missing inputResponses")')],
    }),
}
