# Planted wrong solutions of module 41-security-and-safety: exact replacements against the practice's reference (see tools/make_plants.py).
# Runs with PLANTS, X and both() in scope; names defined here are local to this file.

PLANTS[f"{X}/41-security-and-safety/unit-01/practice-1"] = {
    "python": ("gate.py", {
        "wrong-concatenate": [('payload = json.dumps({"source": source, "trust": "untrusted", "content": content}, separators=(",", ":"))', 'payload = f"source={source}\\ntrust=untrusted\\n{content}"')],
        "wrong-screen-case-sensitive": [(r'\b(instructions?|prompts?|rules)\b", re.I | re.S),', r'\b(instructions?|prompts?|rules)\b", re.S),')],
        "wrong-screen-leaks": [("withheld: possible prompt injection ({', '.join(signals)})\"", "withheld: possible prompt injection ({', '.join(signals)}): {content[:40]}\"")],
        "wrong-prefix-sibling": [('return path == self.root or path.startswith(self.root + "/")', "return path.startswith(self.root)")],
        "wrong-env-variants": [('return (base == ".env" or (base.startswith(".env.") and base != ".env.example") or "secrets" in parts[:-1]', 'return (base == ".env" or "secrets" in parts[:-1]')],
        "wrong-chain-allowed": [("if any(t in command for t in SHELL_TRICKS):", "if False:")],
        "wrong-host-suffix": [('if not any(host == h or host.endswith("." + h) for h in self.allowed_hosts):', "if not any(host.endswith(h) for h in self.allowed_hosts):")],
        "wrong-email-tainted-allowed": [('        if self._tainted:\n            return _result("deny", "a person must send it")\n', "")],
        "wrong-luhn-skip": [('return 13 <= len(digits) <= 19 and _luhn(digits)', 'return 13 <= len(digits) <= 19')],
        "wrong-audit-raw": [("clean = {k: (redact(v) if isinstance(v, str) else v) for k, v in args.items()}", "clean = dict(args)")],
        "wrong-hook-exit2": [('return {"exit_code": 0, "stdout": json.dumps(out, separators=(",", ":")), "stderr": ""}', 'return {"exit_code": 2, "stdout": json.dumps(out, separators=(",", ":")), "stderr": ""}')],
        "wrong-alert-asks": [('if record["decision"] == "deny":', 'if record["decision"] != "allow":')],
    }),
    "typescript": ("gate.ts", {
        "wrong-concatenate": [('JSON.stringify({ source, trust: "untrusted", content })', '`source=${source}\\ntrust=untrusted\\n${content}`')],
        "wrong-screen-case-sensitive": [(r'\b(instructions?|prompts?|rules)\b/i],', r'\b(instructions?|prompts?|rules)\b/],')],
        "wrong-screen-leaks": [('possible prompt injection (${signals.join(", ")})`', 'possible prompt injection (${signals.join(", ")}): ${content.slice(0, 40)}`')],
        "wrong-prefix-sibling": [('return path === this.root || path.startsWith(this.root + "/");', "return path.startsWith(this.root);")],
        "wrong-env-variants": [('return base === ".env" || (base.startsWith(".env.") && base !== ".env.example") || parts.slice(0, -1).includes("secrets")', 'return base === ".env" || parts.slice(0, -1).includes("secrets")')],
        "wrong-chain-allowed": [('if (SHELL_TRICKS.some((t) => command.includes(t))) return result("deny", "chaining or redirection");', "")],
        "wrong-host-suffix": [('if (!this.allowedHosts.some((h) => host === h || host.endsWith("." + h))) return result("deny", "host not allowed");', 'if (!this.allowedHosts.some((h) => host.endsWith(h))) return result("deny", "host not allowed");')],
        "wrong-email-tainted-allowed": [('    if (this.isTainted) return result("deny", "a person must send it");\n', "")],
        "wrong-luhn-skip": [('return digits.length >= 13 && digits.length <= 19 && luhn(digits);', 'return digits.length >= 13 && digits.length <= 19;')],
        "wrong-audit-raw": [('clean[k] = typeof v === "string" ? redact(v) : v;', "clean[k] = v;")],
        "wrong-hook-exit2": [('return { exit_code: 0, stdout: JSON.stringify(out), stderr: "" };', 'return { exit_code: 2, stdout: JSON.stringify(out), stderr: "" };')],
        "wrong-alert-asks": [('if (r.decision === "deny") {', 'if (r.decision !== "allow") {')],
    }),
    "java": ("Gate.java", {
        "wrong-concatenate": [('"content", Json.stringify(map("source", source, "trust", "untrusted", "content", content)));', r'"content", "source=" + source + "\ntrust=untrusted\n" + content);')],
        "wrong-screen-case-sensitive": [(r'\\b(instructions?|prompts?|rules)\\b", flags));', r'\\b(instructions?|prompts?|rules)\\b", Pattern.DOTALL));')],
        "wrong-screen-leaks": [('+ String.join(", ", signals) + ")");', '+ String.join(", ", signals) + "): " + content.substring(0, Math.min(40, content.length())));')],
        "wrong-prefix-sibling": [('return path.equals(root) || path.startsWith(root + "/");', "return path.startsWith(root);")],
        "wrong-env-variants": [('return base.equals(".env") || (base.startsWith(".env.") && !base.equals(".env.example")) || parts.subList', 'return base.equals(".env") || parts.subList')],
        "wrong-chain-allowed": [('for (String t : SHELL_TRICKS) if (command.contains(t)) return result("deny", "chaining or redirection");', "")],
        "wrong-host-suffix": [('for (String h : allowedHosts) if (host.equals(h) || host.endsWith("." + h)) listed = true;', "for (String h : allowedHosts) if (host.endsWith(h)) listed = true;")],
        "wrong-email-tainted-allowed": [('        if (tainted) return result("deny", "a person must send it");\n', "")],
        "wrong-luhn-skip": [('return digits.length() >= 13 && digits.length() <= 19 && luhn(digits);', 'return digits.length() >= 13 && digits.length() <= 19;')],
        "wrong-audit-raw": [("clean.put(e.getKey(), e.getValue() instanceof String s ? redact(s) : e.getValue());", "clean.put(e.getKey(), e.getValue());")],
        "wrong-hook-exit2": [('return map("exit_code", 0, "stdout", Json.stringify(out), "stderr", "");', 'return map("exit_code", 2, "stdout", Json.stringify(out), "stderr", "");')],
        "wrong-alert-asks": [('if (r.get("decision").equals("deny")) {', 'if (!r.get("decision").equals("allow")) {')],
    }),
    "kotlin": ("Gate.kt", {
        "wrong-concatenate": [('"content" to Json.stringify(linkedMapOf("source" to source, "trust" to "untrusted", "content" to content)))', r'"content" to ("source=" + source + "\ntrust=untrusted\n" + content))')],
        "wrong-screen-case-sensitive": [(r'\\b(instructions?|prompts?|rules)\\b", flags),', r'\\b(instructions?|prompts?|rules)\\b", setOf(RegexOption.DOT_MATCHES_ALL)),')],
        "wrong-screen-leaks": [('(${found.joinToString(", ")})")', '(${found.joinToString(", ")}): ${content.take(40)}")')],
        "wrong-prefix-sibling": [('private fun inside(path: String) = path == root || path.startsWith("$root/")', "private fun inside(path: String) = path.startsWith(root)")],
        "wrong-env-variants": [('return base == ".env" || (base.startsWith(".env.") && base != ".env.example") || parts.dropLast(1)', 'return base == ".env" || parts.dropLast(1)')],
        "wrong-chain-allowed": [('if (shellTricks.any { it in command }) return result("deny", "chaining or redirection")', "")],
        "wrong-host-suffix": [('if (allowedHosts.none { host == it || host.endsWith(".$it") }) return result("deny", "host not allowed")', 'if (allowedHosts.none { host.endsWith(it) }) return result("deny", "host not allowed")')],
        "wrong-email-tainted-allowed": [('        if (tainted) return result("deny", "a person must send it")\n', "")],
        "wrong-luhn-skip": [('return digits.length in 13..19 && luhn(digits)', 'return digits.length in 13..19')],
        "wrong-audit-raw": [("val clean = args.mapValues { (_, v) -> if (v is String) redact(v) else v }", "val clean = args")],
        "wrong-hook-exit2": [('return linkedMapOf("exit_code" to 0, "stdout" to Json.stringify(out), "stderr" to "")', 'return linkedMapOf("exit_code" to 2, "stdout" to Json.stringify(out), "stderr" to "")')],
        "wrong-alert-asks": [('if (r["decision"] == "deny") {', 'if (r["decision"] != "allow") {')],
    }),
}
