# Planted wrong solutions of module 43-debugging-claude-applications: exact replacements against the practice's reference (see tools/make_plants.py).
# Runs with PLANTS, X and both() in scope; names defined here are local to this file.

PLANTS[f"{X}/43-debugging-claude-applications/unit-01/practice-1"] = {
    "python": ("diagnose.py", {
        "wrong-retry-400": [('400: ("invalid_request", "integration", "fix_request"),', '400: ("invalid_request", "integration", "retry_backoff"),')],
        "wrong-413-service": [('413: ("request_too_large", "integration", "shrink_request"),', '413: ("request_too_large", "service", "shrink_request"),')],
        "wrong-429-always-retry": [('if event.get("error_code") == "enforced_spend_limit_reached":', "if False:")],
        "wrong-spend-400-ignored": [('if status == 400 and "spend limit" in event.get("message", "").lower():', "if False:")],
        "wrong-maxtokens-model": [('"max_tokens": ("truncated", "integration", "raise_max_tokens"),', '"max_tokens": ("truncated", "model", "raise_max_tokens"),')],
        "wrong-refusal-retry": [('"refusal": ("refusal", "model", "fallback_model"),', '"refusal": ("refusal", "model", "retry_backoff"),')],
        "wrong-empty-always-model": [('if "tool_result" in last_blocks and "text" in last_blocks[last_blocks.index("tool_result"):]:', "if False:")],
        "wrong-empty-text-anywhere": [('if "tool_result" in last_blocks and "text" in last_blocks[last_blocks.index("tool_result"):]:', 'if "tool_result" in last_blocks and "text" in last_blocks:')],
        "wrong-parse-always-model": [('if _has_json_object(event.get("text", "")):', "if False:")],
        "wrong-parse-braces-only": [('return isinstance(json.loads(text[start:end + 1]), dict)', "return True")],
        "wrong-unknown-tool-integration": [('return ("unknown_tool", "model", "return_error_result")', 'return ("unknown_tool", "integration", "return_error_result")')],
        "wrong-tool-error-flagged": [('if kind == "tool_result" and event.get("exception"):', 'if kind == "tool_result" and (event.get("exception") or event.get("is_error")):')],
        "wrong-last-failure": [("for i, event in enumerate(trace):", "for i, event in reversed(list(enumerate(trace))):")],
        "wrong-recovered-ignored": [("recovered = any(", "recovered = False and any(")],
        "wrong-recovered-empty": [(' and e.get("stop_reason") == "end_turn" and e.get("content")', ' and e.get("stop_reason") == "end_turn"')],
        "wrong-network-integration": [('return ("network", "service", "retry_backoff")', 'return ("network", "integration", "retry_backoff")')],
    }),
    "typescript": ("diagnose.ts", {
        "wrong-retry-400": [('400: ["invalid_request", "integration", "fix_request"],', '400: ["invalid_request", "integration", "retry_backoff"],')],
        "wrong-413-service": [('413: ["request_too_large", "integration", "shrink_request"],', '413: ["request_too_large", "service", "shrink_request"],')],
        "wrong-429-always-retry": [('if (event.error_code === "enforced_spend_limit_reached") return', "if (false) return")],
        "wrong-spend-400-ignored": [('if (status === 400 && String(event.message ?? "").toLowerCase().includes("spend limit")) return', "if (false) return")],
        "wrong-maxtokens-model": [('max_tokens: ["truncated", "integration", "raise_max_tokens"],', 'max_tokens: ["truncated", "model", "raise_max_tokens"],')],
        "wrong-refusal-retry": [('refusal: ["refusal", "model", "fallback_model"],', 'refusal: ["refusal", "model", "retry_backoff"],')],
        "wrong-empty-always-model": [('if (at >= 0 && lastBlocks.slice(at).includes("text")) return', "if (false) return")],
        "wrong-empty-text-anywhere": [('if (at >= 0 && lastBlocks.slice(at).includes("text")) return', 'if (at >= 0 && lastBlocks.includes("text")) return')],
        "wrong-parse-always-model": [('return hasJsonObject(String(event.text ?? "")) ?', "return false ?")],
        "wrong-parse-braces-only": [('    const value = JSON.parse(text.slice(start, end + 1));\n    return typeof value === "object" && value !== null && !Array.isArray(value);', "    return true;")],
        "wrong-unknown-tool-integration": [('["unknown_tool", "model", "return_error_result"]', '["unknown_tool", "integration", "return_error_result"]')],
        "wrong-tool-error-flagged": [('kind === "tool_result" && event.exception)', 'kind === "tool_result" && (event.exception || event.is_error))')],
        "wrong-last-failure": [("for (let i = 0; i < trace.length; i++) {\n    const event = trace[i];", "for (let i = trace.length - 1; i >= 0; i--) {\n    const event = trace[i];")],
        "wrong-recovered-ignored": [("const recovered = trace.slice(i + 1).some(", "const recovered = false && trace.slice(i + 1).some(")],
        "wrong-recovered-empty": [('e.stop_reason === "end_turn" && e.content && e.content.length > 0);', 'e.stop_reason === "end_turn");')],
        "wrong-network-integration": [('if (kind === "network_error") return ["network", "service", "retry_backoff"];', 'if (kind === "network_error") return ["network", "integration", "retry_backoff"];')],
    }),
    "java": ("Diagnose.java", {
        "wrong-retry-400": [('400, new String[] {"invalid_request", "integration", "fix_request"},', '400, new String[] {"invalid_request", "integration", "retry_backoff"},')],
        "wrong-413-service": [('413, new String[] {"request_too_large", "integration", "shrink_request"},', '413, new String[] {"request_too_large", "service", "shrink_request"},')],
        "wrong-429-always-retry": [('if ("enforced_spend_limit_reached".equals(event.get("error_code"))) return', "if (false) return")],
        "wrong-spend-400-ignored": [("if (status == 400 && String.valueOf(", "if (false && String.valueOf(")],
        "wrong-maxtokens-model": [('"max_tokens", new String[] {"truncated", "integration", "raise_max_tokens"},', '"max_tokens", new String[] {"truncated", "model", "raise_max_tokens"},')],
        "wrong-refusal-retry": [('"refusal", new String[] {"refusal", "model", "fallback_model"},', '"refusal", new String[] {"refusal", "model", "retry_backoff"},')],
        "wrong-empty-always-model": [('if (at >= 0 && lastBlocks.subList(at, lastBlocks.size()).contains("text")) return', "if (false) return")],
        "wrong-empty-text-anywhere": [('if (at >= 0 && lastBlocks.subList(at, lastBlocks.size()).contains("text")) return', 'if (at >= 0 && lastBlocks.contains("text")) return')],
        "wrong-parse-always-model": [('return hasJsonObject(String.valueOf(event.getOrDefault("text", ""))) ?', "return false ?")],
        "wrong-parse-braces-only": [("return Json.parse(text.substring(start, end + 1)) instanceof Map<?, ?>;", "return true;")],
        "wrong-unknown-tool-integration": [('new String[] {"unknown_tool", "model", "return_error_result"}', 'new String[] {"unknown_tool", "integration", "return_error_result"}')],
        "wrong-tool-error-flagged": [('return event.get("exception") instanceof String s && !s.isEmpty() ?', 'return (event.get("exception") instanceof String s && !s.isEmpty() || Boolean.TRUE.equals(event.get("is_error"))) ?')],
        "wrong-last-failure": [("for (int i = 0; i < trace.size(); i++) {", "for (int i = trace.size() - 1; i >= 0; i--) {")],
        "wrong-recovered-ignored": [('if ("response".equals(e.get("kind")) &&', 'if (false && "response".equals(e.get("kind")) &&')],
        "wrong-recovered-empty": [('"end_turn".equals(e.get("stop_reason"))\n                        && e.get("content") instanceof List<?> c && !c.isEmpty()) recovered = true;', '"end_turn".equals(e.get("stop_reason"))) recovered = true;')],
        "wrong-network-integration": [('return new String[] {"network", "service", "retry_backoff"};', 'return new String[] {"network", "integration", "retry_backoff"};')],
    }),
    "kotlin": ("Diagnose.kt", {
        "wrong-retry-400": [('400 to listOf("invalid_request", "integration", "fix_request"),', '400 to listOf("invalid_request", "integration", "retry_backoff"),')],
        "wrong-413-service": [('413 to listOf("request_too_large", "integration", "shrink_request"),', '413 to listOf("request_too_large", "service", "shrink_request"),')],
        "wrong-429-always-retry": [('if (event["error_code"] == "enforced_spend_limit_reached") return', "if (false) return")],
        "wrong-spend-400-ignored": [('if (status == 400 && (event["message"]', 'if (false && (event["message"]')],
        "wrong-maxtokens-model": [('"max_tokens" to listOf("truncated", "integration", "raise_max_tokens"),', '"max_tokens" to listOf("truncated", "model", "raise_max_tokens"),')],
        "wrong-refusal-retry": [('"refusal" to listOf("refusal", "model", "fallback_model"),', '"refusal" to listOf("refusal", "model", "retry_backoff"),')],
        "wrong-empty-always-model": [('return if (at >= 0 && "text" in lastBlocks.subList(at, lastBlocks.size)) listOf(', "return if (false) listOf(")],
        "wrong-empty-text-anywhere": [('return if (at >= 0 && "text" in lastBlocks.subList(at, lastBlocks.size)) listOf(', 'return if (at >= 0 && "text" in lastBlocks) listOf(')],
        "wrong-parse-always-model": [('return if (hasJsonObject(event["text"] as? String ?: "")) listOf(', "return if (false) listOf(")],
        "wrong-parse-braces-only": [("return try { Json.parse(text.substring(start, end + 1)) is Map<*, *> } catch", "return try { true } catch")],
        "wrong-unknown-tool-integration": [('listOf("unknown_tool", "model", "return_error_result")', 'listOf("unknown_tool", "integration", "return_error_result")')],
        "wrong-tool-error-flagged": [('"tool_result" -> if (!(event["exception"] as? String).isNullOrEmpty()) return', '"tool_result" -> if (!(event["exception"] as? String).isNullOrEmpty() || event["is_error"] == true) return')],
        "wrong-last-failure": [("for ((i, event) in trace.withIndex()) {", "for ((i, event) in trace.withIndex().reversed()) {")],
        "wrong-recovered-ignored": [("val recovered = trace.drop(i + 1).any {", "val recovered = false && trace.drop(i + 1).any {")],
        "wrong-recovered-empty": [(' && it["stop_reason"] == "end_turn" && !(it["content"] as? List<*>).isNullOrEmpty()', ' && it["stop_reason"] == "end_turn"')],
        "wrong-network-integration": [('"network_error" -> return listOf("network", "service", "retry_backoff")', '"network_error" -> return listOf("network", "integration", "retry_backoff")')],
    }),
}
