# Planted wrong solutions of module 43-debugging-claude-applications: exact replacements against the practice's reference (see tools/make_plants.py).
# Runs with PLANTS, X and both() in scope; names defined here are local to this file.

PLANTS[f"{X}/43-debugging-claude-applications/unit-01/practice-1"] = {
    "python": ("diagnose.py", {
        "wrong-retry-404": [('404: ("not_found", "integration", "fix_request"),', '404: ("not_found", "integration", "retry_backoff"),')],
        "wrong-413-service": [('413: ("request_too_large", "integration", "shrink_request"),', '413: ("request_too_large", "service", "shrink_request"),')],
        "wrong-429-always-retry": [('if event.get("error_code") == "enforced_spend_limit_reached":', "if False:")],
        "wrong-spend-400-ignored": [('if status == 400 and "spend limit" in event.get("message", "").lower():', "if False:")],
        "wrong-maxtokens-model": [('"max_tokens": ("truncated", "integration", "raise_max_tokens"),', '"max_tokens": ("truncated", "model", "raise_max_tokens"),')],
        "wrong-refusal-retry": [('"refusal": ("refusal", "model", "fallback_model"),', '"refusal": ("refusal", "model", "retry_backoff"),')],
        "wrong-empty-always-model": [('if "tool_result" in last_blocks and "text" in last_blocks[last_blocks.index("tool_result"):]:', "if False:")],
        "wrong-empty-text-anywhere": [('if "tool_result" in last_blocks and "text" in last_blocks[last_blocks.index("tool_result"):]:', 'if "tool_result" in last_blocks and "text" in last_blocks:')],
        "wrong-parse-always-model": [('if _has_json_object(event.get("text", "")):', "if False:")],
        "wrong-parse-braces-only": [('return isinstance(json.loads(text[start:end + 1]), dict)', "return True")],
        "wrong-unknown-tool-integration": [('return ("unknown_tool", "model", "return_error_result")', 'return ("unknown_tool", "integration", "return_error_result")')],
        "wrong-tool-error-flagged": [('if kind == "tool_result" and event.get("exception"):', 'if kind == "tool_result" and (event.get("exception") or event.get("is_error")):')],
        "wrong-last-failure": [("    tools, last_blocks = None, []\n", "    tools, last_blocks = None, []\n    last = None\n"),
                               ('            return {"index": i,', '            last = {"index": i,'),
                               ('    return {"index": -1,', '    return last or {"index": -1,')],
        "wrong-recovered-next-only": [("               for e in trace[i + 1:])", '               for e in [x for x in trace[i + 1:] if x.get("kind") == "response"][:1])')],
        "wrong-recovered-empty": [(' and e.get("stop_reason") == "end_turn" and e.get("content")', ' and e.get("stop_reason") == "end_turn"')],
        "wrong-network-integration": [('return ("network", "service", "retry_backoff")', 'return ("network", "integration", "retry_backoff")')],
    }),
    "typescript": ("diagnose.ts", {
        "wrong-retry-404": [('404: ["not_found", "integration", "fix_request"],', '404: ["not_found", "integration", "retry_backoff"],')],
        "wrong-413-service": [('413: ["request_too_large", "integration", "shrink_request"],', '413: ["request_too_large", "service", "shrink_request"],')],
        "wrong-429-always-retry": [('if (event.error_code === "enforced_spend_limit_reached") return', "if (false) return")],
        "wrong-spend-400-ignored": [('if (status === 400 && String(event.message ?? "").toLowerCase().includes("spend limit")) return', "if (false) return")],
        "wrong-maxtokens-model": [('max_tokens: ["truncated", "integration", "raise_max_tokens"],', 'max_tokens: ["truncated", "model", "raise_max_tokens"],')],
        "wrong-refusal-retry": [('refusal: ["refusal", "model", "fallback_model"],', 'refusal: ["refusal", "model", "retry_backoff"],')],
        "wrong-empty-always-model": [('if (at >= 0 && lastBlocks.slice(at).includes("text")) return', "if (false) return")],
        "wrong-empty-text-anywhere": [('if (at >= 0 && lastBlocks.slice(at).includes("text")) return', 'if (at >= 0 && lastBlocks.includes("text")) return')],
        "wrong-parse-always-model": [('return hasJsonObject(String(event.text ?? "")) ?', "return false ?")],
        "wrong-parse-braces-only": [('    const value = JSON.parse(text.slice(start, end + 1));\n    return typeof value === "object" && value !== null && !Array.isArray(value);', "    return true;")],
        "wrong-unknown-tool-integration": [('["unknown_tool", "model", "return_error_result"]', '["unknown_tool", "integration", "return_error_result"]')],
        "wrong-tool-error-flagged": [('kind === "tool_result" && event.exception)', 'kind === "tool_result" && (event.exception || event.is_error))')],
        "wrong-last-failure": [("  let lastBlocks: string[] = [];\n", "  let lastBlocks: string[] = [];\n  let last: Diagnosis | null = null;\n"),
                               ("      return { index: i, type: found[0],", "      last = { index: i, type: found[0],"),
                               ('  return { index: -1, type: "ok",', '  return last ?? { index: -1, type: "ok",')],
        "wrong-recovered-next-only": [("  return trace.slice(i + 1).some(", '  return trace.slice(i + 1).filter((x) => x.kind === "response").slice(0, 1).some(')],
        "wrong-recovered-empty": [('e.stop_reason === "end_turn" && e.content && e.content.length > 0);', 'e.stop_reason === "end_turn");')],
        "wrong-network-integration": [('if (kind === "network_error") return ["network", "service", "retry_backoff"];', 'if (kind === "network_error") return ["network", "integration", "retry_backoff"];')],
    }),
    "java": ("Diagnose.java", {
        "wrong-retry-404": [('404, new String[] {"not_found", "integration", "fix_request"},', '404, new String[] {"not_found", "integration", "retry_backoff"},')],
        "wrong-413-service": [('413, new String[] {"request_too_large", "integration", "shrink_request"},', '413, new String[] {"request_too_large", "service", "shrink_request"},')],
        "wrong-429-always-retry": [('if ("enforced_spend_limit_reached".equals(event.get("error_code"))) return', "if (false) return")],
        "wrong-spend-400-ignored": [("if (status == 400 && String.valueOf(", "if (false && String.valueOf(")],
        "wrong-maxtokens-model": [('"max_tokens", new String[] {"truncated", "integration", "raise_max_tokens"},', '"max_tokens", new String[] {"truncated", "model", "raise_max_tokens"},')],
        "wrong-refusal-retry": [('"refusal", new String[] {"refusal", "model", "fallback_model"},', '"refusal", new String[] {"refusal", "model", "retry_backoff"},')],
        "wrong-empty-always-model": [('if (at >= 0 && lastBlocks.subList(at, lastBlocks.size()).contains("text")) return', "if (false) return")],
        "wrong-empty-text-anywhere": [('if (at >= 0 && lastBlocks.subList(at, lastBlocks.size()).contains("text")) return', 'if (at >= 0 && lastBlocks.contains("text")) return')],
        "wrong-parse-always-model": [('return hasJsonObject(String.valueOf(event.getOrDefault("text", ""))) ?', "return false ?")],
        "wrong-parse-braces-only": [("return Json.parse(text.substring(start, end + 1)) instanceof Map<?, ?>;", "return true;")],
        "wrong-unknown-tool-integration": [('new String[] {"unknown_tool", "model", "return_error_result"}', 'new String[] {"unknown_tool", "integration", "return_error_result"}')],
        "wrong-tool-error-flagged": [('"tool_result".equals(kind) && event.get("exception") instanceof String s && !s.isEmpty())', '"tool_result".equals(kind) && (event.get("exception") instanceof String s && !s.isEmpty() || Boolean.TRUE.equals(event.get("is_error"))))')],
        "wrong-last-failure": [("        List<String> tools = null, lastBlocks = List.of();\n", "        List<String> tools = null, lastBlocks = List.of();\n        Map<String, Object> last = null;\n"),
                               ('                return map("index", i,', '                last = map("index", i,'),
                               ('        return map("index", -1,', '        return last != null ? last : map("index", -1,')],
        "wrong-recovered-next-only": [("for (Map<String, Object> e : trace.subList(i + 1, trace.size())) {", 'for (Map<String, Object> e : trace.subList(i + 1, trace.size()).stream().filter(x -> "response".equals(x.get("kind"))).limit(1).toList()) {')],
        "wrong-recovered-empty": [('"end_turn".equals(e.get("stop_reason"))\n                && e.get("content") instanceof List<?> c && !c.isEmpty()) return true;', '"end_turn".equals(e.get("stop_reason"))) return true;')],
        "wrong-network-integration": [('return new String[] {"network", "service", "retry_backoff"};', 'return new String[] {"network", "integration", "retry_backoff"};')],
    }),
    "kotlin": ("Diagnose.kt", {
        "wrong-retry-404": [('404 to listOf("not_found", "integration", "fix_request"),', '404 to listOf("not_found", "integration", "retry_backoff"),')],
        "wrong-413-service": [('413 to listOf("request_too_large", "integration", "shrink_request"),', '413 to listOf("request_too_large", "service", "shrink_request"),')],
        "wrong-429-always-retry": [('if (event["error_code"] == "enforced_spend_limit_reached") return', "if (false) return")],
        "wrong-spend-400-ignored": [('if (status == 400 && (event["message"]', 'if (false && (event["message"]')],
        "wrong-maxtokens-model": [('"max_tokens" to listOf("truncated", "integration", "raise_max_tokens"),', '"max_tokens" to listOf("truncated", "model", "raise_max_tokens"),')],
        "wrong-refusal-retry": [('"refusal" to listOf("refusal", "model", "fallback_model"),', '"refusal" to listOf("refusal", "model", "retry_backoff"),')],
        "wrong-empty-always-model": [('return if (at >= 0 && "text" in lastBlocks.subList(at, lastBlocks.size)) listOf(', "return if (false) listOf(")],
        "wrong-empty-text-anywhere": [('return if (at >= 0 && "text" in lastBlocks.subList(at, lastBlocks.size)) listOf(', 'return if (at >= 0 && "text" in lastBlocks) listOf(')],
        "wrong-parse-always-model": [('return if (hasJsonObject(event["text"] as? String ?: "")) listOf(', "return if (false) listOf(")],
        "wrong-parse-braces-only": [("return try { Json.parse(text.substring(start, end + 1)) is Map<*, *> } catch", "return try { true } catch")],
        "wrong-unknown-tool-integration": [('listOf("unknown_tool", "model", "return_error_result")', 'listOf("unknown_tool", "integration", "return_error_result")')],
        "wrong-tool-error-flagged": [('event["kind"] == "tool_result" && !(event["exception"] as? String).isNullOrEmpty())', 'event["kind"] == "tool_result" && (!(event["exception"] as? String).isNullOrEmpty() || event["is_error"] == true))')],
        "wrong-last-failure": [("        var tools: List<*>? = null\n", "        var tools: List<*>? = null\n        var last: Map<String, Any?>? = null\n"),
                               ('            return linkedMapOf("index" to i,', '            last = linkedMapOf("index" to i,'),
                               ('        return linkedMapOf("index" to -1,', '        return last ?: linkedMapOf("index" to -1,')],
        "wrong-recovered-next-only": [("= trace.drop(i + 1).any {", '= trace.drop(i + 1).filter { it["kind"] == "response" }.take(1).any {')],
        "wrong-recovered-empty": [(' && it["stop_reason"] == "end_turn" && !(it["content"] as? List<*>).isNullOrEmpty()', ' && it["stop_reason"] == "end_turn"')],
        "wrong-network-integration": [('"network_error" -> return listOf("network", "service", "retry_backoff")', '"network_error" -> return listOf("network", "integration", "retry_backoff")')],
    }),
}
