# Planted wrong solutions of module 52-designing-tool-interfaces: exact replacements against the practice's reference (see tools/make_plants.py).
# Runs with PLANTS, X and both() in scope; names defined here are local to this file.

PLANTS[f"{X}/52-designing-tool-interfaces/unit-01/practice-1"] = {
    "python": ("toolset.py", {
        "wrong-name-spaces-allowed": [('NAME = re.compile(r"[A-Za-z0-9_-]{1,128}")', 'NAME = re.compile(r"[A-Za-z0-9_ .#-]{1,128}")')],
        "wrong-vague-case-sensitive": [("if name.lower() in VAGUE:", "if name in VAGUE:")],
        "wrong-two-sentences-ok": [("description)) < 3:", "description)) < 2:")],
        "wrong-boundary-do-not-only": [('("do not use", "not for", "instead of")', '("do not use",)')],
        "wrong-required-unchecked": [("if any(item not in properties for item in required):", "if False:")],
        "wrong-example-enum-ignored": [('return "enum" not in schema or value in schema["enum"]', "return True")],
        "wrong-bool-is-integer": [('if kind == "integer" and (isinstance(value, bool) or not isinstance(value, int)):', 'if kind == "integer" and not isinstance(value, int):')],
        "wrong-undescribed-ok": [('if any(not str((spec or {}).get("description") or "").strip() for spec in properties.values()):', "if False:")],
        "wrong-limit-only": [('not ("limit" in properties and "cursor" in properties)', '"limit" not in properties')],
        "wrong-hint-readonly-only": [(' or (hints.get("destructiveHint") is False and name.startswith(DELETE_PREFIXES))', "")],
        "wrong-duplicate-allowed": [('found |= {(name, "duplicate-name") for name in set(names) if names.count(name) > 1}', "found |= set()")],
        "wrong-overlap-strict": [(" >= OVERLAP", " > OVERLAP")],
        "wrong-count-off-by-one": [("if len(tools) > max_tools:", "if len(tools) >= max_tools:")],
        "wrong-limit-unclamped": [("limit = min(limit, MAX_LIMIT)", "limit = limit")],
        "wrong-no-note": [(" if next_cursor else None\n", " if False else None\n")],
        "wrong-cursor-unchecked": [('raise ValueError("invalid cursor")', "return 0")],
        "wrong-cap-exclusive": [("used + len(item) > max_chars", "used + len(item) >= max_chars")],
        "wrong-truncated-never": [('"truncated": len(page) < min(limit, len(items) - offset)', '"truncated": False')],
        "wrong-untrusted-honoured": [("    if trusted_server:\n", "    if True:\n")],
        "wrong-parallel-untrusted": [('effective_hints(tool, tool.get("server") in trusted_servers)', "effective_hints(tool, True)")],
    }),
    "typescript": ("toolset.ts", {
        "wrong-name-spaces-allowed": [("const NAME = /^[A-Za-z0-9_-]{1,128}$/;", "const NAME = /^[A-Za-z0-9_ .#-]{1,128}$/;")],
        "wrong-vague-case-sensitive": [("VAGUE.has(name.toLowerCase())", "VAGUE.has(name)")],
        "wrong-two-sentences-ok": [("?? []).length < 3)", "?? []).length < 2)")],
        "wrong-boundary-do-not-only": [('["do not use", "not for", "instead of"]', '["do not use"]')],
        "wrong-required-unchecked": [("required.some((item) => !(item in properties))", "false")],
        "wrong-example-enum-ignored": [('return !("enum" in schema) || schema.enum.includes(value);', "return true;")],
        "wrong-bool-is-integer": [('if (kind === "integer" && !Number.isInteger(value)) return false;', 'if (kind === "integer" && typeof value !== "number" && typeof value !== "boolean") return false;')],
        "wrong-undescribed-ok": [('specs.some((spec) => !String(spec.description ?? "").trim())', "false")],
        "wrong-limit-only": [('!("limit" in properties && "cursor" in properties)', '!("limit" in properties)')],
        "wrong-hint-readonly-only": [(" || (hints.destructiveHint === false && startsWithAny(name, DELETE_PREFIXES))", "")],
        "wrong-duplicate-allowed": [('.length > 1) add(name, "duplicate-name")', '.length > 99) add(name, "duplicate-name")')],
        "wrong-overlap-strict": [("shared / union.size >= OVERLAP", "shared / union.size > OVERLAP")],
        "wrong-count-off-by-one": [("if (tools.length > maxTools)", "if (tools.length >= maxTools)")],
        "wrong-limit-unclamped": [("limit = Math.min(limit, MAX_LIMIT);", "limit = limit;")],
        "wrong-no-note": [("const note = nextCursor ?", "const note = false ?")],
        "wrong-cursor-unchecked": [('throw new Error("invalid cursor");', "return 0;")],
        "wrong-cap-exclusive": [("used + item.length > maxChars", "used + item.length >= maxChars")],
        "wrong-truncated-never": [("truncated: page.length < Math.min(limit, items.length - offset), note", "truncated: false, note")],
        "wrong-untrusted-honoured": [("  if (trustedServer) {", "  if (true) {")],
        "wrong-parallel-untrusted": [("effectiveHints(tool, trustedServers.has(tool.server))", "effectiveHints(tool, true)")],
    }),
    "java": ("Toolset.java", {
        "wrong-name-spaces-allowed": [('Pattern.compile("[A-Za-z0-9_-]{1,128}")', 'Pattern.compile("[A-Za-z0-9_ .#-]{1,128}")')],
        "wrong-vague-case-sensitive": [("VAGUE.contains(name.toLowerCase(Locale.ROOT))", "VAGUE.contains(name)")],
        "wrong-two-sentences-ok": [("if (count < 3)", "if (count < 2)")],
        "wrong-boundary-do-not-only": [('List.of("do not use", "not for", "instead of").stream()', 'List.of("do not use").stream()')],
        "wrong-required-unchecked": [("required.stream().anyMatch(item -> !properties.containsKey(item))", "false")],
        "wrong-example-enum-ignored": [('return !schema.containsKey("enum") || ((Collection<?>) schema.get("enum")).contains(value);', "return true;")],
        "wrong-bool-is-integer": [('!(value instanceof Integer || value instanceof Long)', '!(value instanceof Integer || value instanceof Long || value instanceof Boolean)')],
        "wrong-undescribed-ok": [('specs.stream().anyMatch(spec -> str(spec.get("description")).isBlank())', "false")],
        "wrong-limit-only": [('!(properties.containsKey("limit") && properties.containsKey("cursor"))', '!properties.containsKey("limit")')],
        "wrong-hint-readonly-only": [(' || (Boolean.FALSE.equals(hints.get("destructiveHint")) && startsWithAny(name, DELETE_PREFIXES))', "")],
        "wrong-duplicate-allowed": [("names.stream().filter(name::equals).count() > 1", "names.stream().filter(name::equals).count() > 99")],
        "wrong-overlap-strict": [("union.size() >= OVERLAP", "union.size() > OVERLAP")],
        "wrong-count-off-by-one": [("if (tools.size() > maxTools)", "if (tools.size() >= maxTools)")],
        "wrong-limit-unclamped": [("limit = Math.min(limit, MAX_LIMIT);", "limit = limit;")],
        "wrong-no-note": [("String note = nextCursor != null ?", "String note = false ?")],
        "wrong-cursor-unchecked": [('throw new IllegalArgumentException("invalid cursor");', "return 0;")],
        "wrong-cap-exclusive": [("used + item.length() > maxChars", "used + item.length() >= maxChars")],
        "wrong-truncated-never": [('result.put("truncated", page.size() < Math.min(limit, items.size() - offset));', 'result.put("truncated", false);')],
        "wrong-untrusted-honoured": [("if (trustedServer) {", "if (true) {")],
        "wrong-parallel-untrusted": [('effectiveHints(tool, trustedServers.contains(str(tool.get("server"))))', "effectiveHints(tool, true)")],
    }),
    "kotlin": ("Toolset.kt", {
        "wrong-name-spaces-allowed": [('Regex("[A-Za-z0-9_-]{1,128}")', 'Regex("[A-Za-z0-9_ .#-]{1,128}")')],
        "wrong-vague-case-sensitive": [("name.lowercase() in VAGUE", "name in VAGUE")],
        "wrong-two-sentences-ok": [(".count() < 3) found.add(\"short-description\")", ".count() < 2) found.add(\"short-description\")")],
        "wrong-boundary-do-not-only": [('listOf("do not use", "not for", "instead of").none', 'listOf("do not use").none')],
        "wrong-required-unchecked": [('if (required.any { str(it) !in properties }) found.add("required-unknown")', 'if (false) found.add("required-unknown")')],
        "wrong-example-enum-ignored": [("return allowed == null || allowed.contains(value)", "return true")],
        "wrong-bool-is-integer": [('"integer" -> if (!(value is Int || value is Long)) return false', '"integer" -> if (!(value is Int || value is Long || value is Boolean)) return false')],
        "wrong-undescribed-ok": [('if (specs.any { str(it["description"]).isBlank() }) found.add("param-undescribed")', 'if (false) found.add("param-undescribed")')],
        "wrong-limit-only": [('!(properties.containsKey("limit") && properties.containsKey("cursor"))', '!properties.containsKey("limit")')],
        "wrong-hint-readonly-only": [(' || (hints["destructiveHint"] == false && startsWithAny(name, DELETE_PREFIXES))', "")],
        "wrong-duplicate-allowed": [("names.count { it == name } > 1", "names.count { it == name } > 99")],
        "wrong-overlap-strict": [(".toDouble() / union.size >= OVERLAP", ".toDouble() / union.size > OVERLAP")],
        "wrong-count-off-by-one": [("if (tools.size > maxTools)", "if (tools.size >= maxTools)")],
        "wrong-limit-unclamped": [("val size = minOf(limit, MAX_LIMIT)", "val size = limit")],
        "wrong-no-note": [('val note = if (nextCursor != null) "', 'val note = if (false) "')],
        "wrong-cursor-unchecked": [('throw IllegalArgumentException("invalid cursor")', "return 0")],
        "wrong-cap-exclusive": [("used + item.length > maxChars", "used + item.length >= maxChars")],
        "wrong-truncated-never": [('"truncated" to (page.size < minOf(size, items.size - offset))', '"truncated" to false')],
        "wrong-untrusted-honoured": [("if (trustedServer) {", "if (true) {")],
        "wrong-parallel-untrusted": [('effectiveHints(it, str(it["server"]) in trustedServers)!!', "effectiveHints(it, true)!!")],
    }),
}
