# Planted wrong solutions of module 53-tool-errors-agents-can-act-on: exact replacements against the practice's reference (see tools/make_plants.py).
# Runs with PLANTS, X and both() in scope; names defined here are local to this file.

PLANTS[f"{X}/53-tool-errors-agents-can-act-on/unit-01/practice-1"] = {
    "python": ("errors.py", {
        "wrong-flag-missing": [('"content": text, "is_error": True}', '"content": text, "is_error": False}')],
        "wrong-business-retryable": [('"permission": False, "business": False', '"permission": False, "business": True')],
        "wrong-generic-message": [('    if str(message or "").strip().lower().rstrip(".") in GENERIC:\n        raise ValueError("an error message must say what went wrong and what to do")\n', "")],
        "wrong-unknown-kind-accepted": [('    if kind not in KINDS:\n        raise ValueError(f"unknown error kind: {kind}")\n', ""), ('"retryable": KINDS[kind]', '"retryable": KINDS.get(kind, False)')],
        "wrong-retries-validation": [('if kind != "transient":', 'if kind not in ("transient", "validation"):')],
        "wrong-flat-wait": [("base * 2 ** (attempts - 1)", "base")],
        "wrong-extra-retry": [("if attempts > max_retries:", "if attempts > max_retries + 1:")],
        "wrong-ignores-retry-after": [("sleep(error.retry_after_ms if error.retry_after_ms is not None else base * 2 ** (attempts - 1))", "sleep(base * 2 ** (attempts - 1))")],
        "wrong-empty-is-error": [('return {"ok": True, "content": value, "empty": _empty(value), "attempts": attempts}', 'return {"ok": not _empty(value), "content": value, "empty": _empty(value), "attempts": attempts}')],
        "wrong-timeout-retried": [("if not safe_to_repeat:", "if False:")],
        "wrong-key-dropped": [('        if key:\n            call_args["idempotency_key"] = key\n', "")],
        "wrong-mutates-args": [("call_args = dict(args)", "call_args = args")],
        "wrong-permission-retry-later": [('"permission": "escalate"', '"permission": "retry_later"')],
        "wrong-internal-retryable": [('"outcome_unknown": False, "internal": False}', '"outcome_unknown": False, "internal": True}')],
    }),
    "typescript": ("errors.ts", {
        "wrong-flag-missing": [("content: text, is_error: true }", "content: text, is_error: false }")],
        "wrong-business-retryable": [("permission: false, business: false", "permission: false, business: true")],
        "wrong-generic-message": [('  if (GENERIC.has(String(message ?? "").trim().toLowerCase().replace(/\\.+$/, ""))) throw new Error("an error message must say what went wrong and what to do");\n', "")],
        "wrong-unknown-kind-accepted": [("  if (!(kind in KINDS)) throw new Error(`unknown error kind: ${kind}`);\n", ""), ("retryable: KINDS[kind]", "retryable: KINDS[kind] ?? false")],
        "wrong-retries-validation": [('if (kind !== "transient") return', 'if (kind !== "transient" && kind !== "validation") return')],
        "wrong-flat-wait": [("base * 2 ** (attempts - 1)", "base")],
        "wrong-extra-retry": [("if (attempts > maxRetries)", "if (attempts > maxRetries + 1)")],
        "wrong-ignores-retry-after": [("sleep(error.retryAfterMs !== null ? error.retryAfterMs : base * 2 ** (attempts - 1));", "sleep(base * 2 ** (attempts - 1));")],
        "wrong-empty-is-error": [("return { ok: true, content: value, empty: isEmpty(value), attempts };", "return { ok: !isEmpty(value), content: value, empty: isEmpty(value), attempts };")],
        "wrong-timeout-retried": [("if (!safeToRepeat) return", "if (false) return")],
        "wrong-key-dropped": [("    if (key) callArgs.idempotency_key = key;\n", "")],
        "wrong-mutates-args": [("const callArgs: Record<string, any> = { ...args };", "const callArgs: Record<string, any> = args;")],
        "wrong-permission-retry-later": [('permission: "escalate"', 'permission: "retry_later"')],
        "wrong-internal-retryable": [("outcome_unknown: false, internal: false }", "outcome_unknown: false, internal: true }")],
    }),
    "java": ("Errors.java", {
        "wrong-flag-missing": [('block.put("is_error", true);', 'block.put("is_error", false);')],
        "wrong-business-retryable": [('"permission", false, "business", false', '"permission", false, "business", true')],
        "wrong-generic-message": [('        if (GENERIC.contains(plain)) throw new IllegalArgumentException("an error message must say what went wrong and what to do");\n', "")],
        "wrong-unknown-kind-accepted": [('        if (!KINDS.containsKey(kind)) throw new IllegalArgumentException("unknown error kind: " + kind);\n', ""), ('error.put("retryable", KINDS.get(kind));', 'error.put("retryable", KINDS.getOrDefault(kind, false));')],
        "wrong-retries-validation": [('if (!kind.equals("transient")) return makeError(kind, error.getMessage(), error.explanation', 'if (!kind.equals("transient") && !kind.equals("validation")) return makeError(kind, error.getMessage(), error.explanation')],
        "wrong-flat-wait": [("base * (1 << (attempts - 1))", "base")],
        "wrong-extra-retry": [("if (attempts > maxRetries)", "if (attempts > maxRetries + 1)")],
        "wrong-ignores-retry-after": [("sleep.accept(error.retryAfterMs != null ? error.retryAfterMs : base * (1 << (attempts - 1)));", "sleep.accept(base * (1 << (attempts - 1)));")],
        "wrong-empty-is-error": [('ok.put("ok", true);', 'ok.put("ok", !isEmpty(value));')],
        "wrong-timeout-retried": [("if (!safeToRepeat) return", "if (false) return")],
        "wrong-key-dropped": [('            if (key != null && !key.isEmpty()) callArgs.put("idempotency_key", key);\n', "")],
        "wrong-mutates-args": [("Map<String, Object> callArgs = new LinkedHashMap<>(args);", "Map<String, Object> callArgs = args;")],
        "wrong-permission-retry-later": [('"permission", "escalate"', '"permission", "retry_later"')],
        "wrong-internal-retryable": [('"outcome_unknown", false, "internal", false);', '"outcome_unknown", false, "internal", true);')],
    }),
    "kotlin": ("Errors.kt", {
        "wrong-flag-missing": [('"content" to text, "is_error" to true)', '"content" to text, "is_error" to false)')],
        "wrong-business-retryable": [('"permission" to false, "business" to false', '"permission" to false, "business" to true')],
        "wrong-generic-message": [('    require(message.trim().lowercase().trimEnd(\'.\') !in GENERIC) { "an error message must say what went wrong and what to do" }\n', "")],
        "wrong-unknown-kind-accepted": [('    require(kind in KINDS) { "unknown error kind: $kind" }\n', ""), ('"retryable" to KINDS[kind]', '"retryable" to (KINDS[kind] ?: false)')],
        "wrong-retries-validation": [('if (kind != "transient") return makeError(kind, error.message ?: ""', 'if (kind != "transient" && kind != "validation") return makeError(kind, error.message ?: ""')],
        "wrong-flat-wait": [("(base * (1 shl (attempts - 1)))", "base")],
        "wrong-extra-retry": [("if (attempts > maxRetries)", "if (attempts > maxRetries + 1)")],
        "wrong-ignores-retry-after": [("sleep(error.retryAfterMs ?: (base * (1 shl (attempts - 1))))", "sleep(base * (1 shl (attempts - 1)))")],
        "wrong-empty-is-error": [('"ok" to true, "content" to value', '"ok" to !isEmpty(value), "content" to value')],
        "wrong-timeout-retried": [("if (!safeToRepeat) return", "if (false) return")],
        "wrong-key-dropped": [('        if (!key.isNullOrEmpty()) callArgs["idempotency_key"] = key\n', "")],
        "wrong-mutates-args": [("val callArgs = LinkedHashMap(args)", "@Suppress(\"UNCHECKED_CAST\") val callArgs = args as MutableMap<String, Any?>")],
        "wrong-permission-retry-later": [('"permission" to "escalate"', '"permission" to "retry_later"')],
        "wrong-internal-retryable": [('"outcome_unknown" to false, "internal" to false)', '"outcome_unknown" to false, "internal" to true)')],
    }),
}
