# Planted wrong solutions of module 54-distributing-tools-across-agents: exact replacements against the practice's reference (see tools/make_plants.py).
# Runs with PLANTS, X and both() in scope; names defined here are local to this file.

PLANTS[f"{X}/54-distributing-tools-across-agents/unit-01/practice-1"] = {
    "python": ("distribute.py", {
        "wrong-sorted-names": [("result[role] = names", "result[role] = sorted(names)")],
        "wrong-no-budget": [("if len(names) > budget:", "if False:")],
        "wrong-unscoped-extra": [('if not (tags & set(tool.get("tags", [])) or tool.get("scoped") or tool.get("irreversible")):', "if False:")],
        "wrong-duplicates-ok": [('        if tool["name"] in by_name:\n            raise ValueError(f"duplicate tool name: {tool[\'name\']}")\n', "")],
        "wrong-irreversible-by-tag": [('if tags & set(t.get("tags", [])) and not t.get("irreversible")]', 'if tags & set(t.get("tags", []))]')],
        "wrong-forces-everywhere": [("rejects = model in NO_FORCING or manual_thinking", "rejects = False")],
        "wrong-fallback-all-tools": [('offered = list(tools) if need == "any" else [forced]', "offered = list(tools)")],
        "wrong-fallback-no-verify": [('"strict": True, "verify_call": True}', '"strict": True, "verify_call": False}')],
        "wrong-tools-ignored": [('    if previous.get("tools") != new.get("tools"):\n        return "all"\n', "")],
        "wrong-choice-ignored": [('    if previous.get("tool_choice") != new.get("tool_choice"):\n        return "messages"\n', "")],
        "wrong-repeat-costs": [('        return "messages"\n    return "none"\n', '        return "messages"\n    return "messages"\n')],
        "wrong-missed-call-ok": [('    if not calls:\n        return "missed_call"\n', "")],
        "wrong-any-tool-counts": [('    if need == "named" and calls[0].get("name") != forced:\n        return "wrong_tool"\n', "")],
        "wrong-default-allow": [('        return _answer(False, "unknown_tool", f"{call.get(\'tool\')} is not an allowed tool")', '        return _answer(True, "ok", "allowed")')],
        "wrong-owner-unchecked": [('    if call.get("verified_customer") is None or call.get("customer") != call.get("verified_customer"):\n        return _answer(False, "not_owner", "the call is not for the verified customer")\n', "")],
        "wrong-cap-exclusive": [("if cap is not None and amount > cap:", "if cap is not None and amount >= cap:")],
        "wrong-approval-lifts-cap": [("if cap is not None and amount > cap:", 'if cap is not None and amount > cap and call.get("id") not in approvals:')],
        "wrong-approval-skipped": [('if rule.get("irreversible") and call.get("id") not in approvals:', "if False:")],
    }),
    "typescript": ("distribute.ts", {
        "wrong-sorted-names": [("result[role] = names;", "result[role] = [...names].sort();")],
        "wrong-no-budget": [("if (names.length > budget) throw", "if (false) throw")],
        "wrong-unscoped-extra": [("if (!(shares(tool) || tool.scoped || tool.irreversible)) throw", "if (false) throw")],
        "wrong-duplicates-ok": [("    if (byName.has(tool.name)) throw new Error(`duplicate tool name: ${tool.name}`);\n", "")],
        "wrong-irreversible-by-tag": [("catalog.filter((t) => shares(t) && !t.irreversible)", "catalog.filter((t) => shares(t))")],
        "wrong-forces-everywhere": [("const rejects = NO_FORCING.has(model) || manualThinking;", "const rejects = false;")],
        "wrong-fallback-all-tools": [('tools: need === "any" ? [...tools] : [forced]', "tools: [...tools]")],
        "wrong-fallback-no-verify": [("strict: true, verify_call: true }", "strict: true, verify_call: false }")],
        "wrong-tools-ignored": [('  if (JSON.stringify(previous.tools) !== JSON.stringify(next.tools)) return "all";\n', "")],
        "wrong-choice-ignored": [('  if (JSON.stringify(previous.tool_choice) !== JSON.stringify(next.tool_choice)) return "messages";\n', "")],
        "wrong-repeat-costs": [('return "messages";\n  return "none";', 'return "messages";\n  return "messages";')],
        "wrong-missed-call-ok": [('  if (calls.length === 0) return "missed_call";\n', "")],
        "wrong-any-tool-counts": [('  if (need === "named" && calls[0].name !== forced) return "wrong_tool";\n', "")],
        "wrong-default-allow": [('return answer(false, "unknown_tool", `${call.tool} is not an allowed tool`);', 'return answer(true, "ok", "allowed");')],
        "wrong-owner-unchecked": [('  if (call.verified_customer === null || call.verified_customer === undefined || call.customer !== call.verified_customer) return answer(false, "not_owner", "the call is not for the verified customer");\n', "")],
        "wrong-cap-exclusive": [("if (cap !== null && amount > cap)", "if (cap !== null && amount >= cap)")],
        "wrong-approval-lifts-cap": [("if (cap !== null && amount > cap)", "if (cap !== null && amount > cap && !new Set(approvals).has(call.id))")],
        "wrong-approval-skipped": [("if (rule.irreversible && !new Set(approvals).has(call.id))", "if (false)")],
    }),
    "java": ("Distribute.java", {
        "wrong-sorted-names": [("result.put(role.getKey(), names);", "java.util.Collections.sort(names);\n            result.put(role.getKey(), names);")],
        "wrong-no-budget": [("if (names.size() > budget) throw", "if (false) throw")],
        "wrong-unscoped-extra": [('if (!(shares(tool, tags) || Boolean.TRUE.equals(tool.get("scoped")) || Boolean.TRUE.equals(tool.get("irreversible")))) {', "if (false) {")],
        "wrong-duplicates-ok": [('            if (byName.containsKey(name)) throw new IllegalArgumentException("duplicate tool name: " + name);\n', "")],
        "wrong-irreversible-by-tag": [('if (shares(tool, tags) && !Boolean.TRUE.equals(tool.get("irreversible"))) names.add(', "if (shares(tool, tags)) names.add(")],
        "wrong-forces-everywhere": [("boolean rejects = NO_FORCING.contains(model) || manualThinking;", "boolean rejects = false;")],
        "wrong-fallback-all-tools": [('need.equals("any") ? new ArrayList<>(tools) : new ArrayList<>(List.of(forced))', "new ArrayList<>(tools)")],
        "wrong-fallback-no-verify": [('"strict", true, "verify_call", true);', '"strict", true, "verify_call", false);')],
        "wrong-tools-ignored": [('        if (!java.util.Objects.equals(previous.get("tools"), next.get("tools"))) return "all";\n', "")],
        "wrong-choice-ignored": [('        if (!java.util.Objects.equals(previous.get("tool_choice"), next.get("tool_choice"))) return "messages";\n', "")],
        "wrong-repeat-costs": [('return "messages";\n        return "none";', 'return "messages";\n        return "messages";')],
        "wrong-missed-call-ok": [('        if (calls.isEmpty()) return "missed_call";\n', "")],
        "wrong-any-tool-counts": [('        if (need.equals("named") && !calls.get(0).get("name").equals(forced)) return "wrong_tool";\n', "")],
        "wrong-default-allow": [('return answer(false, "unknown_tool", call.get("tool") + " is not an allowed tool", false);', 'return answer(true, "ok", "allowed", false);')],
        "wrong-owner-unchecked": [('        if (verified == null || !verified.equals(call.get("customer"))) return answer(false, "not_owner", "the call is not for the verified customer", false);\n', "")],
        "wrong-cap-exclusive": [("(Integer) amount > cap", "(Integer) amount >= cap")],
        "wrong-approval-lifts-cap": [("if (cap != null && (Integer) amount > cap) return answer(", 'if (cap != null && (Integer) amount > cap && !approvals.contains(call.get("id"))) return answer(')],
        "wrong-approval-skipped": [('if (Boolean.TRUE.equals(rule.get("irreversible")) && !approvals.contains(call.get("id"))) return', "if (false) return")],
    }),
    "kotlin": ("Distribute.kt", {
        "wrong-sorted-names": [("result[role] = names", "result[role] = names.sorted()")],
        "wrong-no-budget": [("require(names.size <= budget)", "require(true || names.size <= budget)")],
        "wrong-unscoped-extra": [('require(shares(tool, tags) || tool["scoped"] == true || tool["irreversible"] == true) {', "require(true) {")],
        "wrong-duplicates-ok": [('        require(name !in byName) { "duplicate tool name: $name" }\n', "")],
        "wrong-irreversible-by-tag": [('catalog.filter { shares(it, tags) && it["irreversible"] != true }', "catalog.filter { shares(it, tags) }")],
        "wrong-forces-everywhere": [("val rejects = model in NO_FORCING || manualThinking", "val rejects = false")],
        "wrong-fallback-all-tools": [('(if (need == "any") tools.toList() else listOf(forced))', "tools.toList()")],
        "wrong-fallback-no-verify": [('"strict" to true, "verify_call" to true)', '"strict" to true, "verify_call" to false)')],
        "wrong-tools-ignored": [('    if (previous["tools"] != next["tools"]) return "all"\n', "")],
        "wrong-choice-ignored": [('    if (previous["tool_choice"] != next["tool_choice"]) return "messages"\n', "")],
        "wrong-repeat-costs": [('return "messages"\n    return "none"\n}', 'return "messages"\n    return "messages"\n}')],
        "wrong-missed-call-ok": [('    if (calls.isEmpty()) return "missed_call"\n', "")],
        "wrong-any-tool-counts": [('    if (need == "named" && calls[0]["name"] != forced) return "wrong_tool"\n', "")],
        "wrong-default-allow": [('?: return answer(false, "unknown_tool", "${call["tool"]} is not an allowed tool")', '?: return answer(true, "ok", "allowed")')],
        "wrong-owner-unchecked": [('    val verified = call["verified_customer"]\n    if (verified == null || verified != call["customer"]) return answer(false, "not_owner", "the call is not for the verified customer")\n', "")],
        "wrong-cap-exclusive": [("(amount as Int) > cap", "(amount as Int) >= cap")],
        "wrong-approval-lifts-cap": [("if (cap != null && (amount as Int) > cap)", 'if (cap != null && (amount as Int) > cap && (call["id"] as String) !in approvals)')],
        "wrong-approval-skipped": [('if (rule["irreversible"] == true && (call["id"] as String) !in approvals) return', "if (false) return")],
    }),
}
