# Planted wrong solutions of module 61-criteria-and-examples: exact replacements against the practice's reference (see tools/make_plants.py).
# Runs with PLANTS, X and both() in scope; names defined here are local to this file.

PLANTS[f"{X}/61-criteria-and-examples/unit-01/practice-1"] = {
    "python": ("review_spec.py", {
        "wrong-diff-first": [('return "\\n".join(["<criteria>", *blocks, "</criteria>", "<examples>", *shown, "</examples>", "<diff>", diff, "</diff>"])',
                              'return "\\n".join(["<diff>", diff, "</diff>", "<criteria>", *blocks, "</criteria>", "<examples>", *shown, "</examples>"])')],
        "wrong-vague-report-only": [("            phrase = _vague(c[key])\n", '            phrase = _vague(c[key]) if key == "report" else None\n')],
        "wrong-vague-short-list": [('VAGUE = ("be conservative", ', "VAGUE = (")],
        "wrong-skip-blank": [("            if not _present(c.get(key)):", "            if c.get(key) is None:")],
        "wrong-severity-high-only": [('        for level in ("high", "low"):', '        for level in ("high",):'), ('Severity low: {severity["low"]}', 'Severity low: {severity.get("low", "")}')],
        "wrong-examples-up-to-six": [("if not 2 <= len(examples) <= 4:", "if not 2 <= len(examples) <= 6:")],
        "wrong-all-report-examples": [('if {e.get("verdict") for e in examples} != {"report", "skip"}:', 'if not {e.get("verdict") for e in examples} <= {"report", "skip"}:')],
        "wrong-reason-optional": [('if not _present(e.get("reason")):', 'if e.get("reason") is None:')],
        "wrong-unknown-category": [('if e["verdict"] == "report" and e.get("category") not in ids:', "if False:")],
        "wrong-disable-few": [('"disable": len(items) >= min_reviewed and precision < min_precision', '"disable": precision < min_precision')],
        "wrong-precision-inverted": [("precision = round(accepted / len(items), 2)", "precision = round((len(items) - accepted) / len(items), 2)")],
        "wrong-boundary-disables": [("precision < min_precision", "precision <= min_precision")],
        "wrong-top-by-name": [("key=lambda kv: (-kv[1], kv[0])", "key=lambda kv: kv[0]")],
        "wrong-top-uncapped": [("))[:3]", "))")],
        "wrong-counts-accepted": [('            if f["verdict"] == "dismissed":', "            if True:")],
        "wrong-ask-defaults": [("unresolved = [f for f in missing if f not in defaults]", "unresolved = list(missing)")],
        "wrong-no-assumptions": [("assumptions = {f: defaults[f] for f in missing if f in defaults}", "assumptions = {}")],
        "wrong-unattended-asks": [('return {"action": "stop", "ask": [], "assumptions": assumptions}', 'return {"action": "ask", "ask": unresolved, "assumptions": assumptions}')],
        "wrong-unattended-guess": [('    if unresolved:\n        return {"action": "stop", "ask": [], "assumptions": assumptions}\n', "")],
        "wrong-blank-is-present": [('return value is None or (isinstance(value, str) and value.strip() == "")', 'return value is None or value == ""')],
    }),
    "typescript": ("reviewSpec.ts", {
        "wrong-diff-first": [('return ["<criteria>", ...blocks, "</criteria>", "<examples>", ...shown, "</examples>", "<diff>", diff, "</diff>"].join("\\n");',
                              'return ["<diff>", diff, "</diff>", "<criteria>", ...blocks, "</criteria>", "<examples>", ...shown, "</examples>"].join("\\n");')],
        "wrong-vague-report-only": [("const phrase = vague(c[key]);", 'const phrase = key === "report" ? vague(c[key]) : undefined;')],
        "wrong-vague-short-list": [('export const VAGUE = ["be conservative", ', "export const VAGUE = [")],
        "wrong-skip-blank": [("if (!present(c[key])) throw new Error(`criterion ${c.id}: ${key} is required`);", "if (c[key] === undefined || c[key] === null) throw new Error(`criterion ${c.id}: ${key} is required`);")],
        "wrong-severity-high-only": [('for (const level of ["high", "low"]) {', 'for (const level of ["high"]) {')],
        "wrong-examples-up-to-six": [("examples.length > 4", "examples.length > 6")],
        "wrong-all-report-examples": [('if (verdicts.join() !== "report,skip")', 'if (verdicts.some((v) => v !== "report" && v !== "skip"))')],
        "wrong-reason-optional": [("if (!present(e.reason)) throw", "if (e.reason === undefined || e.reason === null) throw")],
        "wrong-unknown-category": [('if (e.verdict === "report" && !ids.includes(e.category)) throw', "if (false) throw")],
        "wrong-disable-few": [("disable: items.length >= minReviewed && precision < minPrecision", "disable: precision < minPrecision")],
        "wrong-precision-inverted": [("Math.round((accepted / items.length) * 100) / 100", "Math.round(((items.length - accepted) / items.length) * 100) / 100")],
        "wrong-boundary-disables": [("precision < minPrecision", "precision <= minPrecision")],
        "wrong-top-by-name": [(".sort((a, b) => b[1] - a[1] || (a[0] < b[0] ? -1 : a[0] > b[0] ? 1 : 0))", ".sort((a, b) => (a[0] < b[0] ? -1 : a[0] > b[0] ? 1 : 0))")],
        "wrong-top-uncapped": [(".slice(0, 3);", ";")],
        "wrong-counts-accepted": [('for (const f of items) if (f.verdict === "dismissed") counts.set(', "for (const f of items) if (true) counts.set(")],
        "wrong-ask-defaults": [("const unresolved = missing.filter((f) => !(f in defaults));", "const unresolved = [...missing];")],
        "wrong-no-assumptions": [("  for (const f of missing) if (f in defaults) assumptions[f] = defaults[f];\n", "")],
        "wrong-unattended-asks": [('if (unresolved.length > 0) return { action: "stop", ask: [], assumptions };', 'if (unresolved.length > 0) return { action: "ask", ask: unresolved, assumptions };')],
        "wrong-unattended-guess": [('  if (unresolved.length > 0) return { action: "stop", ask: [], assumptions };\n', "")],
        "wrong-blank-is-present": [('(typeof value === "string" && value.trim() === "");', '(typeof value === "string" && value === "");')],
    }),
    "java": ("ReviewSpec.java", {
        "wrong-diff-first": [('return String.join("\\n", out);', 'return String.join("\\n", out.subList(out.size() - 3, out.size())) + "\\n" + String.join("\\n", out.subList(0, out.size() - 3));')],
        "wrong-vague-report-only": [('String phrase = vague((String) c.get(key));', 'String phrase = key.equals("report") ? vague((String) c.get(key)) : null;')],
        "wrong-vague-short-list": [('List.of("be conservative", "high-confidence"', 'List.of("high-confidence"')],
        "wrong-skip-blank": [('if (!present(c.get(key))) throw new IllegalArgumentException("criterion " + c.get("id") + ": " + key + " is required");', 'if (c.get(key) == null) throw new IllegalArgumentException("criterion " + c.get("id") + ": " + key + " is required");')],
        "wrong-severity-high-only": [('for (String level : List.of("high", "low")) {', 'for (String level : List.of("high")) {')],
        "wrong-examples-up-to-six": [("examples.size() > 4", "examples.size() > 6")],
        "wrong-all-report-examples": [('if (!verdicts.equals(Set.of("report", "skip")))', 'if (!Set.of("report", "skip").containsAll(verdicts))')],
        "wrong-reason-optional": [('if (!present(e.get("reason"))) throw', 'if (e.get("reason") == null) throw')],
        "wrong-unknown-category": [('if ("report".equals(e.get("verdict")) && !ids.contains(e.get("category"))) throw', "if (false) throw")],
        "wrong-disable-few": [("boolean off = items.size() >= minReviewed && precision < minPrecision;", "boolean off = precision < minPrecision;")],
        "wrong-precision-inverted": [("Math.round((double) accepted / items.size() * 100) / 100.0", "Math.round((double) (items.size() - accepted) / items.size() * 100) / 100.0")],
        "wrong-boundary-disables": [("precision < minPrecision", "precision <= minPrecision")],
        "wrong-top-by-name": [("top.sort((a, b) -> b.getValue().equals(a.getValue()) ? a.getKey().compareTo(b.getKey()) : b.getValue().compareTo(a.getValue()));", "top.sort((a, b) -> a.getKey().compareTo(b.getKey()));")],
        "wrong-top-uncapped": [("i < Math.min(3, top.size())", "i < top.size()")],
        "wrong-counts-accepted": [('else if ("dismissed".equals(f.get("verdict"))) counts.merge(', "if (true) counts.merge(")],
        "wrong-ask-defaults": [("            else unresolved.add(f);", "            unresolved.add(f);")],
        "wrong-no-assumptions": [("if (defaults.containsKey(f)) assumptions.put(f, defaults.get(f));", "if (defaults.containsKey(f)) assumptions.size();")],
        "wrong-unattended-asks": [('return map("action", "stop", "ask", List.of(), "assumptions", assumptions);', 'return map("action", "ask", "ask", unresolved, "assumptions", assumptions);')],
        "wrong-unattended-guess": [('        if (!unresolved.isEmpty()) return map("action", "stop", "ask", List.of(), "assumptions", assumptions);\n', "")],
        "wrong-blank-is-present": [("return value == null || (value instanceof String s && s.isBlank());", "return value == null || (value instanceof String s && s.isEmpty());")],
    }),
    "kotlin": ("ReviewSpec.kt", {
        "wrong-diff-first": [('return out.joinToString("\\n")', 'return (out.takeLast(3) + out.dropLast(3)).joinToString("\\n")')],
        "wrong-vague-report-only": [("val phrase = vague(c[key] as String)", 'val phrase = if (key == "report") vague(c[key] as String) else null')],
        "wrong-vague-short-list": [('listOf("be conservative", "high-confidence"', 'listOf("high-confidence"')],
        "wrong-skip-blank": [('require(present(c[key])) { "criterion ${c["id"]}: $key is required" }', 'require(c[key] != null) { "criterion ${c["id"]}: $key is required" }')],
        "wrong-severity-high-only": [('for (level in listOf("high", "low")) require(present(severity[level]))', 'for (level in listOf("high")) require(present(severity[level]))')],
        "wrong-examples-up-to-six": [("examples.size in 2..4", "examples.size in 2..6")],
        "wrong-all-report-examples": [('require(examples.map { it["verdict"] }.toSet() == setOf("report", "skip"))', 'require(setOf("report", "skip").containsAll(examples.map { it["verdict"] }.toSet()))')],
        "wrong-reason-optional": [('require(present(e["reason"])) { "every example needs a reason" }', 'require(e["reason"] != null) { "every example needs a reason" }')],
        "wrong-unknown-category": [('require(e["verdict"] != "report" || e["category"] in ids) {', "require(true) {")],
        "wrong-disable-few": [("val off = items.size >= minReviewed && precision < minPrecision", "val off = precision < minPrecision")],
        "wrong-precision-inverted": [("Math.round(accepted.toDouble() / items.size * 100) / 100.0", "Math.round((items.size - accepted).toDouble() / items.size * 100) / 100.0")],
        "wrong-boundary-disables": [("precision < minPrecision", "precision <= minPrecision")],
        "wrong-top-by-name": [(".sortedWith(compareBy({ -it.value }, { it.key }))", ".sortedWith(compareBy({ it.key }))")],
        "wrong-top-uncapped": [(".take(3).map {", ".map {")],
        "wrong-counts-accepted": [('items.filter { it["verdict"] == "dismissed" }.groupingBy', "items.groupingBy")],
        "wrong-ask-defaults": [("val unresolved = missing.filter { it !in defaults }", "val unresolved = missing")],
        "wrong-no-assumptions": [("    missing.filter { it in defaults }.forEach { assumptions[it] = defaults.getValue(it) }\n", "")],
        "wrong-unattended-asks": [('unresolved.isNotEmpty() -> mapOf("action" to "stop", "ask" to emptyList<String>(), "assumptions" to assumptions)', 'unresolved.isNotEmpty() -> mapOf("action" to "ask", "ask" to unresolved, "assumptions" to assumptions)')],
        "wrong-unattended-guess": [('        unresolved.isNotEmpty() -> mapOf("action" to "stop", "ask" to emptyList<String>(), "assumptions" to assumptions)\n', "")],
        "wrong-blank-is-present": [("(value is String && value.isBlank())", "(value is String && value.isEmpty())")],
    }),
}
