# Planted wrong solutions of module 62-structured-output-at-the-architect-level: exact replacements against the practice's reference (see tools/make_plants.py).
# Runs with PLANTS, X and both() in scope; names defined here are local to this file.

PLANTS[f"{X}/62-structured-output-at-the-architect-level/unit-01/practice-1"] = {
    "python": ("extraction.py", {
        "wrong-grounding-skipped": [('return isinstance(quote, str) and quote != "" and quote in document', 'return isinstance(quote, str) and quote != ""')],
        "wrong-null-needs-quote": [('        value = record[field]\n        if value is None or value == "unclear":', '        value = record[field]\n        if value == "unclear":')],
        "wrong-feedback-all-errors": [('feedback = {"previous": record, "errors": retryable}', 'feedback = {"previous": record, "errors": errors}')],
        "wrong-feedback-no-previous": [('feedback = {"previous": record, "errors": retryable}', 'feedback = {"previous": None, "errors": retryable}')],
        "wrong-retry-absent": [("        if not retryable:\n            break\n", "")],
        "wrong-absent-failed": [('status = "needs_review" if all(e["kind"] == "absent" for e in errors) else "failed"', 'status = "failed"')],
        "wrong-extra-retry": [("if attempts > max_retries:", "if attempts > max_retries + 1:")],
        "wrong-sum-unchecked": [('    if abs(sum(items) - record["calculated_total"]) > 0.005:', "    if False:")],
        "wrong-conflict-error": [(' and not record["conflict_detected"]:', ":")],
        "wrong-conflict-valid": [('    elif record["conflict_detected"]:', "    elif False:")],
        "wrong-unclear-needs-quote": [('        value = record[field]\n        if value is None or value == "unclear":', "        value = record[field]\n        if value is None:")],
        "wrong-other-no-detail": [('return currency == "other" and not (isinstance(detail, str) and detail.strip())', "return False")],
        "wrong-currency-open": [('return currency in CURRENCIES', "return isinstance(currency, str)")],
        "wrong-merge-last-wins": [('return value is None or value == "unclear"', "return True")],
        "wrong-merge-no-conflict": [('return current != value and field not in conflicts', "return False")],
        "wrong-accuracy-validated-only": [('"all_documents": round(correct / total, 2) if total else 0.0', '"all_documents": round(correct / valid, 2) if valid else 0.0')],
        "wrong-accuracy-missing-skipped": [("    total = len(labels)", "    total = len([d for d in labels if d in results])")],
        "wrong-force-always": [('    if model in NO_FORCING:\n        return {"tool_choice": {"type": "auto"}, "strict": True, "verify_reply": True}\n', "")],
        "wrong-any-for-single": [("    if len(tools) > 1:", "    if len(tools) >= 1:")],
        "wrong-no-verify": [('{"tool_choice": {"type": "auto"}, "strict": True, "verify_reply": True}', '{"tool_choice": {"type": "auto"}, "strict": True, "verify_reply": False}')],
    }),
    "typescript": ("extraction.ts", {
        "wrong-grounding-skipped": [('return typeof quote === "string" && quote !== "" && document.includes(quote);', 'return typeof quote === "string" && quote !== "";')],
        "wrong-null-needs-quote": [('if (value === null || value === "unclear") continue;', 'if (value === "unclear") continue;')],
        "wrong-feedback-all-errors": [("feedback = { previous: record, errors: retryable };", "feedback = { previous: record, errors };")],
        "wrong-feedback-no-previous": [("feedback = { previous: record, errors: retryable };", "feedback = { previous: null, errors: retryable };")],
        "wrong-retry-absent": [("    if (retryable.length === 0) break;\n", "")],
        "wrong-absent-failed": [('status = errors.every((e) => e.kind === "absent") ? "needs_review" : "failed";', 'status = "failed";')],
        "wrong-extra-retry": [("if (attempts > maxRetries) break;", "if (attempts > maxRetries + 1) break;")],
        "wrong-sum-unchecked": [("if (Math.abs(sum - record.calculated_total) > 0.005) err(", "if (false) err(")],
        "wrong-conflict-error": [(" && !record.conflict_detected) {", ") {")],
        "wrong-conflict-valid": [('else if (record.conflict_detected) status = "needs_review";', 'else if (false) status = "needs_review";')],
        "wrong-unclear-needs-quote": [('if (value === null || value === "unclear") continue;', "if (value === null) continue;")],
        "wrong-other-no-detail": [('return currency === "other" && !(typeof detail === "string" && detail.trim() !== "");', "return false;")],
        "wrong-currency-open": [("return CURRENCIES.includes(currency as string);", 'return typeof currency === "string";')],
        "wrong-merge-last-wins": [('return value === null || value === "unclear";', "return true;")],
        "wrong-merge-no-conflict": [("return current !== value && !conflicts.includes(field);", "return false;")],
        "wrong-accuracy-validated-only": [("all_documents: total ? round2(correct / total) : 0", "all_documents: valid ? round2(correct / valid) : 0")],
        "wrong-accuracy-missing-skipped": [("const total = Object.keys(labels).length;", "const total = Object.keys(labels).filter((d) => d in results).length;")],
        "wrong-force-always": [('  if (NO_FORCING.has(model)) return { tool_choice: { type: "auto" }, strict: true, verify_reply: true };\n', "")],
        "wrong-any-for-single": [("if (tools.length > 1) return", "if (tools.length >= 1) return")],
        "wrong-no-verify": [('{ tool_choice: { type: "auto" }, strict: true, verify_reply: true }', '{ tool_choice: { type: "auto" }, strict: true, verify_reply: false }')],
    }),
    "java": ("Extraction.java", {
        "wrong-grounding-skipped": [('return quote instanceof String q && !q.isEmpty() && document.contains(q);', "return quote instanceof String q && !q.isEmpty();")],
        "wrong-null-needs-quote": [('            if (value == null || "unclear".equals(value)) continue;\n            Object quote', '            if ("unclear".equals(value)) continue;\n            Object quote')],
        "wrong-feedback-all-errors": [('feedback = map("previous", record, "errors", retryable);', 'feedback = map("previous", record, "errors", errors);')],
        "wrong-feedback-no-previous": [('feedback = map("previous", record, "errors", retryable);', 'feedback = map("previous", null, "errors", retryable);')],
        "wrong-retry-absent": [("            if (retryable.isEmpty()) break;\n", "")],
        "wrong-absent-failed": [('status = errors.stream().allMatch(e -> "absent".equals(e.get("kind"))) ? "needs_review" : "failed";', 'status = "failed";')],
        "wrong-extra-retry": [("if (attempts > maxRetries) break;", "if (attempts > maxRetries + 1) break;")],
        "wrong-sum-unchecked": [("if (Math.abs(sum - calculated) > 0.005) err(", "if (false) err(")],
        "wrong-conflict-error": [('if (Math.abs(stated - calculated) > 0.005 && !((Boolean) record.get("conflict_detected"))) {', "if (Math.abs(stated - calculated) > 0.005) {")],
        "wrong-conflict-valid": [('else if (Boolean.TRUE.equals(record.get("conflict_detected"))) status = "needs_review";', 'else if (false) status = "needs_review";')],
        "wrong-unclear-needs-quote": [('            if (value == null || "unclear".equals(value)) continue;\n            Object quote', "            if (value == null) continue;\n            Object quote")],
        "wrong-other-no-detail": [('return "other".equals(currency) && !(detail instanceof String d && !d.isBlank());', "return false;")],
        "wrong-currency-open": [('return CURRENCIES.contains(currency);', "return currency instanceof String;")],
        "wrong-merge-last-wins": [('return value == null || "unclear".equals(value);', "return true;")],
        "wrong-merge-no-conflict": [("return !current.equals(value) && !conflicts.contains(field);", "return false;")],
        "wrong-accuracy-validated-only": [('"all_documents", total > 0 ? round2((double) correct / total) : 0.0', '"all_documents", valid > 0 ? round2((double) correct / valid) : 0.0')],
        "wrong-accuracy-missing-skipped": [("int total = labels.size();", "int total = (int) labels.keySet().stream().filter(results::containsKey).count();")],
        "wrong-force-always": [('        if (NO_FORCING.contains(model)) return map("tool_choice", map("type", "auto"), "strict", true, "verify_reply", true);\n', "")],
        "wrong-any-for-single": [("if (tools.size() > 1) return", "if (tools.size() >= 1) return")],
        "wrong-no-verify": [('map("tool_choice", map("type", "auto"), "strict", true, "verify_reply", true)', 'map("tool_choice", map("type", "auto"), "strict", true, "verify_reply", false)')],
    }),
    "kotlin": ("Extraction.kt", {
        "wrong-grounding-skipped": [("return quote is String && quote.isNotEmpty() && document.contains(quote)", "return quote is String && quote.isNotEmpty()")],
        "wrong-null-needs-quote": [('        if (value == null || value == "unclear") continue\n        val quote', '        if (value == "unclear") continue\n        val quote')],
        "wrong-feedback-all-errors": [('feedback = mapOf("previous" to record, "errors" to retryable)', 'feedback = mapOf("previous" to record, "errors" to errors)')],
        "wrong-feedback-no-previous": [('feedback = mapOf("previous" to record, "errors" to retryable)', 'feedback = mapOf("previous" to null, "errors" to retryable)')],
        "wrong-retry-absent": [("        if (retryable.isEmpty()) break\n", "")],
        "wrong-absent-failed": [('errors.isNotEmpty() -> if (errors.all { it["kind"] == "absent" }) "needs_review" else "failed"', 'errors.isNotEmpty() -> "failed"')],
        "wrong-extra-retry": [("if (attempts > maxRetries) break", "if (attempts > maxRetries + 1) break")],
        "wrong-sum-unchecked": [("if (Math.abs(sum - calculated) > 0.005) errors +=", "if (false) errors +=")],
        "wrong-conflict-error": [(' && record["conflict_detected"] != true) {', ") {")],
        "wrong-conflict-valid": [('record["conflict_detected"] == true -> "needs_review"', 'false -> "needs_review"')],
        "wrong-unclear-needs-quote": [('        if (value == null || value == "unclear") continue\n        val quote', "        if (value == null) continue\n        val quote")],
        "wrong-other-no-detail": [('return currency == "other" && !(detail is String && detail.isNotBlank())', "return false")],
        "wrong-currency-open": [("return currency in CURRENCIES", "return currency is String")],
        "wrong-merge-last-wins": [('return value == null || value == "unclear"', "return true")],
        "wrong-merge-no-conflict": [("return current != value && field !in conflicts", "return false")],
        "wrong-accuracy-validated-only": [('"all_documents" to if (total > 0) round2(correct.toDouble() / total) else 0.0', '"all_documents" to if (valid > 0) round2(correct.toDouble() / valid) else 0.0')],
        "wrong-accuracy-missing-skipped": [("val total = labels.size", "val total = labels.keys.count { it in results }")],
        "wrong-force-always": [('    if (model in NO_FORCING) return mapOf("tool_choice" to mapOf("type" to "auto"), "strict" to true, "verify_reply" to true)\n', "")],
        "wrong-any-for-single": [("tools.size > 1 ->", "tools.size >= 1 ->")],
        "wrong-no-verify": [('mapOf("tool_choice" to mapOf("type" to "auto"), "strict" to true, "verify_reply" to true)', 'mapOf("tool_choice" to mapOf("type" to "auto"), "strict" to true, "verify_reply" to false)')],
    }),
}
