# Planted wrong solutions of module 70-scenario-customer-support-agent: exact replacements against the practice's reference (see tools/make_plants.py).
# Runs with PLANTS, X and both() in scope; names defined here are local to this file.

PLANTS[f"{X}/70-scenario-customer-support-agent/unit-01/practice-1"] = {
    "python": ("audit.py", {
        "wrong-prereq-ignores-order": [('        elif step["tool"] in PROTECTED and not verified:', '        elif step["tool"] in PROTECTED:')],
        "wrong-failed-identity-opens": [('if step["tool"] == "get_customer" and step["ok"]:', 'if step["tool"] == "get_customer":')],
        "wrong-over-limit-any-outcome": [('if s["outcome"] == "resolved" and s["refund_cents"] > s["limit_cents"])', 'if s["refund_cents"] > s["limit_cents"])')],
        "wrong-diagnosis-criteria-first": [('    elif wrong and wrong >= over + under:\n        diagnosis = "rewrite_tool_descriptions"\n    elif over + under:\n        diagnosis = "write_escalation_criteria"\n',
                                            '    elif over + under:\n        diagnosis = "write_escalation_criteria"\n    elif wrong and wrong >= over + under:\n        diagnosis = "rewrite_tool_descriptions"\n')],
        "wrong-target-strict": [('"meets_target": fcr >= TARGET', '"meets_target": fcr > TARGET')],
        "wrong-wrong-tool-steps": [('wrong = sum(1 for s in sessions if any(st.get("right_tool") and st["tool"] != st["right_tool"] for st in s["steps"]))',
                                    'wrong = sum(1 for s in sessions for st in s["steps"] if st.get("right_tool") and st["tool"] != st["right_tool"])')],
        "wrong-no-rounding": [('fcr = round(resolved / n, 3) if n else 0.0', 'fcr = resolved / n if n else 0.0')],
        "wrong-over-counts-needs-human": [('over = sum(1 for s in sessions if s["outcome"] == "escalated" and not s["needs_human"])', 'over = sum(1 for s in sessions if s["outcome"] == "escalated")')],
    }),
    "typescript": ("audit.ts", {
        "wrong-prereq-ignores-order": [("else if (PROTECTED.includes(step.tool) && !verified) return true;", "else if (PROTECTED.includes(step.tool)) return true;")],
        "wrong-failed-identity-opens": [('if (step.tool === "get_customer" && step.ok) verified = true;', 'if (step.tool === "get_customer") verified = true;')],
        "wrong-over-limit-any-outcome": [('count((s) => s.outcome === "resolved" && s.refund_cents > s.limit_cents)', "count((s) => s.refund_cents > s.limit_cents)")],
        "wrong-diagnosis-criteria-first": [('  else if (wrong && wrong >= over + under) diagnosis = "rewrite_tool_descriptions";\n  else if (over + under) diagnosis = "write_escalation_criteria";\n',
                                            '  else if (over + under) diagnosis = "write_escalation_criteria";\n  else if (wrong && wrong >= over + under) diagnosis = "rewrite_tool_descriptions";\n')],
        "wrong-target-strict": [("meets_target: fcr >= TARGET", "meets_target: fcr > TARGET")],
        "wrong-wrong-tool-steps": [("const wrong = count((s) => s.steps.some((st) => st.right_tool && st.tool !== st.right_tool));",
                                    "const wrong = sessions.reduce((a, s) => a + s.steps.filter((st) => st.right_tool && st.tool !== st.right_tool).length, 0);")],
        "wrong-no-rounding": [("const fcr = n ? Math.round((resolved / n) * 1000) / 1000 : 0;", "const fcr = n ? resolved / n : 0;")],
        "wrong-over-counts-needs-human": [('const over = count((s) => s.outcome === "escalated" && !s.needs_human);', 'const over = count((s) => s.outcome === "escalated");')],
    }),
    "java": ("Audit.java", {
        "wrong-prereq-ignores-order": [("else if (PROTECTED.contains(step.tool()) && !verified) return true;", "else if (PROTECTED.contains(step.tool())) return true;")],
        "wrong-failed-identity-opens": [('if (step.tool().equals("get_customer") && step.ok()) verified = true;', 'if (step.tool().equals("get_customer")) verified = true;')],
        "wrong-over-limit-any-outcome": [('s.outcome().equals("resolved") && s.refundCents() > s.limitCents()', "s.refundCents() > s.limitCents()")],
        "wrong-diagnosis-criteria-first": [('        else if (wrong > 0 && wrong >= over + under) diagnosis = "rewrite_tool_descriptions";\n        else if (over + under > 0) diagnosis = "write_escalation_criteria";\n',
                                            '        else if (over + under > 0) diagnosis = "write_escalation_criteria";\n        else if (wrong > 0 && wrong >= over + under) diagnosis = "rewrite_tool_descriptions";\n')],
        "wrong-target-strict": [("fcr >= TARGET", "fcr > TARGET")],
        "wrong-wrong-tool-steps": [("int wrong = (int) sessions.stream().filter(s -> s.steps().stream().anyMatch(st -> st.rightTool() != null && !st.tool().equals(st.rightTool()))).count();",
                                    "int wrong = (int) sessions.stream().flatMap(s -> s.steps().stream()).filter(st -> st.rightTool() != null && !st.tool().equals(st.rightTool())).count();")],
        "wrong-no-rounding": [("double fcr = n > 0 ? Math.round((double) resolved / n * 1000) / 1000.0 : 0.0;", "double fcr = n > 0 ? (double) resolved / n : 0.0;")],
        "wrong-over-counts-needs-human": [('int over = (int) sessions.stream().filter(s -> s.outcome().equals("escalated") && !s.needsHuman()).count();', 'int over = (int) sessions.stream().filter(s -> s.outcome().equals("escalated")).count();')],
    }),
    "kotlin": ("Audit.kt", {
        "wrong-prereq-ignores-order": [("else if (step.tool in PROTECTED && !verified) return true", "else if (step.tool in PROTECTED) return true")],
        "wrong-failed-identity-opens": [('if (step.tool == "get_customer" && step.ok) verified = true', 'if (step.tool == "get_customer") verified = true')],
        "wrong-over-limit-any-outcome": [('sessions.count { it.outcome == "resolved" && it.refundCents > it.limitCents }', "sessions.count { it.refundCents > it.limitCents }")],
        "wrong-diagnosis-criteria-first": [('        wrong > 0 && wrong >= over + under -> "rewrite_tool_descriptions"\n        over + under > 0 -> "write_escalation_criteria"\n',
                                            '        over + under > 0 -> "write_escalation_criteria"\n        wrong > 0 && wrong >= over + under -> "rewrite_tool_descriptions"\n')],
        "wrong-target-strict": [("fcr >= TARGET", "fcr > TARGET")],
        "wrong-wrong-tool-steps": [("val wrong = sessions.count { s -> s.steps.any { it.rightTool != null && it.tool != it.rightTool } }",
                                    "val wrong = sessions.sumOf { s -> s.steps.count { it.rightTool != null && it.tool != it.rightTool } }")],
        "wrong-no-rounding": [("val fcr = if (n > 0) Math.round(resolved.toDouble() / n * 1000) / 1000.0 else 0.0", "val fcr = if (n > 0) resolved.toDouble() / n else 0.0")],
        "wrong-over-counts-needs-human": [('val over = sessions.count { it.outcome == "escalated" && !it.needsHuman }', 'val over = sessions.count { it.outcome == "escalated" }')],
    }),
}
