# Planted wrong solutions of module 75-scenario-structured-data-extraction: exact replacements against the practice's reference (see tools/make_plants.py).
# Runs with PLANTS, X and both() in scope; names defined here are local to this file.

PLANTS[f"{X}/75-scenario-structured-data-extraction/unit-01/practice-1"] = {
    "python": ("run_audit.py", {
        "wrong-validated-denominator": [("accuracy_all = percent(right, n)", 'accuracy_all = percent(right, counts["valid"])')],
        "wrong-target-strict": [("return n > 0 and right * 100 >= target * n", "return n > 0 and right * 100 > target * n")],
        "wrong-segment-strict": [('ok * 100 >= policy["target"] * len(group)', 'ok * 100 > policy["target"] * len(group)')],
        "wrong-min-n-ignored": [('len(group) >= policy["min_n"] and ', "")],
        "wrong-gap-inclusive": [("return accuracy_validated - accuracy_all > gap", "return accuracy_validated - accuracy_all >= gap")],
        "wrong-unchecked-any-status": [('if r["status"] == "valid" and not r["sum_ok"])', 'if not r["sum_ok"])')],
        "wrong-fix-unchecked-before-wasted": [('    if wasted:\n        return "stop_retrying_absent"\n    if unchecked:\n        return "add_semantic_checks"\n',
                                               '    if unchecked:\n        return "add_semantic_checks"\n    if wasted:\n        return "stop_retrying_absent"\n')],
        "wrong-rounding-floor": [("return (200 * correct + total) // (2 * total) if total else 0", "return 100 * correct // total if total else 0")],
        "wrong-empty-meets-target": [("return n > 0 and right * 100 >= target * n", "return right * 100 >= target * n")],
    }),
    "typescript": ("runAudit.ts", {
        "wrong-validated-denominator": [("const accuracyAll = percent(right, n);", "const accuracyAll = percent(right, valid);")],
        "wrong-target-strict": [("return n > 0 && right * 100 >= target * n;", "return n > 0 && right * 100 > target * n;")],
        "wrong-segment-strict": [("ok * 100 >= policy.target * group.length", "ok * 100 > policy.target * group.length")],
        "wrong-min-n-ignored": [("group.length >= policy.min_n && ", "")],
        "wrong-gap-inclusive": [("return accuracyValidated - accuracyAll > gap;", "return accuracyValidated - accuracyAll >= gap;")],
        "wrong-unchecked-any-status": [('r.status === "valid" && !r.sum_ok', "!r.sum_ok")],
        "wrong-fix-unchecked-before-wasted": [('  if (wasted) return "stop_retrying_absent";\n  if (unchecked) return "add_semantic_checks";\n',
                                               '  if (unchecked) return "add_semantic_checks";\n  if (wasted) return "stop_retrying_absent";\n')],
        "wrong-rounding-floor": [("Math.floor((200 * correct + total) / (2 * total))", "Math.floor((100 * correct) / total)")],
        "wrong-empty-meets-target": [("return n > 0 && right * 100 >= target * n;", "return right * 100 >= target * n;")],
    }),
    "java": ("RunAudit.java", {
        "wrong-validated-denominator": [("int accuracyAll = percent(right, n);", "int accuracyAll = percent(right, valid);")],
        "wrong-target-strict": [("return n > 0 && right * 100 >= target * n;", "return n > 0 && right * 100 > target * n;")],
        "wrong-segment-strict": [("ok * 100 >= policy.target() * group.size()", "ok * 100 > policy.target() * group.size()")],
        "wrong-min-n-ignored": [("group.size() >= policy.minN() && ", "")],
        "wrong-gap-inclusive": [("return accuracyValidated - accuracyAll > gap;", "return accuracyValidated - accuracyAll >= gap;")],
        "wrong-unchecked-any-status": [('r.status().equals("valid") && !r.sumOk()', "!r.sumOk()")],
        "wrong-fix-unchecked-before-wasted": [('        if (wasted > 0) return "stop_retrying_absent";\n        if (unchecked > 0) return "add_semantic_checks";\n',
                                               '        if (unchecked > 0) return "add_semantic_checks";\n        if (wasted > 0) return "stop_retrying_absent";\n')],
        "wrong-rounding-floor": [("(200 * correct + total) / (2 * total)", "100 * correct / total")],
        "wrong-empty-meets-target": [("return n > 0 && right * 100 >= target * n;", "return right * 100 >= target * n;")],
    }),
    "kotlin": ("RunAudit.kt", {
        "wrong-validated-denominator": [("val accuracyAll = percent(right, n)", "val accuracyAll = percent(right, valid)")],
        "wrong-target-strict": [("= n > 0 && right * 100 >= target * n", "= n > 0 && right * 100 > target * n")],
        "wrong-segment-strict": [("ok * 100 >= policy.target * group.size", "ok * 100 > policy.target * group.size")],
        "wrong-min-n-ignored": [("group.size >= policy.minN && ", "")],
        "wrong-gap-inclusive": [("= accuracyValidated - accuracyAll > gap", "= accuracyValidated - accuracyAll >= gap")],
        "wrong-unchecked-any-status": [('it.status == "valid" && !it.sumOk', "!it.sumOk")],
        "wrong-fix-unchecked-before-wasted": [('    wasted > 0 -> "stop_retrying_absent"\n    unchecked > 0 -> "add_semantic_checks"\n',
                                               '    unchecked > 0 -> "add_semantic_checks"\n    wasted > 0 -> "stop_retrying_absent"\n')],
        "wrong-rounding-floor": [("(200 * correct + total) / (2 * total)", "100 * correct / total")],
        "wrong-empty-meets-target": [("= n > 0 && right * 100 >= target * n", "= right * 100 >= target * n")],
    }),
}
