# Planted wrong solutions of module 76-scenario-conversational-ai-assistant: exact replacements against the practice's reference (see tools/make_plants.py).
# Runs with PLANTS, X and both() in scope; names defined here are local to this file.

PLANTS[f"{X}/76-scenario-conversational-ai-assistant/unit-01/practice-1"] = {
    "python": ("conversation_review.py", {
        "wrong-safety-any-hand-off": [('c["risk"] and c["handoff"] != "safety"', 'c["risk"] and c["handoff"] == "none"')],
        "wrong-safety-never-holds": [('    if safety_missed:\n        return "hold", "safety"\n', "")],
        "wrong-overlong-inclusive": [('c["turns"] > max_turns', 'c["turns"] >= max_turns')],
        "wrong-repeat-strict": [("return repeated * 100 <= max_repeat * n", "return repeated * 100 < max_repeat * n or n == 0")],
        "wrong-weak-inclusive": [('done * 100 < policy["min_resolved"] * len(group)', 'done * 100 <= policy["min_resolved"] * len(group)')],
        "wrong-floor-too-low": [('done * 100 < policy["min_resolved"] * len(group)', 'done * 100 < (policy["min_resolved"] - 10) * len(group)')],
        "wrong-weak-ignores-min-n": [('len(group) >= policy["min_n"] and ', "")],
        "wrong-min-n-strict": [('len(group) >= policy["min_n"]', 'len(group) > policy["min_n"]')],
        "wrong-over-escalated-counts-risk": [('c["handoff"] != "none" and not c["needed_person"] and not c["risk"]', 'c["handoff"] != "none" and not c["needed_person"]')],
        "wrong-resolved-ignores-hand-off": [('return c["resolved"] and c["handoff"] == "none"', 'return c["resolved"]')],
        "wrong-resolved-pct-floor": [('"resolved_pct": percent(resolved, n)', '"resolved_pct": 100 * resolved // n if n else 0')],
        "wrong-empty-ships": [('return "hold", "no_data"', 'return "ship", "none"')],
    }),
    "typescript": ("conversationReview.ts", {
        "wrong-safety-any-hand-off": [('c.risk && c.handoff !== "safety"', 'c.risk && c.handoff === "none"')],
        "wrong-safety-never-holds": [('  if (safetyMissed) return ["hold", "safety"];\n', "")],
        "wrong-overlong-inclusive": [("c.turns > maxTurns", "c.turns >= maxTurns")],
        "wrong-repeat-strict": [("return repeated * 100 <= maxRepeat * n;", "return repeated * 100 < maxRepeat * n || n === 0;")],
        "wrong-weak-inclusive": [("done * 100 < policy.min_resolved * group.length", "done * 100 <= policy.min_resolved * group.length")],
        "wrong-floor-too-low": [("done * 100 < policy.min_resolved * group.length", "done * 100 < (policy.min_resolved - 10) * group.length")],
        "wrong-weak-ignores-min-n": [("group.length >= policy.min_n && ", "")],
        "wrong-min-n-strict": [("group.length >= policy.min_n", "group.length > policy.min_n")],
        "wrong-over-escalated-counts-risk": [('c.handoff !== "none" && !c.needed_person && !c.risk', 'c.handoff !== "none" && !c.needed_person')],
        "wrong-resolved-ignores-hand-off": [('return c.resolved && c.handoff === "none";', "return c.resolved;")],
        "wrong-resolved-pct-floor": [("resolved_pct: percent(resolved, n)", "resolved_pct: n ? Math.floor((100 * resolved) / n) : 0")],
        "wrong-empty-ships": [('return ["hold", "no_data"];', 'return ["ship", "none"];')],
    }),
    "java": ("ConversationReview.java", {
        "wrong-safety-any-hand-off": [('c.risk() && !c.handoff().equals("safety")', 'c.risk() && c.handoff().equals("none")')],
        "wrong-safety-never-holds": [('        if (safetyMissed > 0) return new String[] {"hold", "safety"};\n', "")],
        "wrong-overlong-inclusive": [("c.turns() > maxTurns", "c.turns() >= maxTurns")],
        "wrong-repeat-strict": [("return repeated * 100 <= maxRepeat * n;", "return repeated * 100 < maxRepeat * n || n == 0;")],
        "wrong-weak-inclusive": [("done * 100 < policy.minResolved() * group.size()", "done * 100 <= policy.minResolved() * group.size()")],
        "wrong-floor-too-low": [("done * 100 < policy.minResolved() * group.size()", "done * 100 < (policy.minResolved() - 10) * group.size()")],
        "wrong-weak-ignores-min-n": [("group.size() >= policy.minN() && ", "")],
        "wrong-min-n-strict": [("group.size() >= policy.minN()", "group.size() > policy.minN()")],
        "wrong-over-escalated-counts-risk": [("!c.neededPerson() && !c.risk()", "!c.neededPerson()")],
        "wrong-resolved-ignores-hand-off": [('return c.resolved() && c.handoff().equals("none");', "return c.resolved();")],
        "wrong-resolved-pct-floor": [("percent(resolved, n), safetyMissed,", "n > 0 ? 100 * resolved / n : 0, safetyMissed,")],
        "wrong-empty-ships": [('return new String[] {"hold", "no_data"};', 'return new String[] {"ship", "none"};')],
    }),
    "kotlin": ("ConversationReview.kt", {
        "wrong-safety-any-hand-off": [('it.risk && it.handoff != "safety"', 'it.risk && it.handoff == "none"')],
        "wrong-safety-never-holds": [('    safetyMissed > 0 -> Pair("hold", "safety")\n', "")],
        "wrong-overlong-inclusive": [("it.turns > maxTurns", "it.turns >= maxTurns")],
        "wrong-repeat-strict": [("= repeated * 100 <= maxRepeat * n", "= repeated * 100 < maxRepeat * n || n == 0")],
        "wrong-weak-inclusive": [("done * 100 < policy.minResolved * group.size", "done * 100 <= policy.minResolved * group.size")],
        "wrong-floor-too-low": [("done * 100 < policy.minResolved * group.size", "done * 100 < (policy.minResolved - 10) * group.size")],
        "wrong-weak-ignores-min-n": [("group.size >= policy.minN && ", "")],
        "wrong-min-n-strict": [("group.size >= policy.minN", "group.size > policy.minN")],
        "wrong-over-escalated-counts-risk": [("!it.neededPerson && !it.risk }", "!it.neededPerson }")],
        "wrong-resolved-ignores-hand-off": [('= c.resolved && c.handoff == "none"', "= c.resolved")],
        "wrong-resolved-pct-floor": [("percent(resolved, n), safetyMissed,", "(if (n > 0) 100 * resolved / n else 0), safetyMissed,")],
        "wrong-empty-ships": [('n == 0 -> Pair("hold", "no_data")', 'n == 0 -> Pair("ship", "none")')],
    }),
}
