# Planted wrong solutions of module 77-scenario-agentic-tool-builder: exact replacements against the practice's reference (see tools/make_plants.py).
# Runs with PLANTS, X and both() in scope; names defined here are local to this file.

PLANTS[f"{X}/77-scenario-agentic-tool-builder/unit-01/practice-1"] = {
    "python": ("tool_review.py", {
        "wrong-description-inclusive": [('< policy["min_words"]', '<= policy["min_words"]')],
        "wrong-timeout-inclusive": [('proposal["timeout_s"] > policy["max_timeout"]', 'proposal["timeout_s"] >= policy["max_timeout"]')],
        "wrong-memory-inclusive": [('proposal["memory_mb"] > policy["max_memory"]', 'proposal["memory_mb"] >= policy["max_memory"]')],
        "wrong-name-too-long": [("{2,63}", "{2,62}")],
        "wrong-forbidden-first-only": [("return sorted(token for token in FORBIDDEN if token in code)", "return sorted(token for token in FORBIDDEN if token in code)[:1]")],
        "wrong-undeclared-ignored": [('    refusals += [f"undeclared:{p}" for p in used if p not in declared]\n', "")],
        "wrong-denied-ignored": [('    refusals += [f"denied:{p}" for p in sorted(set(declared) & set(denied))]\n', "")],
        "wrong-gate-skipped": [("return any(p in approval for p in declared)", "return False")],
        "wrong-revise-before-refuse": [('    if refusals:\n        return "refuse"\n    if findings:\n        return "revise"\n', '    if findings:\n        return "revise"\n    if refusals:\n        return "refuse"\n')],
        "wrong-used-unsorted": [("return sorted(perm for perm, markers in MARKERS.items() if any(m in code for m in markers))", "return [perm for perm, markers in MARKERS.items() if any(m in code for m in markers)]")],
    }),
    "typescript": ("toolReview.ts", {
        "wrong-description-inclusive": [(".length < policy.min_words", ".length <= policy.min_words")],
        "wrong-timeout-inclusive": [("proposal.timeout_s > policy.max_timeout", "proposal.timeout_s >= policy.max_timeout")],
        "wrong-memory-inclusive": [("proposal.memory_mb > policy.max_memory", "proposal.memory_mb >= policy.max_memory")],
        "wrong-name-too-long": [("{2,63}", "{2,62}")],
        "wrong-forbidden-first-only": [("return FORBIDDEN.filter((token) => code.includes(token)).sort();", "return FORBIDDEN.filter((token) => code.includes(token)).sort().slice(0, 1);")],
        "wrong-undeclared-ignored": [("  refusals.push(...used.filter((p) => !declared.includes(p)).map((p) => `undeclared:${p}`));\n", "")],
        "wrong-denied-ignored": [("  refusals.push(...[...new Set(declared)].filter((p) => denied.includes(p)).sort().map((p) => `denied:${p}`));\n", "")],
        "wrong-gate-skipped": [("return declared.some((p) => approval.includes(p));", "return false;")],
        "wrong-revise-before-refuse": [('  if (refusals.length > 0) return "refuse";\n  if (findings.length > 0) return "revise";\n', '  if (findings.length > 0) return "revise";\n  if (refusals.length > 0) return "refuse";\n')],
        "wrong-used-unsorted": [(".map(([perm]) => perm).sort();", ".map(([perm]) => perm);")],
    }),
    "java": ("ToolReview.java", {
        "wrong-description-inclusive": [(".length < policy.minWords()", ".length <= policy.minWords()")],
        "wrong-timeout-inclusive": [("proposal.timeoutS() > policy.maxTimeout()", "proposal.timeoutS() >= policy.maxTimeout()")],
        "wrong-memory-inclusive": [("proposal.memoryMb() > policy.maxMemory()", "proposal.memoryMb() >= policy.maxMemory()")],
        "wrong-name-too-long": [("{2,63}", "{2,62}")],
        "wrong-forbidden-first-only": [("return new TreeSet<>(FORBIDDEN.stream().filter(code::contains).toList()).stream().toList();", "return new TreeSet<>(FORBIDDEN.stream().filter(code::contains).toList()).stream().limit(1).toList();")],
        "wrong-undeclared-ignored": [('        used.stream().filter(p -> !declared.contains(p)).forEach(p -> refusals.add("undeclared:" + p));\n', "")],
        "wrong-denied-ignored": [('        new TreeSet<>(declared).stream().filter(denied::contains).forEach(p -> refusals.add("denied:" + p));\n', "")],
        "wrong-gate-skipped": [("return declared.stream().anyMatch(approval::contains);", "return false;")],
        "wrong-revise-before-refuse": [('        if (!refusals.isEmpty()) return "refuse";\n        if (!findings.isEmpty()) return "revise";\n', '        if (!findings.isEmpty()) return "revise";\n        if (!refusals.isEmpty()) return "refuse";\n')],
        "wrong-used-unsorted": [("return new TreeSet<>(MARKERS.entrySet().stream().filter(e -> e.getValue().stream().anyMatch(code::contains)).map(Map.Entry::getKey).toList()).stream().toList();",
                                 "return MARKERS.entrySet().stream().filter(e -> e.getValue().stream().anyMatch(code::contains)).map(Map.Entry::getKey).toList();")],
    }),
    "kotlin": ("ToolReview.kt", {
        "wrong-description-inclusive": [(".size < policy.minWords", ".size <= policy.minWords")],
        "wrong-timeout-inclusive": [("proposal.timeoutS > policy.maxTimeout", "proposal.timeoutS >= policy.maxTimeout")],
        "wrong-memory-inclusive": [("proposal.memoryMb > policy.maxMemory", "proposal.memoryMb >= policy.maxMemory")],
        "wrong-name-too-long": [("{2,63}", "{2,62}")],
        "wrong-forbidden-first-only": [("FORBIDDEN.filter { it in code }.sorted()", "FORBIDDEN.filter { it in code }.sorted().take(1)")],
        "wrong-undeclared-ignored": [('    refusals += used.filter { it !in declared }.map { "undeclared:$it" }\n', "")],
        "wrong-denied-ignored": [('    refusals += declared.toSortedSet().filter { it in denied }.map { "denied:$it" }\n', "")],
        "wrong-gate-skipped": [("= declared.any { it in approval }", "= false")],
        "wrong-revise-before-refuse": [('    refusals.isNotEmpty() -> "refuse"\n    findings.isNotEmpty() -> "revise"\n', '    findings.isNotEmpty() -> "revise"\n    refusals.isNotEmpty() -> "refuse"\n')],
        "wrong-used-unsorted": [("}.keys.sorted()", "}.keys.toList()")],
    }),
}
