# Planted wrong solutions of module 77-scenario-agentic-tool-builder: exact replacements against the practice's reference (see tools/make_plants.py).
# Runs with PLANTS, X and both() in scope; names defined here are local to this file.

PLANTS[f"{X}/77-scenario-agentic-tool-builder/unit-01/practice-1"] = {
    "python": ("tool_review.py", {
        "wrong-description-inclusive": [('< policy["min_words"]', '<= policy["min_words"]')],
        "wrong-timeout-inclusive": [('> policy["max_timeout"]', '>= policy["max_timeout"]')],
        "wrong-memory-inclusive": [('> policy["max_memory"]', '>= policy["max_memory"]')],
        "wrong-name-too-long": [("{2,63}", "{2,62}")],
        "wrong-forbidden-first-only": [("forbidden = sorted(token for token in FORBIDDEN if token in code)", "forbidden = sorted(token for token in FORBIDDEN if token in code)[:1]")],
        "wrong-undeclared-ignored": [('    refusals += [f"undeclared:{p}" for p in used if p not in declared]\n', "")],
        "wrong-denied-ignored": [('    refusals += [f"denied:{p}" for p in sorted(set(declared) & set(policy["denied"]))]\n', "")],
        "wrong-gate-skipped": [('gated = any(p in policy["approval"] for p in declared)', "gated = False")],
        "wrong-revise-before-refuse": [('    if refusals:\n        decision = "refuse"\n    elif findings:\n        decision = "revise"\n', '    if findings:\n        decision = "revise"\n    elif refusals:\n        decision = "refuse"\n')],
        "wrong-used-unsorted": [("used = sorted(perm for perm, markers in MARKERS.items() if any(m in code for m in markers))", "used = [perm for perm, markers in MARKERS.items() if any(m in code for m in markers)]")],
    }),
    "typescript": ("toolReview.ts", {
        "wrong-description-inclusive": [("< policy.min_words", "<= policy.min_words")],
        "wrong-timeout-inclusive": [("> policy.max_timeout", ">= policy.max_timeout")],
        "wrong-memory-inclusive": [("> policy.max_memory", ">= policy.max_memory")],
        "wrong-name-too-long": [("{2,63}", "{2,62}")],
        "wrong-forbidden-first-only": [(".filter((token) => code.includes(token)).sort();", ".filter((token) => code.includes(token)).sort().slice(0, 1);")],
        "wrong-undeclared-ignored": [("  refusals.push(...used.filter((p) => !declared.includes(p)).map((p) => `undeclared:${p}`));\n", "")],
        "wrong-denied-ignored": [("  refusals.push(...[...new Set(declared)].filter((p) => policy.denied.includes(p)).sort().map((p) => `denied:${p}`));\n", "")],
        "wrong-gate-skipped": [("const gated = declared.some((p) => policy.approval.includes(p));", "const gated = false;")],
        "wrong-revise-before-refuse": [('  if (refusals.length > 0) decision = "refuse";\n  else if (findings.length > 0) decision = "revise";\n', '  if (findings.length > 0) decision = "revise";\n  else if (refusals.length > 0) decision = "refuse";\n')],
        "wrong-used-unsorted": [(".map(([perm]) => perm).sort();", ".map(([perm]) => perm);")],
    }),
    "java": ("ToolReview.java", {
        "wrong-description-inclusive": [("< policy.minWords()", "<= policy.minWords()")],
        "wrong-timeout-inclusive": [("> policy.maxTimeout()", ">= policy.maxTimeout()")],
        "wrong-memory-inclusive": [("> policy.maxMemory()", ">= policy.maxMemory()")],
        "wrong-name-too-long": [("{2,63}", "{2,62}")],
        "wrong-forbidden-first-only": [("FORBIDDEN.stream().filter(code::contains).toList()).stream().toList();", "FORBIDDEN.stream().filter(code::contains).toList()).stream().limit(1).toList();")],
        "wrong-undeclared-ignored": [('        used.stream().filter(p -> !declared.contains(p)).forEach(p -> refusals.add("undeclared:" + p));\n', "")],
        "wrong-denied-ignored": [('        new TreeSet<>(declared).stream().filter(policy.denied()::contains).forEach(p -> refusals.add("denied:" + p));\n', "")],
        "wrong-gate-skipped": [("boolean gated = declared.stream().anyMatch(policy.approval()::contains);", "boolean gated = false;")],
        "wrong-revise-before-refuse": [('        if (!refusals.isEmpty()) decision = "refuse";\n        else if (!findings.isEmpty()) decision = "revise";\n', '        if (!findings.isEmpty()) decision = "revise";\n        else if (!refusals.isEmpty()) decision = "refuse";\n')],
        "wrong-used-unsorted": [("List<String> used = new TreeSet<>(MARKERS.entrySet().stream().filter(e -> e.getValue().stream().anyMatch(code::contains)).map(Map.Entry::getKey).toList()).stream().toList();",
                                 "List<String> used = MARKERS.entrySet().stream().filter(e -> e.getValue().stream().anyMatch(code::contains)).map(Map.Entry::getKey).toList();")],
    }),
    "kotlin": ("ToolReview.kt", {
        "wrong-description-inclusive": [("< policy.minWords", "<= policy.minWords")],
        "wrong-timeout-inclusive": [("> policy.maxTimeout", ">= policy.maxTimeout")],
        "wrong-memory-inclusive": [("> policy.maxMemory", ">= policy.maxMemory")],
        "wrong-name-too-long": [("{2,63}", "{2,62}")],
        "wrong-forbidden-first-only": [("FORBIDDEN.filter { it in code }.sorted()", "FORBIDDEN.filter { it in code }.sorted().take(1)")],
        "wrong-undeclared-ignored": [('    refusals += used.filter { it !in declared }.map { "undeclared:$it" }\n', "")],
        "wrong-denied-ignored": [('    refusals += declared.toSortedSet().filter { it in policy.denied }.map { "denied:$it" }\n', "")],
        "wrong-gate-skipped": [("val gated = declared.any { it in policy.approval }", "val gated = false")],
        "wrong-revise-before-refuse": [('        refusals.isNotEmpty() -> "refuse"\n        findings.isNotEmpty() -> "revise"\n', '        findings.isNotEmpty() -> "revise"\n        refusals.isNotEmpty() -> "refuse"\n')],
        "wrong-used-unsorted": [("markers.any { it in code } }.keys.sorted()", "markers.any { it in code } }.keys.toList()")],
    }),
}
