# Planted wrong solutions of module 80-end-to-end-and-multi-agent-architecture: exact replacements against the practice's reference (see tools/make_plants.py).
# Runs with PLANTS, X and both() in scope; names defined here are local to this file.

PLANTS[f"{X}/80-end-to-end-and-multi-agent-architecture/unit-01/practice-1"] = {
    "python": ("architecture_review.py", {
        "wrong-no-feedback-check": [('    if _empty(stages.get("feedback")):', "    if False:")],
        "wrong-input-stage-skipped": [('    for stage in ("input", "processing", "output"):', '    for stage in ("processing", "output"):')],
        "wrong-autonomy-always": [('    if design.get("pattern") in AUTONOMOUS and design.get("path_known"):', '    if design.get("pattern") in AUTONOMOUS:')],
        "wrong-team-shared-only": [(' and (design.get("shared_context") or not design.get("parallel_independent")):', ' and design.get("shared_context"):')],
        "wrong-team-single-agent": [('design.get("agents", 1) > 1', 'design.get("agents", 1) >= 1')],
        "wrong-write-without-audit": [('    if design.get("writes_without_approval") and design.get("needs_audit"):', '    if design.get("writes_without_approval"):')],
        "wrong-validate-inverted": [('"validate" not in stages["output"]', '"validate" in stages["output"]')],
        "wrong-lone-validate-ignored": [('"validate" not in stages["output"]', '"validate" not in stages["output"][:-1]')],
        "wrong-order-by-rule": [('key=lambda f: (SEVERITY_ORDER[f["severity"]], f["rule"]))', 'key=lambda f: f["rule"])')],
        "wrong-any-finding-rejects": [('    return "reject" if "high" in severities else "revise" if "medium" in severities else "approve"', '    return "reject" if severities else "approve"')],
        "wrong-rejected-allowed": [('    adequate = [d for d in designs if verdict(review(d)) != "reject"]', "    adequate = list(designs)")],
        "wrong-tie-by-position": [('key=lambda d: (d["cost"], d["name"])', 'key=lambda d: d["cost"]')],
    }),
    "typescript": ("architectureReview.ts", {
        "wrong-no-feedback-check": [("  if (empty(stages.feedback)) findings.push(", "  if (false) findings.push(")],
        "wrong-input-stage-skipped": [('  for (const stage of ["input", "processing", "output"]) {', '  for (const stage of ["processing", "output"]) {')],
        "wrong-autonomy-always": [("  if (AUTONOMOUS.includes(design.pattern) && design.path_known) findings", "  if (AUTONOMOUS.includes(design.pattern)) findings")],
        "wrong-team-shared-only": [('(design.shared_context || !design.parallel_independent)) findings.push({ rule: "team-without-independence"', 'design.shared_context) findings.push({ rule: "team-without-independence"')],
        "wrong-team-single-agent": [("(design.agents ?? 1) > 1", "(design.agents ?? 1) >= 1")],
        "wrong-write-without-audit": [("  if (design.writes_without_approval && design.needs_audit) findings", "  if (design.writes_without_approval) findings")],
        "wrong-validate-inverted": [('!stages.output.includes("validate")', 'stages.output.includes("validate")')],
        "wrong-lone-validate-ignored": [('!stages.output.includes("validate")', '!stages.output.slice(0, -1).includes("validate")')],
        "wrong-order-by-rule": [("SEVERITY_ORDER[a.severity] - SEVERITY_ORDER[b.severity] || (a.rule < b.rule ? -1 : a.rule > b.rule ? 1 : 0)", "a.rule < b.rule ? -1 : a.rule > b.rule ? 1 : 0")],
        "wrong-any-finding-rejects": [('  return severities.has("high") ? "reject" : severities.has("medium") ? "revise" : "approve";', '  return severities.size > 0 ? "reject" : "approve";')],
        "wrong-rejected-allowed": [('  const adequate = designs.filter((d) => verdict(review(d)) !== "reject");', "  const adequate = designs;")],
        "wrong-tie-by-position": [("[...adequate].sort((a, b) => a.cost - b.cost || (a.name < b.name ? -1 : a.name > b.name ? 1 : 0))[0].name", "[...adequate].sort((a, b) => a.cost - b.cost)[0].name")],
    }),
    "java": ("ArchitectureReview.java", {
        "wrong-no-feedback-check": [('if (empty(stages.get("feedback"))) findings.add(finding("no-feedback", "high"));', 'if (false) findings.add(finding("no-feedback", "high"));')],
        "wrong-input-stage-skipped": [('for (String stage : List.of("input", "processing", "output")) {', 'for (String stage : List.of("processing", "output")) {')],
        "wrong-autonomy-always": [('if (AUTONOMOUS.contains(design.get("pattern")) && truthy(design.get("path_known"))) findings', 'if (AUTONOMOUS.contains(design.get("pattern"))) findings')],
        "wrong-team-shared-only": [('agents > 1 && (truthy(design.get("shared_context")) || !truthy(design.get("parallel_independent"))))', 'agents > 1 && truthy(design.get("shared_context")))')],
        "wrong-team-single-agent": [("if (agents > 1 &&", "if (agents >= 1 &&")],
        "wrong-write-without-audit": [('if (truthy(design.get("writes_without_approval")) && truthy(design.get("needs_audit"))) findings', 'if (truthy(design.get("writes_without_approval"))) findings')],
        "wrong-validate-inverted": [('!((List<?>) stages.get("output")).contains("validate")', '((List<?>) stages.get("output")).contains("validate")')],
        "wrong-lone-validate-ignored": [('!((List<?>) stages.get("output")).contains("validate")', '!((List<?>) stages.get("output")).subList(0, ((List<?>) stages.get("output")).size() - 1).contains("validate")')],
        "wrong-order-by-rule": [('Comparator.comparingInt((Map<String, Object> f) -> SEVERITY_ORDER.get((String) f.get("severity"))).thenComparing(f -> (String) f.get("rule"))', 'Comparator.comparing((Map<String, Object> f) -> (String) f.get("rule"))')],
        "wrong-any-finding-rejects": [('return severities.contains("high") ? "reject" : severities.contains("medium") ? "revise" : "approve";', 'return !severities.isEmpty() ? "reject" : "approve";')],
        "wrong-rejected-allowed": [('for (Map<String, Object> d : designs) if (!verdict(review(d)).equals("reject")) adequate.add(d);', "for (Map<String, Object> d : designs) adequate.add(d);")],
        "wrong-tie-by-position": [('.thenComparing(d -> (String) d.get("name")));', ");")],
    }),
    "kotlin": ("ArchitectureReview.kt", {
        "wrong-no-feedback-check": [('if (empty(stages["feedback"])) findings += finding("no-feedback", "high")', 'if (false) findings += finding("no-feedback", "high")')],
        "wrong-input-stage-skipped": [('for (stage in listOf("input", "processing", "output")) {', 'for (stage in listOf("processing", "output")) {')],
        "wrong-autonomy-always": [('if (design["pattern"] in AUTONOMOUS && truthy(design["path_known"])) findings', 'if (design["pattern"] in AUTONOMOUS) findings')],
        "wrong-team-shared-only": [('agents > 1 && (truthy(design["shared_context"]) || !truthy(design["parallel_independent"])))', 'agents > 1 && truthy(design["shared_context"]))')],
        "wrong-team-single-agent": [("if (agents > 1 &&", "if (agents >= 1 &&")],
        "wrong-write-without-audit": [('if (truthy(design["writes_without_approval"]) && truthy(design["needs_audit"])) findings', 'if (truthy(design["writes_without_approval"])) findings')],
        "wrong-validate-inverted": [('!(stages["output"] as List<*>).contains("validate")', '(stages["output"] as List<*>).contains("validate")')],
        "wrong-lone-validate-ignored": [('!(stages["output"] as List<*>).contains("validate")', '!(stages["output"] as List<*>).dropLast(1).contains("validate")')],
        "wrong-order-by-rule": [('compareBy({ SEVERITY_ORDER.getValue(it["severity"] as String) }, { it["rule"] as String })', 'compareBy<Map<String, Any?>> { it["rule"] as String }')],
        "wrong-any-finding-rejects": [('return if ("high" in severities) "reject" else if ("medium" in severities) "revise" else "approve"', 'return if (severities.isNotEmpty()) "reject" else "approve"')],
        "wrong-rejected-allowed": [('val adequate = designs.filter { verdict(review(it)!!) != "reject" }', "val adequate = designs")],
        "wrong-tie-by-position": [('compareBy({ it["cost"] as Int }, { it["name"] as String })', 'compareBy<Map<String, Any?>> { it["cost"] as Int }')],
    }),
}
