# Planted wrong solutions of module 80-end-to-end-and-multi-agent-architecture: exact replacements against the practice's reference (see tools/make_plants.py).
# Runs with PLANTS, X and both() in scope; names defined here are local to this file.

PLANTS[f"{X}/80-end-to-end-and-multi-agent-architecture/unit-01/practice-1"] = {
    "python": ("architecture_review.py", {
        "wrong-no-feedback-check": [('    if _empty(stages.get("feedback")):\n        found.append(finding("no-feedback", "high"))\n', "")],
        "wrong-input-stage-skipped": [('("input", "processing", "output")', '("processing", "output")')],
        "wrong-autonomy-always": [('design.get("pattern") in AUTONOMOUS and design.get("path_known")', 'design.get("pattern") in AUTONOMOUS')],
        "wrong-autonomy-agent-only": [('design.get("pattern") in AUTONOMOUS and', 'design.get("pattern") == "agent" and')],
        "wrong-team-shared-only": [('(design.get("shared_context") or not design.get("parallel_independent"))', 'design.get("shared_context")')],
        "wrong-team-single-agent": [('design.get("agents", 1) > 1 and ', "")],
        "wrong-write-without-audit": [('design.get("writes_without_approval") and design.get("needs_audit")', 'design.get("writes_without_approval")')],
        "wrong-validate-inverted": [('"validate" not in stages["output"]', '"validate" in stages["output"]')],
        "wrong-lone-validate-ignored": [('"validate" not in stages["output"]', '"validate" not in stages["output"][:-1]')],
        "wrong-order-by-rule": [('key=lambda f: (SEVERITY_ORDER[f["severity"]], f["rule"])', 'key=lambda f: f["rule"]')],
        "wrong-medium-approves": [('"reject" if "high" in severities else "revise" if "medium" in severities else "approve"', '"reject" if "high" in severities else "approve"')],
        "wrong-any-finding-rejects": [('"reject" if "high" in severities else "revise" if "medium" in severities else "approve"', '"reject" if severities else "approve"')],
        "wrong-rejected-allowed": [('adequate = [d for d in designs if verdict(review(d)) != "reject"]', "adequate = list(designs)")],
        "wrong-tie-by-position": [('min(adequate, key=lambda d: (d["cost"], d["name"]))', 'min(adequate, key=lambda d: d["cost"])')],
    }),
    "typescript": ("architectureReview.ts", {
        "wrong-no-feedback-check": [('  if (empty(stages.feedback)) found.push(finding("no-feedback", "high"));\n', "")],
        "wrong-input-stage-skipped": [('["input", "processing", "output"].filter', '["processing", "output"].filter')],
        "wrong-autonomy-always": [("AUTONOMOUS.includes(design.pattern) && design.path_known ?", "AUTONOMOUS.includes(design.pattern) ?")],
        "wrong-autonomy-agent-only": [("AUTONOMOUS.includes(design.pattern) && design.path_known", 'design.pattern === "agent" && design.path_known')],
        "wrong-team-shared-only": [("(design.shared_context || !design.parallel_independent)", "design.shared_context")],
        "wrong-team-single-agent": [("(design.agents ?? 1) > 1 && ", "")],
        "wrong-write-without-audit": [("design.writes_without_approval && design.needs_audit", "design.writes_without_approval")],
        "wrong-validate-inverted": [('!stages.output.includes("validate")', 'stages.output.includes("validate")')],
        "wrong-lone-validate-ignored": [('!stages.output.includes("validate")', '!stages.output.slice(0, -1).includes("validate")')],
        "wrong-order-by-rule": [("SEVERITY_ORDER[a.severity] - SEVERITY_ORDER[b.severity] || ", "")],
        "wrong-medium-approves": [('severities.has("high") ? "reject" : severities.has("medium") ? "revise" : "approve"', 'severities.has("high") ? "reject" : "approve"')],
        "wrong-any-finding-rejects": [('severities.has("high") ? "reject" : severities.has("medium") ? "revise" : "approve"', 'severities.size > 0 ? "reject" : "approve"')],
        "wrong-rejected-allowed": [('const adequate = designs.filter((d) => verdict(review(d)) !== "reject");', "const adequate = [...designs];")],
        "wrong-tie-by-position": [("a.cost - b.cost || (a.name < b.name ? -1 : a.name > b.name ? 1 : 0))[0]", "a.cost - b.cost)[0]")],
    }),
    "java": ("ArchitectureReview.java", {
        "wrong-no-feedback-check": [('        if (empty(stages.get("feedback"))) found.add(finding("no-feedback", "high"));\n', "")],
        "wrong-input-stage-skipped": [('List.of("input", "processing", "output")', 'List.of("processing", "output")')],
        "wrong-autonomy-always": [('AUTONOMOUS.contains(design.get("pattern")) && truthy(design.get("path_known")) ?', 'AUTONOMOUS.contains(design.get("pattern")) ?')],
        "wrong-autonomy-agent-only": [('AUTONOMOUS.contains(design.get("pattern")) && truthy(', '"agent".equals(design.get("pattern")) && truthy(')],
        "wrong-team-shared-only": [('(truthy(design.get("shared_context")) || !truthy(design.get("parallel_independent")))', 'truthy(design.get("shared_context"))')],
        "wrong-team-single-agent": [("agents > 1 && ", "")],
        "wrong-write-without-audit": [('truthy(design.get("writes_without_approval")) && truthy(design.get("needs_audit"))', 'truthy(design.get("writes_without_approval"))')],
        "wrong-validate-inverted": [('!((List<?>) stages.get("output")).contains("validate")', '((List<?>) stages.get("output")).contains("validate")')],
        "wrong-lone-validate-ignored": [('!((List<?>) stages.get("output")).contains("validate")', '!((List<?>) stages.get("output")).subList(0, ((List<?>) stages.get("output")).size() - 1).contains("validate")')],
        "wrong-order-by-rule": [('Comparator.comparingInt((Map<String, Object> f) -> SEVERITY_ORDER.get((String) f.get("severity"))).thenComparing(f -> (String) f.get("rule"))', 'Comparator.comparing((Map<String, Object> f) -> (String) f.get("rule"))')],
        "wrong-medium-approves": [('severities.contains("high") ? "reject" : severities.contains("medium") ? "revise" : "approve"', 'severities.contains("high") ? "reject" : "approve"')],
        "wrong-any-finding-rejects": [('severities.contains("high") ? "reject" : severities.contains("medium") ? "revise" : "approve"', '!severities.isEmpty() ? "reject" : "approve"')],
        "wrong-rejected-allowed": [('for (Map<String, Object> d : designs) if (!verdict(review(d)).equals("reject")) adequate.add(d);', "adequate.addAll(designs);")],
        "wrong-tie-by-position": [('(Integer) d.get("cost")).thenComparing(d -> (String) d.get("name")));', '(Integer) d.get("cost")));')],
    }),
    "kotlin": ("ArchitectureReview.kt", {
        "wrong-no-feedback-check": [('    if (empty(stages["feedback"])) found += finding("no-feedback", "high")\n', "")],
        "wrong-input-stage-skipped": [('listOf("input", "processing", "output")', 'listOf("processing", "output")')],
        "wrong-autonomy-always": [(' && truthy(design["path_known"])', "")],
        "wrong-autonomy-agent-only": [('design["pattern"] in AUTONOMOUS', 'design["pattern"] == "agent"')],
        "wrong-team-shared-only": [('(truthy(design["shared_context"]) || !truthy(design["parallel_independent"]))', 'truthy(design["shared_context"])')],
        "wrong-team-single-agent": [("agents > 1 && ", "")],
        "wrong-write-without-audit": [('truthy(design["writes_without_approval"]) && truthy(design["needs_audit"])', 'truthy(design["writes_without_approval"])')],
        "wrong-validate-inverted": [('!(stages["output"] as List<*>).contains("validate")', '(stages["output"] as List<*>).contains("validate")')],
        "wrong-lone-validate-ignored": [('!(stages["output"] as List<*>).contains("validate")', '!(stages["output"] as List<*>).dropLast(1).contains("validate")')],
        "wrong-order-by-rule": [('compareBy({ SEVERITY_ORDER.getValue(it["severity"] as String) }, { it["rule"] as String })', 'compareBy { it["rule"] as String }')],
        "wrong-medium-approves": [('if ("high" in severities) "reject" else if ("medium" in severities) "revise" else "approve"', 'if ("high" in severities) "reject" else "approve"')],
        "wrong-any-finding-rejects": [('if ("high" in severities) "reject" else if ("medium" in severities) "revise" else "approve"', 'if (severities.isNotEmpty()) "reject" else "approve"')],
        "wrong-rejected-allowed": [('val adequate = designs.filter { verdict(review(it)!!) != "reject" }', "val adequate = designs")],
        "wrong-tie-by-position": [('compareBy({ it["cost"] as Int }, { it["name"] as String })', 'compareBy { it["cost"] as Int }')],
    }),
}
