# Planted wrong solutions of module 81-reliability-of-multi-agent-systems: exact replacements against the practice's reference (see tools/make_plants.py).
# Runs with PLANTS, X and both() in scope; names defined here are local to this file.

PLANTS[f"{X}/81-reliability-of-multi-agent-systems/unit-01/practice-1"] = {
    "python": ("reliable_agents.py", {
        "wrong-retry-new-key": [("result = agents[agent_name](key, inputs)", 'result = agents[agent_name](f"{key}:{n}", inputs)')],
        "wrong-key-changes-late": [("result = agents[agent_name](key, inputs)", 'result = agents[agent_name](key if n < 3 else f"{key}:{n}", inputs)')],
        "wrong-fatal-retried": [('                return None, f"fatal: {error}"', "                continue")],
        "wrong-attempts-off-by-one": [("for n in range(1, attempts + 1):", "for n in range(1, attempts):")],
        "wrong-dependents-still-run": [("        missing = next((n for n in needs if n not in done), None)", "        missing = None"),
                                       ("        inputs = {n: done[n] for n in needs}", '        inputs = {n: done.get(n, "") for n in needs}')],
        "wrong-failure-stops-run": [("            failed[tid] = reason\n            continue", "            failed[tid] = reason\n            break")],
        "wrong-breaker-total": [("            consecutive[agent_name] = 0\n", "")],
        "wrong-breaker-never-opens": [("            if consecutive.get(agent_name, 0) >= breaker_threshold:", "            if False:")],
        "wrong-fallback-same-key": [('task["key"] + ":fallback"', 'task["key"]')],
        "wrong-fallback-checkpointed": [("                degraded.append(tid)", "                degraded.append(tid)\n                store[tid] = result")],
        "wrong-resume-reruns": [("        if tid in store:", "        if False:")],
        "wrong-crash-swallowed": [("            except Transient:", '            except RuntimeError as error:\n                return None, f"fatal: {error}"\n            except Transient:')],
        "wrong-checkpoint-late": [('        done[tid] = result\n        store[tid] = result\n    return {', '        done[tid] = result\n    store.update(done)\n    return {')],
    }),
    "typescript": ("reliableAgents.ts", {
        "wrong-retry-new-key": [("const result = agents[agentName](key, inputs);", 'const result = agents[agentName](key + ":" + n, inputs);')],
        "wrong-key-changes-late": [("const result = agents[agentName](key, inputs);", 'const result = agents[agentName](n < 3 ? key : key + ":" + n, inputs);')],
        "wrong-fatal-retried": [("          return [null, `fatal: ${error.message}`];", "          continue;")],
        "wrong-attempts-off-by-one": [("for (let n = 1; n <= attempts; n++) {", "for (let n = 1; n < attempts; n++) {")],
        "wrong-dependents-still-run": [("    if (missing !== undefined) {", "    if (false) {"),
                                       ("Object.fromEntries(needs.map((n) => [n, done[n]]))", 'Object.fromEntries(needs.map((n) => [n, done[n] ?? ""]))')],
        "wrong-failure-stops-run": [("      failed[tid] = reason!;\n      continue;", "      failed[tid] = reason!;\n      break;")],
        "wrong-breaker-total": [("        consecutive[agentName] = 0;\n", "")],
        "wrong-breaker-never-opens": [('if ((consecutive[agentName] ?? 0) >= breakerThreshold) return [null, "circuit open"];', 'if (false) return [null, "circuit open"];')],
        "wrong-fallback-same-key": [('task.key + ":fallback"', "task.key")],
        "wrong-fallback-checkpointed": [("        degraded.push(tid);", "        degraded.push(tid);\n        store[tid] = result;")],
        "wrong-resume-reruns": [("    if (tid in store) {", "    if (false) {")],
        "wrong-crash-swallowed": [("        if (error instanceof Transient) {", '        if (error instanceof Error && error.message === "process died") return [null, "fatal: process died"];\n        if (error instanceof Transient) {')],
        "wrong-checkpoint-late": [("    done[tid] = result;\n    store[tid] = result;\n  }\n  return {", "    done[tid] = result;\n  }\n  Object.assign(store, done);\n  return {")],
    }),
    "java": ("ReliableAgents.java", {
        "wrong-retry-new-key": [("agents.get(agentName).call(key, inputs)", 'agents.get(agentName).call(key + ":" + n, inputs)')],
        "wrong-key-changes-late": [("agents.get(agentName).call(key, inputs)", 'agents.get(agentName).call(n < 3 ? key : key + ":" + n, inputs)')],
        "wrong-fatal-retried": [('                    return new Outcome(null, "fatal: " + e.getMessage());', "                    continue;")],
        "wrong-attempts-off-by-one": [("for (int n = 1; n <= attempts; n++) {", "for (int n = 1; n < attempts; n++) {")],
        "wrong-dependents-still-run": [("            if (missing != null) {", "            if (false) {")],
        "wrong-failure-stops-run": [("                failed.put(tid, outcome.reason());\n                continue;", "                failed.put(tid, outcome.reason());\n                break;")],
        "wrong-breaker-total": [("                    consecutive.put(agentName, 0);\n", "")],
        "wrong-breaker-never-opens": [('if (consecutive.getOrDefault(agentName, 0) >= breakerThreshold) return new Outcome(null, "circuit open");', 'if (false) return new Outcome(null, "circuit open");')],
        "wrong-fallback-same-key": [('task.get("key") + ":fallback"', 'task.get("key")')],
        "wrong-fallback-checkpointed": [("                    degraded.add(tid);", "                    degraded.add(tid);\n                    store.put(tid, second.result());")],
        "wrong-resume-reruns": [("            if (store.containsKey(tid)) {", "            if (false) {")],
        "wrong-crash-swallowed": [("                } catch (Transient e) {", '                } catch (IllegalStateException e) {\n                    return new Outcome(null, "fatal: " + e.getMessage());\n                } catch (Transient e) {')],
        "wrong-checkpoint-late": [("            store.put(tid, outcome.result());\n", ""), ("        Map<String, Object> out = new LinkedHashMap<>();", "        store.putAll(done);\n        Map<String, Object> out = new LinkedHashMap<>();")],
    }),
    "kotlin": ("ReliableAgents.kt", {
        "wrong-retry-new-key": [("agents.getValue(agentName)(key, inputs)", 'agents.getValue(agentName)(key + ":" + n, inputs)')],
        "wrong-key-changes-late": [("agents.getValue(agentName)(key, inputs)", 'agents.getValue(agentName)(if (n < 3) key else key + ":" + n, inputs)')],
        "wrong-fatal-retried": [('                return null to "fatal: ${e.message}"', "                continue")],
        "wrong-attempts-off-by-one": [("for (n in 1..attempts) {", "for (n in 1 until attempts) {")],
        "wrong-dependents-still-run": [("        if (missing != null) {", "        if (false) {"), ("needs.associateWith { done.getValue(it) }", 'needs.associateWith { done[it] ?: "" }')],
        "wrong-failure-stops-run": [("            failed[tid] = reason!!\n            continue", "            failed[tid] = reason!!\n            break")],
        "wrong-breaker-total": [("                consecutive[agentName] = 0\n", "")],
        "wrong-breaker-never-opens": [('if ((consecutive[agentName] ?: 0) >= breakerThreshold) return null to "circuit open"', 'if (false) return null to "circuit open"')],
        "wrong-fallback-same-key": [('task["key"].toString() + ":fallback"', 'task["key"].toString()')],
        "wrong-fallback-checkpointed": [("                degraded += tid", "                degraded += tid\n                store[tid] = result")],
        "wrong-resume-reruns": [("        if (tid in store) {", "        if (false) {")],
        "wrong-crash-swallowed": [("            } catch (e: Transient) {", '            } catch (e: IllegalStateException) {\n                return null to "fatal: ${e.message}"\n            } catch (e: Transient) {')],
        "wrong-checkpoint-late": [("        store[tid] = result\n", ""), ('    return linkedMapOf("done" to done,', '    store.putAll(done)\n    return linkedMapOf("done" to done,')],
    }),
}
