# Planted wrong solutions of module 82-models-prompts-and-context-as-design-choices: exact replacements against the practice's reference (see tools/make_plants.py).
# Runs with PLANTS, X and both() in scope; names defined here are local to this file.

PLANTS[f"{X}/82-models-prompts-and-context-as-design-choices/unit-01/practice-1"] = {
    "python": ("prompt_plan.py", {
        "wrong-static-reversed": [('blocks = [{"name": m["name"], "text": m["text"]} for m in static]', 'blocks = [{"name": m["name"], "text": m["text"]} for m in reversed(static)]')],
        "wrong-breakpoint-after-all": [("breakpoint_of(len(static), prefix)", "breakpoint_of(len(static) + len(kept), prefix)")],
        "wrong-variable-in-static-allowed": [('if re.search(r"\\{\\w+\\}", m["text"]):', "if False:")],
        "wrong-missing-variable-blank": [('        if name not in variables:\n            raise ValueError(f"missing variable: {name}")\n        return str(variables[name])\n', '        return str(variables.get(name, ""))\n')],
        "wrong-drop-highest-priority": [('key=lambda i: (kept[i]["priority"], -i)', 'key=lambda i: (-kept[i]["priority"], -i)')],
        "wrong-drop-tie-earlier": [('key=lambda i: (kept[i]["priority"], -i)', 'key=lambda i: (kept[i]["priority"], i)')],
        "wrong-over-budget-ignored": [('        if not kept:\n            raise ValueError("over budget: the static modules alone exceed it")\n', "        if not kept:\n            break\n")],
        "wrong-minimum-exclusive": [("prefix >= MIN_CACHEABLE", "prefix > MIN_CACHEABLE")],
        "wrong-minimum-one-low": [("prefix >= MIN_CACHEABLE", "prefix >= MIN_CACHEABLE - 1")],
        "wrong-model-tier-ignored": [('m["tier"] >= workload["tier"] and ', "")],
        "wrong-model-latency-ignored": [(' and m["latency_ms"] <= workload["max_latency_ms"]', "")],
        "wrong-model-tie-by-position": [('key=lambda m: (m["price_out"], m["name"])', 'key=lambda m: m["price_out"]')],
        "wrong-reuse-first-block-only": [('same = all(a["blocks"][i] == b["blocks"][i] for i in range(ia + 1))', 'same = a["blocks"][0] == b["blocks"][0]')],
        "wrong-reuse-needs-whole-prompt": [('same = all(a["blocks"][i] == b["blocks"][i] for i in range(ia + 1))', 'same = a["blocks"] == b["blocks"]')],
    }),
    "typescript": ("promptPlan.ts", {
        "wrong-static-reversed": [("const blocks = stat.map((m) => ({ name: m.name, text: m.text }));", "const blocks = [...stat].reverse().map((m) => ({ name: m.name, text: m.text }));")],
        "wrong-breakpoint-after-all": [("breakpointOf(stat.length, prefix)", "breakpointOf(stat.length + kept.length, prefix)")],
        "wrong-variable-in-static-allowed": [("    if (/\\{\\w+\\}/.test(m.text)) throw", "    if (false) throw")],
        "wrong-missing-variable-blank": [("    if (!(name in variables)) throw new Error(`missing variable: ${name}`);\n    return String(variables[name]);\n", '    return String(variables[name] ?? "");\n')],
        "wrong-drop-highest-priority": [("if (k.priority < kept[victim].priority ||", "if (k.priority > kept[victim].priority ||")],
        "wrong-drop-tie-earlier": [("(k.priority === kept[victim].priority && i > victim)", "(k.priority === kept[victim].priority && i < victim)")],
        "wrong-over-budget-ignored": [('if (kept.length === 0) throw new Error("over budget: the static modules alone exceed it");', "if (kept.length === 0) break;")],
        "wrong-minimum-exclusive": [("prefix >= MIN_CACHEABLE ?", "prefix > MIN_CACHEABLE ?")],
        "wrong-minimum-one-low": [("prefix >= MIN_CACHEABLE ?", "prefix >= MIN_CACHEABLE - 1 ?")],
        "wrong-model-tier-ignored": [("m.tier >= workload.tier && ", "")],
        "wrong-model-latency-ignored": [(" && m.latency_ms <= workload.max_latency_ms", "")],
        "wrong-model-tie-by-position": [("a.price_out - b.price_out || (a.name < b.name ? -1 : a.name > b.name ? 1 : 0)", "a.price_out - b.price_out")],
        "wrong-reuse-first-block-only": [("const same = a.blocks.slice(0, ia + 1).every((block: any, i: number) => block.name === b.blocks[i].name && block.text === b.blocks[i].text);", "const same = a.blocks[0].name === b.blocks[0].name && a.blocks[0].text === b.blocks[0].text;")],
        "wrong-reuse-needs-whole-prompt": [("const same = a.blocks.slice(0, ia + 1).every(", "const same = a.blocks.length === b.blocks.length && a.blocks.every(")],
    }),
    "java": ("PromptPlan.java", {
        "wrong-static-reversed": [('            blocks.add(block((String) m.get("name"), (String) m.get("text")));', '            blocks.add(0, block((String) m.get("name"), (String) m.get("text")));')],
        "wrong-breakpoint-after-all": [("breakpointOf(stat.size(), prefix)", "breakpointOf(stat.size() + kept.size(), prefix)")],
        "wrong-variable-in-static-allowed": [('if (VARIABLE.matcher((String) m.get("text")).find()) throw', "if (false) throw")],
        "wrong-missing-variable-blank": [('            if (!variables.containsKey(m.group(1))) throw new IllegalArgumentException("missing variable: " + m.group(1));\n            return Matcher.quoteReplacement(variables.get(m.group(1)));\n', '            return Matcher.quoteReplacement(variables.getOrDefault(m.group(1), ""));\n')],
        "wrong-drop-highest-priority": [('(Integer) kept.get(i).get("priority") <= (Integer) kept.get(victim).get("priority")', '(Integer) kept.get(i).get("priority") >= (Integer) kept.get(victim).get("priority")')],
        "wrong-drop-tie-earlier": [('(Integer) kept.get(i).get("priority") <= (Integer)', '(Integer) kept.get(i).get("priority") < (Integer)')],
        "wrong-over-budget-ignored": [('if (kept.isEmpty()) throw new IllegalArgumentException("over budget: the static modules alone exceed it");', "if (kept.isEmpty()) break;")],
        "wrong-minimum-exclusive": [("prefix >= MIN_CACHEABLE ?", "prefix > MIN_CACHEABLE ?")],
        "wrong-minimum-one-low": [("prefix >= MIN_CACHEABLE ?", "prefix >= MIN_CACHEABLE - 1 ?")],
        "wrong-model-tier-ignored": [('(Integer) m.get("tier") >= (Integer) workload.get("tier") && ', "")],
        "wrong-model-latency-ignored": [(' && (Integer) m.get("latency_ms") <= (Integer) workload.get("max_latency_ms")', "")],
        "wrong-model-tie-by-position": [('(Integer) m.get("price_out")).thenComparing(m -> (String) m.get("name")))', '(Integer) m.get("price_out")))')],
        "wrong-reuse-first-block-only": [("return headA.equals(headB) ?", "return headA.get(0).equals(headB.get(0)) ?")],
        "wrong-reuse-needs-whole-prompt": [("return headA.equals(headB) ?", 'return ((List<?>) a.get("blocks")).equals(b.get("blocks")) ?')],
    }),
    "kotlin": ("PromptPlan.kt", {
        "wrong-static-reversed": [('val blocks = stat.map { block(it["name"], it["text"] as String) }.toMutableList()', 'val blocks = stat.reversed().map { block(it["name"], it["text"] as String) }.toMutableList()')],
        "wrong-breakpoint-after-all": [("breakpointOf(stat.size, prefix)", "breakpointOf(stat.size + kept.size, prefix)")],
        "wrong-variable-in-static-allowed": [('require(!VARIABLE.containsMatchIn(m["text"] as String))', "require(true)")],
        "wrong-missing-variable-blank": [('?: throw IllegalArgumentException("missing variable: ${m.groupValues[1]}")', '?: ""')],
        "wrong-drop-highest-priority": [("kept[i].priority <= kept[victim].priority", "kept[i].priority >= kept[victim].priority")],
        "wrong-drop-tie-earlier": [("kept[i].priority <= kept[victim].priority", "kept[i].priority < kept[victim].priority")],
        "wrong-over-budget-ignored": [('require(kept.isNotEmpty()) { "over budget: the static modules alone exceed it" }', "if (kept.isEmpty()) break")],
        "wrong-minimum-exclusive": [("prefix >= MIN_CACHEABLE)", "prefix > MIN_CACHEABLE)")],
        "wrong-minimum-one-low": [("prefix >= MIN_CACHEABLE)", "prefix >= MIN_CACHEABLE - 1)")],
        "wrong-model-tier-ignored": [('(it["tier"] as Int) >= (workload["tier"] as Int) && ', "")],
        "wrong-model-latency-ignored": [(' && (it["latency_ms"] as Int) <= (workload["max_latency_ms"] as Int)', "")],
        "wrong-model-tie-by-position": [('compareBy({ it["price_out"] as Int }, { it["name"] as String })', 'compareBy { it["price_out"] as Int }')],
        "wrong-reuse-first-block-only": [('if (head == (b["blocks"] as List<Map<String, Any?>>).take(ia + 1))', 'if (head[0] == (b["blocks"] as List<Map<String, Any?>>)[0])')],
        "wrong-reuse-needs-whole-prompt": [('if (head == (b["blocks"] as List<Map<String, Any?>>).take(ia + 1))', 'if (a["blocks"] == b["blocks"])')],
    }),
}
