# Planted wrong solutions of module 82-models-prompts-and-context-as-design-choices: exact replacements against the practice's reference (see tools/make_plants.py).
# Runs with PLANTS, X and both() in scope; names defined here are local to this file.

PLANTS[f"{X}/82-models-prompts-and-context-as-design-choices/unit-01/practice-1"] = {
    "python": ("prompt_plan.py", {
        "wrong-static-reversed": [('    static = [m for m in modules if m["static"]]', '    static = [m for m in modules if m["static"]][::-1]')],
        "wrong-breakpoint-after-all": [("len(static) - 1 if static", "len(blocks) - 1 if static")],
        "wrong-variable-in-static-allowed": [('        if re.search(r"\\{\\w+\\}", m["text"]):', "        if False:")],
        "wrong-missing-variable-blank": [('            raise ValueError(f"missing variable: {name}")', '            return ""')],
        "wrong-drop-highest-priority": [("victim = min(range(len(kept)),", "victim = max(range(len(kept)),")],
        "wrong-drop-tie-earlier": [('key=lambda i: (kept[i]["priority"], -i))', 'key=lambda i: (kept[i]["priority"], i))')],
        "wrong-over-budget-ignored": [('            raise ValueError("over budget: the static modules alone exceed it")', "            break")],
        "wrong-minimum-exclusive": [("prefix >= MIN_CACHEABLE", "prefix > MIN_CACHEABLE")],
        "wrong-minimum-one-low": [("prefix >= MIN_CACHEABLE", "prefix >= MIN_CACHEABLE - 1")],
        "wrong-model-tier-ignored": [('m["tier"] >= workload["tier"] and ', "")],
        "wrong-model-latency-ignored": [(' and m["latency_ms"] <= workload["max_latency_ms"]]', "]")],
        "wrong-model-tie-by-position": [('key=lambda m: (m["price_out"], m["name"])', 'key=lambda m: m["price_out"]')],
        "wrong-reuse-first-block-only": [('    same = all(a["blocks"][i] == b["blocks"][i] for i in range(ia + 1))', '    same = a["blocks"][0] == b["blocks"][0]')],
        "wrong-reuse-needs-whole-prompt": [('    same = all(a["blocks"][i] == b["blocks"][i] for i in range(ia + 1))', '    same = a["blocks"] == b["blocks"]')],
    }),
    "typescript": ("promptPlan.ts", {
        "wrong-static-reversed": [("const stat = modules.filter((m) => m.static);", "const stat = modules.filter((m) => m.static).reverse();")],
        "wrong-breakpoint-after-all": [("? stat.length - 1 : null", "? blocks.length - 1 : null")],
        "wrong-variable-in-static-allowed": [("    if (/\\{\\w+\\}/.test(m.text)) throw", "    if (false) throw")],
        "wrong-missing-variable-blank": [("    if (!(name in variables)) throw new Error(`missing variable: ${name}`);", '    if (!(name in variables)) return "";')],
        "wrong-drop-highest-priority": [("if (k.priority < kept[victim].priority ||", "if (k.priority > kept[victim].priority ||")],
        "wrong-drop-tie-earlier": [("k.priority === kept[victim].priority && i > victim", "k.priority === kept[victim].priority && i < victim")],
        "wrong-over-budget-ignored": [('    if (kept.length === 0) throw new Error("over budget: the static modules alone exceed it");', "    if (kept.length === 0) break;")],
        "wrong-minimum-exclusive": [("prefix >= MIN_CACHEABLE", "prefix > MIN_CACHEABLE")],
        "wrong-minimum-one-low": [("prefix >= MIN_CACHEABLE", "prefix >= MIN_CACHEABLE - 1")],
        "wrong-model-tier-ignored": [("m.tier >= workload.tier && ", "")],
        "wrong-model-latency-ignored": [(" && m.latency_ms <= workload.max_latency_ms)", ")")],
        "wrong-model-tie-by-position": [("a.price_out - b.price_out || (a.name < b.name ? -1 : a.name > b.name ? 1 : 0)", "a.price_out - b.price_out")],
        "wrong-reuse-first-block-only": [("  const same = a.blocks.slice(0, ia + 1).every((block: any, i: number) => block.name === b.blocks[i].name && block.text === b.blocks[i].text);", "  const same = a.blocks[0].text === b.blocks[0].text;")],
        "wrong-reuse-needs-whole-prompt": [("  const same = a.blocks.slice(0, ia + 1).every(", "  const same = a.blocks.every(")],
    }),
    "java": ("PromptPlan.java", {
        "wrong-static-reversed": [('for (Map<String, Object> m : modules) (Boolean.TRUE.equals(m.get("static")) ? stat : dynamic).add(m);', 'for (Map<String, Object> m : modules) {\n            if (Boolean.TRUE.equals(m.get("static"))) stat.add(0, m);\n            else dynamic.add(m);\n        }')],
        "wrong-breakpoint-after-all": [("? stat.size() - 1 : null", "? blocks.size() - 1 : null")],
        "wrong-variable-in-static-allowed": [('if (VARIABLE.matcher((String) m.get("text")).find()) throw', "if (false) throw")],
        "wrong-missing-variable-blank": [('if (!variables.containsKey(name)) throw new IllegalArgumentException("missing variable: " + name);', 'if (!variables.containsKey(name)) {\n                m.appendReplacement(out, "");\n                continue;\n            }')],
        "wrong-drop-highest-priority": [('if ((Integer) kept.get(i).get("priority") <= (Integer) kept.get(victim).get("priority")) victim = i;', 'if ((Integer) kept.get(i).get("priority") >= (Integer) kept.get(victim).get("priority")) victim = i;')],
        "wrong-drop-tie-earlier": [('if ((Integer) kept.get(i).get("priority") <= (Integer) kept.get(victim).get("priority")) victim = i;', 'if ((Integer) kept.get(i).get("priority") < (Integer) kept.get(victim).get("priority")) victim = i;')],
        "wrong-over-budget-ignored": [('if (kept.isEmpty()) throw new IllegalArgumentException("over budget: the static modules alone exceed it");', "if (kept.isEmpty()) break;")],
        "wrong-minimum-exclusive": [("prefix >= MIN_CACHEABLE", "prefix > MIN_CACHEABLE")],
        "wrong-minimum-one-low": [("prefix >= MIN_CACHEABLE", "prefix >= MIN_CACHEABLE - 1")],
        "wrong-model-tier-ignored": [('(Integer) m.get("tier") >= (Integer) workload.get("tier") && ', "")],
        "wrong-model-latency-ignored": [(' && (Integer) m.get("latency_ms") <= (Integer) workload.get("max_latency_ms")) fit.add(m);', ") fit.add(m);")],
        "wrong-model-tie-by-position": [('.thenComparing(m -> (String) m.get("name")));', ");")],
        "wrong-reuse-first-block-only": [("same = same && blocksA.get(i).equals(blocksB.get(i));", "same = same && (i > 0 || blocksA.get(i).equals(blocksB.get(i)));")],
        "wrong-reuse-needs-whole-prompt": [("for (int i = 0; i <= ia; i++) {", "for (int i = 0; i < blocksA.size(); i++) {")],
    }),
    "kotlin": ("PromptPlan.kt", {
        "wrong-static-reversed": [('val stat = modules.filter { it["static"] == true }', 'val stat = modules.filter { it["static"] == true }.reversed()')],
        "wrong-breakpoint-after-all": [("stat.size - 1 else null", "blocks.size - 1 else null")],
        "wrong-variable-in-static-allowed": [('for (m in stat) require(!VARIABLE.containsMatchIn(m["text"] as String)) {', "for (m in stat) require(true) {")],
        "wrong-missing-variable-blank": [('variables[m.groupValues[1]] ?: throw IllegalArgumentException("missing variable: ${m.groupValues[1]}")', 'variables[m.groupValues[1]] ?: ""')],
        "wrong-drop-highest-priority": [("if (kept[i].third <= kept[victim].third) victim = i", "if (kept[i].third >= kept[victim].third) victim = i")],
        "wrong-drop-tie-earlier": [("if (kept[i].third <= kept[victim].third) victim = i", "if (kept[i].third < kept[victim].third) victim = i")],
        "wrong-over-budget-ignored": [('require(kept.isNotEmpty()) { "over budget: the static modules alone exceed it" }', "if (kept.isEmpty()) break")],
        "wrong-minimum-exclusive": [("prefix >= MIN_CACHEABLE", "prefix > MIN_CACHEABLE")],
        "wrong-minimum-one-low": [("prefix >= MIN_CACHEABLE", "prefix >= MIN_CACHEABLE - 1")],
        "wrong-model-tier-ignored": [('(it["tier"] as Int) >= (workload["tier"] as Int) && ', "")],
        "wrong-model-latency-ignored": [(' && (it["latency_ms"] as Int) <= (workload["max_latency_ms"] as Int) }', " }")],
        "wrong-model-tie-by-position": [('compareBy({ it["price_out"] as Int }, { it["name"] as String })', 'compareBy<Map<String, Any?>> { it["price_out"] as Int }')],
        "wrong-reuse-first-block-only": [("val same = (0..ia).all { blocksA[it] == blocksB[it] }", "val same = blocksA[0] == blocksB[0]")],
        "wrong-reuse-needs-whole-prompt": [("val same = (0..ia).all { blocksA[it] == blocksB[it] }", "val same = blocksA == blocksB")],
    }),
}
