# Planted wrong solutions of module 83-deployment-architecture-and-data-handling: exact replacements against the practice's reference (see tools/make_plants.py).
# Runs with PLANTS, X and both() in scope; names defined here are local to this file.

PLANTS[f"{X}/83-deployment-architecture-and-data-handling/unit-01/practice-1"] = {
    "python": ("data_policy.py", {
        "wrong-geo-unset-passes": [('            if config.get("inference_geo") != "us":', '            if config.get("inference_geo") == "global":')],
        "wrong-eu-pin-allowed": [('        if platform in ("api", "aws-platform"):\n            findings.add("residency-unavailable")', '        if False:\n            findings.add("residency-unavailable")')],
        "wrong-any-region-for-us": [('        elif not region.startswith("us-"):', "        elif not region:")],
        "wrong-cloud-zdr-ok": [('        if platform in ("bedrock", "vertex"):\n            findings.add("zdr-not-anthropics")', '        if False:\n            findings.add("zdr-not-anthropics")')],
        "wrong-fable-zdr-ok": [('            if str(config.get("model", "")).startswith("claude-fable"):', "            if False:")],
        "wrong-baa-optional": [('        if platform == "api" and not config.get("hipaa_baa"):', "        if False:")],
        "wrong-aws-hipaa-ok": [('        if platform == "aws-platform":\n            findings.add("phi-platform-unsupported")', '        if False:\n            findings.add("phi-platform-unsupported")')],
        "wrong-redact-not-safe": [('        if config.get("pii_handling") not in SAFE_INPUT:\n            findings.add("phi-not-deidentified")', '        if config.get("pii_handling") != "tokenise":\n            findings.add("phi-not-deidentified")')],
        "wrong-tenancy-ignored": [('    if req.get("multi_tenant") and config.get("tenancy") != "workspace-per-tenant":', "    if False:")],
        "wrong-audit-phi-only": [('(req.get("phi") or config.get("pii_handling") not in SAFE_INPUT)', 'req.get("phi")')],
        "wrong-retention-long-inclusive": [('days > req["audit_max_days"]', 'days >= req["audit_max_days"]')],
        "wrong-retention-short-inclusive": [('days < req["audit_min_days"]', 'days <= req["audit_min_days"]')],
        "wrong-purge-held": [('age > max_days and not e.get("hold")', "age > max_days")],
        "wrong-purge-boundary": [('age > max_days and not e.get("hold")', 'age >= max_days and not e.get("hold")')],
        "wrong-global-fallback": [('if d["residency"] == WANT.get(user_region))', 'if d["residency"] in (WANT.get(user_region), "global"))')],
        "wrong-pick-first-listed": [('matching = sorted(d["name"] for d in deployments if', 'matching = list(d["name"] for d in deployments if')],
    }),
    "typescript": ("dataPolicy.ts", {
        "wrong-geo-unset-passes": [('if (config.inference_geo !== "us") findings.add("residency-not-pinned");', 'if (config.inference_geo === "global") findings.add("residency-not-pinned");')],
        "wrong-eu-pin-allowed": [('    if (platform === "api" || platform === "aws-platform") {\n      findings.add("residency-unavailable");', '    if (false) {\n      findings.add("residency-unavailable");')],
        "wrong-any-region-for-us": [('} else if (!region.startsWith("us-")) {', "} else if (!region) {")],
        "wrong-cloud-zdr-ok": [('    if (platform === "bedrock" || platform === "vertex") {\n      findings.add("zdr-not-anthropics");', '    if (false) {\n      findings.add("zdr-not-anthropics");')],
        "wrong-fable-zdr-ok": [('      if (String(config.model ?? "").startsWith("claude-fable")) findings.add("model-needs-retention");', '      if (false) findings.add("model-needs-retention");')],
        "wrong-baa-optional": [('    if (platform === "api" && !config.hipaa_baa) findings.add("phi-no-baa");', '    if (false) findings.add("phi-no-baa");')],
        "wrong-aws-hipaa-ok": [('    if (platform === "aws-platform") findings.add("phi-platform-unsupported");', '    if (false) findings.add("phi-platform-unsupported");')],
        "wrong-redact-not-safe": [('    if (!SAFE_INPUT.includes(config.pii_handling)) {\n      findings.add("phi-not-deidentified");', '    if (config.pii_handling !== "tokenise") {\n      findings.add("phi-not-deidentified");')],
        "wrong-tenancy-ignored": [('  if (req.multi_tenant && config.tenancy !== "workspace-per-tenant") findings.add("tenant-isolation");', '  if (false) findings.add("tenant-isolation");')],
        "wrong-audit-phi-only": [("(req.phi || !SAFE_INPUT.includes(config.pii_handling))", "req.phi")],
        "wrong-retention-long-inclusive": [("days > req.audit_max_days", "days >= req.audit_max_days")],
        "wrong-retention-short-inclusive": [("days < req.audit_min_days", "days <= req.audit_min_days")],
        "wrong-purge-held": [("(age > maxDays && !e.hold ? purge : keep)", "(age > maxDays ? purge : keep)")],
        "wrong-purge-boundary": [("(age > maxDays && !e.hold ? purge : keep)", "(age >= maxDays && !e.hold ? purge : keep)")],
        "wrong-global-fallback": [("d.residency === WANT[userRegion]", '(d.residency === WANT[userRegion] || d.residency === "global")')],
        "wrong-pick-first-listed": [(".map((d) => d.name as string).sort(byText)", ".map((d) => d.name as string)")],
    }),
    "java": ("DataPolicy.java", {
        "wrong-geo-unset-passes": [('if (!"us".equals(config.get("inference_geo"))) findings.add("residency-not-pinned");', 'if ("global".equals(config.get("inference_geo"))) findings.add("residency-not-pinned");')],
        "wrong-eu-pin-allowed": [('            if (!cloud) {\n                findings.add("residency-unavailable");', '            if (false) {\n                findings.add("residency-unavailable");')],
        "wrong-any-region-for-us": [('} else if (!region.startsWith("us-")) {', "} else if (region.isEmpty()) {")],
        "wrong-cloud-zdr-ok": [('            if (cloud) {\n                findings.add("zdr-not-anthropics");', '            if (false) {\n                findings.add("zdr-not-anthropics");')],
        "wrong-fable-zdr-ok": [('if (String.valueOf(config.getOrDefault("model", "")).startsWith("claude-fable")) findings.add("model-needs-retention");', 'if (false) findings.add("model-needs-retention");')],
        "wrong-baa-optional": [('if ("api".equals(platform) && !truthy(config.get("hipaa_baa"))) findings.add("phi-no-baa");', 'if (false) findings.add("phi-no-baa");')],
        "wrong-aws-hipaa-ok": [('if ("aws-platform".equals(platform)) findings.add("phi-platform-unsupported");', 'if (false) findings.add("phi-platform-unsupported");')],
        "wrong-redact-not-safe": [('            if (!safeInput(config.get("pii_handling"))) {\n                findings.add("phi-not-deidentified");', '            if (!"tokenise".equals(config.get("pii_handling"))) {\n                findings.add("phi-not-deidentified");')],
        "wrong-tenancy-ignored": [('if (truthy(req.get("multi_tenant")) && !"workspace-per-tenant".equals(config.get("tenancy"))) findings.add("tenant-isolation");', 'if (false) findings.add("tenant-isolation");')],
        "wrong-audit-phi-only": [('(truthy(req.get("phi")) || !safeInput(config.get("pii_handling")))', 'truthy(req.get("phi"))')],
        "wrong-retention-long-inclusive": [('days > (Integer) req.get("audit_max_days")', 'days >= (Integer) req.get("audit_max_days")')],
        "wrong-retention-short-inclusive": [('days < (Integer) req.get("audit_min_days")', 'days <= (Integer) req.get("audit_min_days")')],
        "wrong-purge-held": [('(age > maxDays && !truthy(e.get("hold")) ? purge : keep)', "(age > maxDays ? purge : keep)")],
        "wrong-purge-boundary": [('(age > maxDays && !truthy(e.get("hold")) ? purge : keep)', '(age >= maxDays && !truthy(e.get("hold")) ? purge : keep)')],
        "wrong-global-fallback": [('if (d.get("residency").equals(WANT.get(userRegion))) matching.add(', 'if (d.get("residency").equals(WANT.get(userRegion)) || d.get("residency").equals("global")) matching.add(')],
        "wrong-pick-first-listed": [("        matching.sort(Comparator.naturalOrder());\n", "")],
    }),
    "kotlin": ("DataPolicy.kt", {
        "wrong-geo-unset-passes": [('if (config["inference_geo"] != "us") findings += "residency-not-pinned"', 'if (config["inference_geo"] == "global") findings += "residency-not-pinned"')],
        "wrong-eu-pin-allowed": [('        if (!cloud) {\n            findings += "residency-unavailable"', '        if (false) {\n            findings += "residency-unavailable"')],
        "wrong-any-region-for-us": [('} else if (!region.startsWith("us-")) {', "} else if (region.isEmpty()) {")],
        "wrong-cloud-zdr-ok": [('        if (cloud) {\n            findings += "zdr-not-anthropics"', '        if (false) {\n            findings += "zdr-not-anthropics"')],
        "wrong-fable-zdr-ok": [('if ((config["model"] ?: "").toString().startsWith("claude-fable")) findings += "model-needs-retention"', 'if (false) findings += "model-needs-retention"')],
        "wrong-baa-optional": [('if (platform == "api" && !truthy(config["hipaa_baa"])) findings += "phi-no-baa"', 'if (false) findings += "phi-no-baa"')],
        "wrong-aws-hipaa-ok": [('if (platform == "aws-platform") findings += "phi-platform-unsupported"', 'if (false) findings += "phi-platform-unsupported"')],
        "wrong-redact-not-safe": [('        if (config["pii_handling"] !in SAFE_INPUT) {\n            findings += "phi-not-deidentified"', '        if (config["pii_handling"] != "tokenise") {\n            findings += "phi-not-deidentified"')],
        "wrong-tenancy-ignored": [('if (truthy(req["multi_tenant"]) && config["tenancy"] != "workspace-per-tenant") findings += "tenant-isolation"', 'if (false) findings += "tenant-isolation"')],
        "wrong-audit-phi-only": [('(truthy(req["phi"]) || config["pii_handling"] !in SAFE_INPUT)', 'truthy(req["phi"])')],
        "wrong-retention-long-inclusive": [('days > (req["audit_max_days"] as Int)', 'days >= (req["audit_max_days"] as Int)')],
        "wrong-retention-short-inclusive": [('days < (req["audit_min_days"] as Int)', 'days <= (req["audit_min_days"] as Int)')],
        "wrong-purge-held": [('(if (age > maxDays && !truthy(e["hold"])) purge else keep)', "(if (age > maxDays) purge else keep)")],
        "wrong-purge-boundary": [('(if (age > maxDays && !truthy(e["hold"])) purge else keep)', '(if (age >= maxDays && !truthy(e["hold"])) purge else keep)')],
        "wrong-global-fallback": [('deployments.filter { it["residency"] == WANT[userRegion] }', 'deployments.filter { it["residency"] == WANT[userRegion] || it["residency"] == "global" }')],
        "wrong-pick-first-listed": [('.map { it["name"] as String }.sorted().firstOrNull()', '.map { it["name"] as String }.firstOrNull()')],
    }),
}
