# Planted wrong solutions of module 84-cost-and-capacity-engineering: exact replacements against the practice's reference (see tools/make_plants.py).
# Runs with PLANTS, X and both() in scope; names defined here are local to this file.

PLANTS[f"{X}/84-cost-and-capacity-engineering/unit-01/practice-1"] = {
    "python": ("gateway_budget.py", {
        "wrong-route-ignores-table": [('else policy["routes"].get(request["task"], policy["default"])', 'else policy["default"]')],
        "wrong-warn-keeps-model": [('    if status == "warn":\n', "    if False:\n")],
        "wrong-block-still-routes": [('    if status == "block":\n        return None\n', "")],
        "wrong-warn-strict": [("after * 100 >= budget * 80", "after * 100 > budget * 80")],
        "wrong-block-at-budget": [("    if after > budget:", "    if after >= budget:")],
        "wrong-zero-budget-open": [('    if budget <= 0:\n        return "block"\n', "")],
        "wrong-showback-unknown-free": [('        if r["model"] not in prices:\n            raise ValueError(f"unknown model: {r[\'model\']}")\n        p = prices[r["model"]]\n', '        p = prices.get(r["model"], {"input": 0, "cache_read": 0, "output": 0})\n')],
        "wrong-showback-by-name": [('key=lambda x: (-x["cents"], x["team"])', 'key=lambda x: x["team"]')],
        "wrong-showback-row-rounding": [('totals.get(r["team"], 0) + r["input"] * p["input"] + r["cache_read"] * p["cache_read"] + r["output"] * p["output"]', 'totals.get(r["team"], 0) + (r["input"] * p["input"] + r["cache_read"] * p["cache_read"] + r["output"] * p["output"] + 500_000) // 1_000_000 * 1_000_000')],
        "wrong-showback-floors": [("(value + 500_000) // 1_000_000", "value // 1_000_000")],
        "wrong-delivery-strict": [("<= timeout_seconds * 100", "< timeout_seconds * 100")],
        "wrong-delivery-no-margin": [("p95_seconds * (100 + margin_percent)", "p95_seconds * 100")],
        "wrong-pin-always-honoured": [('wanted if wanted in policy["allowed"] else', "wanted if wanted else")],
    }),
    "typescript": ("gatewayBudget.ts", {
        "wrong-route-ignores-table": [(": (policy.routes[request.task] ?? policy.default);", ": policy.default;")],
        "wrong-warn-keeps-model": [('  if (status === "warn") {', "  if (false) {")],
        "wrong-block-still-routes": [('  if (status === "block") return null;\n', "")],
        "wrong-warn-strict": [("after * 100 >= budget * 80", "after * 100 > budget * 80")],
        "wrong-block-at-budget": [('if (after > budget) return "block";', 'if (after >= budget) return "block";')],
        "wrong-zero-budget-open": [('  if (budget <= 0) {\n    return "block";\n  }\n', "")],
        "wrong-showback-unknown-free": [("    if (!(r.model in prices)) throw new Error(`unknown model: ${r.model}`);\n    const p = prices[r.model];", "    const p = prices[r.model] ?? { input: 0, cache_read: 0, output: 0 };")],
        "wrong-showback-by-name": [("b.cents - a.cents || (a.team < b.team ? -1 : a.team > b.team ? 1 : 0)", "a.team < b.team ? -1 : a.team > b.team ? 1 : 0")],
        "wrong-showback-row-rounding": [("(totals.get(r.team) ?? 0) + r.input * p.input + r.cache_read * p.cache_read + r.output * p.output", "(totals.get(r.team) ?? 0) + Math.floor((r.input * p.input + r.cache_read * p.cache_read + r.output * p.output + 500_000) / 1_000_000) * 1_000_000")],
        "wrong-showback-floors": [("Math.floor((value + 500_000) / 1_000_000)", "Math.floor(value / 1_000_000)")],
        "wrong-delivery-strict": [("<= timeoutSeconds * 100", "< timeoutSeconds * 100")],
        "wrong-delivery-no-margin": [("p95Seconds * (100 + marginPercent)", "p95Seconds * 100")],
        "wrong-pin-always-honoured": [("policy.allowed.includes(wanted) ? wanted :", "wanted ? wanted :")],
    }),
    "java": ("GatewayBudget.java", {
        "wrong-route-ignores-table": [(': (String) asMap(policy.get("routes")).getOrDefault(request.get("task"), policy.get("default"));', ': (String) policy.get("default");')],
        "wrong-warn-keeps-model": [('        if (status.equals("warn")) {', "        if (false) {")],
        "wrong-block-still-routes": [('        if (status.equals("block")) {\n            return null;\n        }\n', "")],
        "wrong-warn-strict": [("after * 100 >= budget * 80", "after * 100 > budget * 80")],
        "wrong-block-at-budget": [('if (after > budget) return "block";', 'if (after >= budget) return "block";')],
        "wrong-zero-budget-open": [('        if (budget <= 0) {\n            return "block";\n        }\n', "")],
        "wrong-showback-unknown-free": [('if (!prices.containsKey(r.get("model"))) throw new IllegalArgumentException("unknown model: " + r.get("model"));', 'if (!prices.containsKey(r.get("model"))) continue;')],
        "wrong-showback-by-name": [('Comparator.comparingLong((Map<String, Object> x) -> -(Long) x.get("cents")).thenComparing(x -> (String) x.get("team"))', 'Comparator.comparing((Map<String, Object> x) -> (String) x.get("team"))')],
        "wrong-showback-row-rounding": [('totals.merge((String) r.get("team"), value, Long::sum);', 'totals.merge((String) r.get("team"), (value + 500_000) / 1_000_000 * 1_000_000, Long::sum);')],
        "wrong-showback-floors": [('row.put("cents", (e.getValue() + 500_000) / 1_000_000);', 'row.put("cents", e.getValue() / 1_000_000);')],
        "wrong-delivery-strict": [("<= timeoutSeconds * 100", "< timeoutSeconds * 100")],
        "wrong-delivery-no-margin": [("p95Seconds * (100 + marginPercent)", "p95Seconds * 100")],
        "wrong-pin-always-honoured": [('String model = wanted != null && asList(policy.get("allowed")).contains(wanted) ? (String) wanted', 'String model = wanted != null ? (String) wanted')],
    }),
    "kotlin": ("GatewayBudget.kt", {
        "wrong-route-ignores-table": [('else (asMap(policy["routes"])[request["task"] as String] ?: policy["default"]) as String', 'else policy["default"] as String')],
        "wrong-warn-keeps-model": [('    if (status == "warn") {', "    if (false) {")],
        "wrong-block-still-routes": [('    if (status == "block") {\n        return null\n    }\n', "")],
        "wrong-warn-strict": [("after * 100 >= budget * 80", "after * 100 > budget * 80")],
        "wrong-block-at-budget": [('if (after > budget) return "block"', 'if (after >= budget) return "block"')],
        "wrong-zero-budget-open": [('    if (budget <= 0) {\n        return "block"\n    }\n', "")],
        "wrong-showback-unknown-free": [('        require(name in prices) { "unknown model: $name" }\n', "        if (name !in prices) continue\n")],
        "wrong-showback-by-name": [('compareBy({ -(it["cents"] as Long) }, { it["team"] as String })', 'compareBy<Map<String, Any?>> { it["team"] as String }')],
        "wrong-showback-row-rounding": [('totals[r["team"] as String] = (totals[r["team"] as String] ?: 0L) + value', 'totals[r["team"] as String] = (totals[r["team"] as String] ?: 0L) + (value + 500_000) / 1_000_000 * 1_000_000')],
        "wrong-showback-floors": [('"cents" to (value + 500_000) / 1_000_000)', '"cents" to value / 1_000_000)')],
        "wrong-delivery-strict": [("<= timeoutSeconds * 100", "< timeoutSeconds * 100")],
        "wrong-delivery-no-margin": [("p95Seconds * (100 + marginPercent)", "p95Seconds * 100")],
        "wrong-pin-always-honoured": [('if (wanted != null && wanted in asList(policy["allowed"])) wanted else', "if (wanted != null) wanted else")],
    }),
}
