# Planted wrong solutions of module 85-retrieval-pipelines-at-design-level: exact replacements against the practice's reference (see tools/make_plants.py).
# Runs with PLANTS, X and both() in scope; names defined here are local to this file.

PLANTS[f"{X}/85-retrieval-pipelines-at-design-level/unit-01/practice-1"] = {
    "python": ("pipeline.py", {
        "wrong-no-prefix": [('f"{title} > {name}. {part}"', "part")],
        "wrong-no-split": [('if current and len(" ".join(current + [sentence]).split()) > max_words:', "if False:")],
        "wrong-code-weight": [("score = sum(3 if any(c.isdigit() for c in t) else 1 for t in wanted if t in have)", "score = sum(1 for t in wanted if t in have)")],
        "wrong-filter-after-cut": [("        if allowed_docs is not None and chunk.doc not in allowed_docs:\n            continue\n", ""),
                                   ("    return [chunk_id for _, _, chunk_id in sorted(scored)[:k]]",
                                    "    allowed = {c.id for c in chunks if allowed_docs is None or c.doc in allowed_docs}\n    return [chunk_id for _, _, chunk_id in sorted(scored)[:k] if chunk_id in allowed]")],
        "wrong-always-index": [('    if corpus_tokens < 200000:\n        return "cached prompt"\n', "")],
        "wrong-table-chunked": [('    if shape == "table":\n        return "structured query"\n', "")],
        "wrong-reindex-additive": [("            result += chunk_sections(doc_id, text)", "            result += old.get(doc_id, []) + chunk_sections(doc_id, text)")],
        "wrong-reindex-keeps-removed": [("    return result, report", '    for d in report["removed"]:\n        result += old[d]\n    return result, report')],
        "wrong-stale-ignores-removed": [("if c.doc not in docs or c.version != doc_version(docs[c.doc])]", "if c.doc in docs and c.version != doc_version(docs[c.doc])]")],
        "wrong-recall-answered-only": [("return round(hits / len(relevant), 2)", "return round(hits / max(1, len([q for q in relevant if q in results])), 2)")],
    }),
    "typescript": ("pipeline.ts", {
        "wrong-no-prefix": [("text: `${title} > ${name}. ${part}`", "text: part")],
        "wrong-no-split": [('if (current.length && [...current, sentence].join(" ").split(/\\s+/).length > maxWords) {', "if (false) {")],
        "wrong-code-weight": [("score += /[0-9]/.test(t) ? 3 : 1;", "score += 1;")],
        "wrong-filter-after-cut": [("    if (allowedDocs !== null && !allowedDocs.has(chunk.doc)) return;\n", ""),
                                   ("  return scored.slice(0, k).map((s) => s[2]);",
                                    "  return scored.slice(0, k).map((s) => s[2]).filter((id) => chunks.some((c) => c.id === id && (allowedDocs === null || allowedDocs.has(c.doc))));")],
        "wrong-always-index": [('  if (corpusTokens < 200000) return "cached prompt";\n', "")],
        "wrong-table-chunked": [('  if (shape === "table") return "structured query";\n', "")],
        "wrong-reindex-additive": [("      result.push(...chunkSections(docId, text));", "      result.push(...(old.get(docId) ?? []), ...chunkSections(docId, text));")],
        "wrong-reindex-keeps-removed": [("  return [result, report];", "  for (const d of report.removed) result.push(...old.get(d)!);\n  return [result, report];")],
        "wrong-stale-ignores-removed": [("filter((c) => !(c.doc in docs) || c.version !== docVersion(docs[c.doc]))", "filter((c) => c.doc in docs && c.version !== docVersion(docs[c.doc]))")],
        "wrong-recall-answered-only": [("  return Math.round((hits / entries.length) * 100) / 100;", "  const answered = entries.filter(([q]) => q in results).length;\n  return Math.round((hits / Math.max(1, answered)) * 100) / 100;")],
    }),
    "java": ("Pipeline.java", {
        "wrong-no-prefix": [('title + " > " + name + ". " + pieces.get(n)', "pieces.get(n)")],
        "wrong-no-split": [('if (!current.isEmpty() && (String.join(" ", current) + " " + sentence).split("\\\\s+").length > maxWords) {', "if (false) {")],
        "wrong-code-weight": [("score += t.chars().anyMatch(Character::isDigit) ? 3 : 1;", "score += 1;")],
        "wrong-filter-after-cut": [("            if (allowedDocs != null && !allowedDocs.contains(chunks.get(n).doc())) continue;\n", ""),
                                   ("for (int i = 0; i < Math.min(k, scored.size()); i++) out.add(chunks.get(scored.get(i)[1]).id());",
                                    "for (int i = 0; i < Math.min(k, scored.size()); i++) { Chunk c = chunks.get(scored.get(i)[1]); if (allowedDocs == null || allowedDocs.contains(c.doc())) out.add(c.id()); }")],
        "wrong-always-index": [('        if (corpusTokens < 200000) return "cached prompt";\n', "")],
        "wrong-table-chunked": [('        if (shape.equals("table")) return "structured query";\n', "")],
        "wrong-reindex-additive": [("                result.addAll(chunkSections(e.getKey(), e.getValue()));", "                if (had != null) result.addAll(had);\n                result.addAll(chunkSections(e.getKey(), e.getValue()));")],
        "wrong-reindex-keeps-removed": [("        return new Reindexed(result, report);", '        for (String d : report.get("removed")) result.addAll(old.get(d));\n        return new Reindexed(result, report);')],
        "wrong-stale-ignores-removed": [("if (!docs.containsKey(c.doc()) || c.version() != docVersion(docs.get(c.doc()))) out.add(c.id());", "if (docs.containsKey(c.doc()) && c.version() != docVersion(docs.get(c.doc()))) out.add(c.id());")],
        "wrong-recall-answered-only": [("return Math.round(hits * 100.0 / relevant.size()) / 100.0;", "int answered = 0;\n        for (String q : relevant.keySet()) if (results.containsKey(q)) answered++;\n        return Math.round(hits * 100.0 / Math.max(1, answered)) / 100.0;")],
    }),
    "kotlin": ("Pipeline.kt", {
        "wrong-no-prefix": [('"$title > $name. $piece"', "piece")],
        "wrong-no-split": [('if (current.isNotEmpty() && (current.joinToString(" ") + " " + sentence).split(Regex("\\\\s+")).size > maxWords) {', "if (false) {")],
        "wrong-code-weight": [(".map { t -> if (t.any { c -> c.isDigit() }) 3 else 1 }.sum()", ".map { 1 }.sum()")],
        "wrong-filter-after-cut": [("        if (allowedDocs != null && chunk.doc !in allowedDocs) return@mapIndexedNotNull null\n", ""),
                                   ("    return scored.sortedWith(compareBy({ it.first }, { it.second })).take(k).map { it.third }",
                                    "    return scored.sortedWith(compareBy({ it.first }, { it.second })).take(k).map { it.third }.filter { id -> chunks.any { it.id == id && (allowedDocs == null || it.doc in allowedDocs) } }")],
        "wrong-always-index": [('    corpusTokens < 200000 -> "cached prompt"\n', "")],
        "wrong-table-chunked": [('    shape == "table" -> "structured query"\n', "")],
        "wrong-reindex-additive": [("            result += chunkSections(docId, text)!!", "            result += (had ?: emptyList()) + chunkSections(docId, text)!!")],
        "wrong-reindex-keeps-removed": [("    return Reindexed(result, report)", '    for (d in report.getValue("removed")) result += old.getValue(d)\n    return Reindexed(result, report)')],
        "wrong-stale-ignores-removed": [("chunks.filter { it.doc !in docs || it.version != docVersion(docs.getValue(it.doc)) }.map { it.id }", "chunks.filter { it.doc in docs && it.version != docVersion(docs.getValue(it.doc)) }.map { it.id }")],
        "wrong-recall-answered-only": [("return Math.round(hits * 100.0 / relevant.size) / 100.0", "return Math.round(hits * 100.0 / maxOf(1, relevant.keys.count { it in results })) / 100.0")],
    }),
}
