# Planted wrong solutions of module 86-integration-choices-access-and-capability-bloat: exact replacements against the practice's reference (see tools/make_plants.py).
# Runs with PLANTS, X and both() in scope; names defined here are local to this file.

PLANTS[f"{X}/86-integration-choices-access-and-capability-bloat/unit-01/practice-1"] = {
    "python": ("capability.py", {
        "wrong-risky-everything": [('    return [t for t in remove if catalog[t]["access"] in RISKY]', '    return remove')],
        "wrong-dormant-removed": [('    return [t for t in agent["holds"] if t not in agent["needs"]]', '    return [t for t in agent["holds"] if t not in agent["needs"] or agent["used"].get(t, 0) == 0]')],
        "wrong-defer-count-only": [('    return len(tools) >= 10 or sum(tools.values()) > 10000', '    return len(tools) >= 10')],
        "wrong-keep-unclamped": [('    return max(3, min(5, keep))', '    return max(1, keep)')],
        "wrong-ties-by-insertion": [("sorted(tools, key=lambda t: (-usage.get(t, 0), t))[:keep]", "sorted(tools, key=lambda t: -usage.get(t, 0))[:keep]")],
        "wrong-mechanism-path-first": [('    if counterpart == "agent":\n        return "agent-to-agent"\n    if path == "fixed":\n        return "direct call in code"\n',
                                        '    if path == "fixed":\n        return "direct call in code"\n    if counterpart == "agent":\n        return "agent-to-agent"\n')],
        "wrong-auth-user-only": [('    if scope not in agent_scopes:\n        return f"deny: agent lacks {scope}"\n', "")],
        "wrong-gateway-rate-first": [('    elif request["model"] not in policy["models"][team]:\n        decision, reason = "deny", "model not allowed"',
                                      '    elif request["recent"] >= policy["limits"][team]:\n        decision, reason = "deny", "rate limited"\n    elif request["model"] not in policy["models"][team]:\n        decision, reason = "deny", "model not allowed"')],
        "wrong-gateway-audit-empty-on-deny": [('return {"team"', 'return {} if decision == "deny" else {"team"')],
        "wrong-gateway-rate-first": [('    if request["model"] not in policy["models"][team]:\n        return "deny", "model not allowed"\n', '    if request["recent"] >= policy["limits"][team]:\n        return "deny", "rate limited"\n    if request["model"] not in policy["models"][team]:\n        return "deny", "model not allowed"\n')],
    }),
    "typescript": ("capability.ts", {
        "wrong-risky-everything": [('return toRemove.filter((t) => RISKY.has(catalog[t].access));', 'return toRemove;')],
        "wrong-dormant-removed": [('return agent.holds.filter((t) => !agent.needs.includes(t));', 'return agent.holds.filter((t) => !agent.needs.includes(t) || (agent.used[t] ?? 0) === 0);')],
        "wrong-defer-count-only": [('return Object.keys(tools).length >= 10 || Object.values(tools).reduce((a, t) => a + t, 0) > 10000;', 'return Object.keys(tools).length >= 10;')],
        "wrong-keep-unclamped": [('return Math.max(3, Math.min(5, keep));', 'return Math.max(1, keep);')],
        "wrong-ties-by-insertion": [("(usage[b] ?? 0) - (usage[a] ?? 0) || (a < b ? -1 : 1))", "(usage[b] ?? 0) - (usage[a] ?? 0))")],
        "wrong-mechanism-path-first": [('  if (counterpart === "agent") return "agent-to-agent";\n  if (path === "fixed") return "direct call in code";\n',
                                        '  if (path === "fixed") return "direct call in code";\n  if (counterpart === "agent") return "agent-to-agent";\n')],
        "wrong-auth-user-only": [("  if (!agentScopes.includes(scope)) return `deny: agent lacks ${scope}`;\n", "")],
        "wrong-gateway-rate-first": [('  else if (!policy.models[team].includes(request.model)) reason = "model not allowed";',
                                      '  else if (request.recent >= policy.limits[team]) reason = "rate limited";\n  else if (!policy.models[team].includes(request.model)) reason = "model not allowed";')],
        "wrong-gateway-audit-empty-on-deny": [('return { team: team ?? ', 'return decision === "deny" ? {} : { team: team ?? ')],
        "wrong-gateway-rate-first": [('  if (!policy.models[team].includes(request.model)) return ["deny", "model not allowed"];', '  if (request.recent >= policy.limits[team]) return ["deny", "rate limited"];\n  if (!policy.models[team].includes(request.model)) return ["deny", "model not allowed"];')],
    }),
    "java": ("Capability.java", {
        "wrong-risky-everything": [('return remove.stream().filter(t -> RISKY.contains(catalog.get(t).access())).toList();', 'return remove;')],
        "wrong-dormant-removed": [('return agent.holds().stream().filter(t -> !agent.needs().contains(t)).toList();', 'return agent.holds().stream().filter(t -> !agent.needs().contains(t) || agent.used().getOrDefault(t, 0) == 0).toList();')],
        "wrong-defer-count-only": [('return tools.size() >= 10 || tools.values().stream().mapToInt(Integer::intValue).sum() > 10000;', 'return tools.size() >= 10;')],
        "wrong-keep-unclamped": [('return Math.max(3, Math.min(5, keep));', 'return Math.max(1, keep);')],
        "wrong-ties-by-insertion": [("Comparator.comparing((String t) -> -usage.getOrDefault(t, 0)).thenComparing(t -> t)", "Comparator.comparing((String t) -> -usage.getOrDefault(t, 0))")],
        "wrong-mechanism-path-first": [('        if (counterpart.equals("agent")) return "agent-to-agent";\n        if (path.equals("fixed")) return "direct call in code";\n',
                                        '        if (path.equals("fixed")) return "direct call in code";\n        if (counterpart.equals("agent")) return "agent-to-agent";\n')],
        "wrong-auth-user-only": [('        if (!agentScopes.contains(scope)) return "deny: agent lacks " + scope;\n', "")],
        "wrong-gateway-rate-first": [('        else if (!policy.models().get(team).contains(request.model())) reason = "model not allowed";',
                                      '        else if (request.recent() >= policy.limits().get(team)) reason = "rate limited";\n        else if (!policy.models().get(team).contains(request.model())) reason = "model not allowed";')],
        "wrong-gateway-audit-empty-on-deny": [('return Map.of("team", team == null', 'return decision.equals("deny") ? Map.of() : Map.of("team", team == null')],
        "wrong-gateway-rate-first": [('        if (!policy.models().get(team).contains(request.model())) return List.of("deny", "model not allowed");\n', '        if (request.recent() >= policy.limits().get(team)) return List.of("deny", "rate limited");\n        if (!policy.models().get(team).contains(request.model())) return List.of("deny", "model not allowed");\n')],
    }),
    "kotlin": ("Capability.kt", {
        "wrong-risky-everything": [('return remove.filter { catalog.getValue(it).access in RISKY }', 'return remove')],
        "wrong-dormant-removed": [('return agent.holds.filter { it !in agent.needs }', 'return agent.holds.filter { it !in agent.needs || (agent.used[it] ?: 0) == 0 }')],
        "wrong-defer-count-only": [('return tools.size >= 10 || tools.values.sum() > 10000', 'return tools.size >= 10')],
        "wrong-keep-unclamped": [('return keep.coerceIn(3, 5)', 'return keep')],
        "wrong-ties-by-insertion": [("compareBy({ -(usage[it] ?: 0) }, { it })", "compareBy({ -(usage[it] ?: 0) })")],
        "wrong-mechanism-path-first": [('        counterpart == "agent" -> "agent-to-agent"\n        path == "fixed" -> "direct call in code"\n', '        path == "fixed" -> "direct call in code"\n        counterpart == "agent" -> "agent-to-agent"\n')],
        "wrong-auth-user-only": [('    if (scope !in agentScopes) return "deny: agent lacks $scope"\n', "")],
        "wrong-gateway-rate-first": [('        request.model !in policy.models.getValue(team) -> "deny" to "model not allowed"\n',
                                      '        request.recent >= policy.limits.getValue(team) -> "deny" to "rate limited"\n        request.model !in policy.models.getValue(team) -> "deny" to "model not allowed"\n')],
        "wrong-gateway-audit-empty-on-deny": [('return mapOf("team" to (team ?: "unknown")', 'return if (decision == "deny") emptyMap() else mapOf("team" to (team ?: "unknown")')],
    }),
}
