# Planted wrong solutions of module 86-integration-choices-access-and-capability-bloat: exact replacements against the practice's reference (see tools/make_plants.py).
# Runs with PLANTS, X and both() in scope; names defined here are local to this file.

PLANTS[f"{X}/86-integration-choices-access-and-capability-bloat/unit-01/practice-1"] = {
    "python": ("capability.py", {
        "wrong-risky-everything": [('"risky": [t for t in remove if catalog[t]["access"] in RISKY],', '"risky": remove,')],
        "wrong-dormant-removed": [("remove = [t for t in holds if t not in needs]", "remove = [t for t in holds if t not in needs or used.get(t, 0) == 0]")],
        "wrong-defer-count-only": [("if len(tools) < 10 and sum(tools.values()) <= 10000:", "if len(tools) < 10:")],
        "wrong-keep-unclamped": [("keep = max(3, min(5, keep))", "keep = max(1, keep)")],
        "wrong-ties-by-insertion": [("sorted(tools, key=lambda t: (-usage.get(t, 0), t))[:keep]", "sorted(tools, key=lambda t: -usage.get(t, 0))[:keep]")],
        "wrong-mechanism-path-first": [('    if counterpart == "agent":\n        return "agent-to-agent"\n    if path == "fixed":\n        return "direct call in code"\n',
                                        '    if path == "fixed":\n        return "direct call in code"\n    if counterpart == "agent":\n        return "agent-to-agent"\n')],
        "wrong-auth-user-only": [('    if scope not in agent_scopes:\n        return f"deny: agent lacks {scope}"\n', "")],
        "wrong-gateway-rate-first": [('    elif request["model"] not in policy["models"][team]:\n        decision, reason = "deny", "model not allowed"',
                                      '    elif request["recent"] >= policy["limits"][team]:\n        decision, reason = "deny", "rate limited"\n    elif request["model"] not in policy["models"][team]:\n        decision, reason = "deny", "model not allowed"')],
        "wrong-gateway-audit-empty-on-deny": [('"audit": {"team"', '"audit": {} if decision == "deny" else {"team"')],
    }),
    "typescript": ("capability.ts", {
        "wrong-risky-everything": [("risky: remove.filter((t) => RISKY.has(catalog[t].access)),", "risky: remove,")],
        "wrong-dormant-removed": [("const remove = holds.filter((t) => !needs.includes(t));", "const remove = holds.filter((t) => !needs.includes(t) || (used[t] ?? 0) === 0);")],
        "wrong-defer-count-only": [("if (names.length < 10 && total <= 10000)", "if (names.length < 10)")],
        "wrong-keep-unclamped": [("keep = Math.max(3, Math.min(5, keep));", "keep = Math.max(1, keep);")],
        "wrong-ties-by-insertion": [("(usage[b] ?? 0) - (usage[a] ?? 0) || (a < b ? -1 : 1))", "(usage[b] ?? 0) - (usage[a] ?? 0))")],
        "wrong-mechanism-path-first": [('  if (counterpart === "agent") return "agent-to-agent";\n  if (path === "fixed") return "direct call in code";\n',
                                        '  if (path === "fixed") return "direct call in code";\n  if (counterpart === "agent") return "agent-to-agent";\n')],
        "wrong-auth-user-only": [("  if (!agentScopes.includes(scope)) return `deny: agent lacks ${scope}`;\n", "")],
        "wrong-gateway-rate-first": [('  else if (!policy.models[team].includes(request.model)) reason = "model not allowed";',
                                      '  else if (request.recent >= policy.limits[team]) reason = "rate limited";\n  else if (!policy.models[team].includes(request.model)) reason = "model not allowed";')],
        "wrong-gateway-audit-empty-on-deny": [("audit: { team: team ?? ", 'audit: decision === "deny" ? {} : { team: team ?? ')],
    }),
    "java": ("Capability.java", {
        "wrong-risky-everything": [("remove.stream().filter(t -> RISKY.contains(catalog.get(t).access())).toList()", "remove")],
        "wrong-dormant-removed": [("filter(t -> !agent.needs().contains(t)).toList();", "filter(t -> !agent.needs().contains(t) || agent.used().getOrDefault(t, 0) == 0).toList();")],
        "wrong-defer-count-only": [("if (names.size() < 10 && total <= 10000)", "if (names.size() < 10)")],
        "wrong-keep-unclamped": [("keep = Math.max(3, Math.min(5, keep));", "keep = Math.max(1, keep);")],
        "wrong-ties-by-insertion": [("Comparator.comparing((String t) -> -usage.getOrDefault(t, 0)).thenComparing(t -> t)", "Comparator.comparing((String t) -> -usage.getOrDefault(t, 0))")],
        "wrong-mechanism-path-first": [('        if (counterpart.equals("agent")) return "agent-to-agent";\n        if (path.equals("fixed")) return "direct call in code";\n',
                                        '        if (path.equals("fixed")) return "direct call in code";\n        if (counterpart.equals("agent")) return "agent-to-agent";\n')],
        "wrong-auth-user-only": [('        if (!agentScopes.contains(scope)) return "deny: agent lacks " + scope;\n', "")],
        "wrong-gateway-rate-first": [('        else if (!policy.models().get(team).contains(request.model())) reason = "model not allowed";',
                                      '        else if (request.recent() >= policy.limits().get(team)) reason = "rate limited";\n        else if (!policy.models().get(team).contains(request.model())) reason = "model not allowed";')],
        "wrong-gateway-audit-empty-on-deny": [('return new Outcome(decision, reason, Map.of("team"', 'return new Outcome(decision, reason, decision.equals("deny") ? Map.of() : Map.of("team"')],
    }),
    "kotlin": ("Capability.kt", {
        "wrong-risky-everything": [("remove.filter { catalog.getValue(it).access in RISKY },", "remove,")],
        "wrong-dormant-removed": [("val remove = agent.holds.filter { it !in agent.needs }", "val remove = agent.holds.filter { it !in agent.needs || (agent.used[it] ?: 0) == 0 }")],
        "wrong-defer-count-only": [("if (names.size < 10 && tools.values.sum() <= 10000)", "if (names.size < 10)")],
        "wrong-keep-unclamped": [("val kept = keep.coerceIn(3, 5)", "val kept = keep")],
        "wrong-ties-by-insertion": [("compareBy({ -(usage[it] ?: 0) }, { it })", "compareBy({ -(usage[it] ?: 0) })")],
        "wrong-mechanism-path-first": [('    counterpart == "agent" -> "agent-to-agent"\n    path == "fixed" -> "direct call in code"\n', '    path == "fixed" -> "direct call in code"\n    counterpart == "agent" -> "agent-to-agent"\n')],
        "wrong-auth-user-only": [('    if (scope !in agentScopes) return "deny: agent lacks $scope"\n', "")],
        "wrong-gateway-rate-first": [('        request.model !in policy.models.getValue(team) -> "deny" to "model not allowed"\n',
                                      '        request.recent >= policy.limits.getValue(team) -> "deny" to "rate limited"\n        request.model !in policy.models.getValue(team) -> "deny" to "model not allowed"\n')],
        "wrong-gateway-audit-empty-on-deny": [('return Outcome(decision, reason, mapOf("team"', 'return Outcome(decision, reason, if (decision == "deny") emptyMap() else mapOf("team"')],
    }),
}
