# Planted wrong solutions of module 87-observability-at-scale: exact replacements against the practice's reference (see tools/make_plants.py).
# Runs with PLANTS, X and both() in scope; names defined here are local to this file.

PLANTS[f"{X}/87-observability-at-scale/unit-01/practice-1"] = {
    "python": ("triage.py", {
        "wrong-error-after-slow": [('    if any(s.status == "error" for s in spans):\n        return "error"\n    if spans[0].ms > slow_ms:\n        return "slow"\n',
                                    '    if spans[0].ms > slow_ms:\n        return "slow"\n    if any(s.status == "error" for s in spans):\n        return "error"\n')],
        "wrong-no-feedback": [('    if feedback:\n        return "feedback"\n', "")],
        "wrong-retries-ignored": [('    tools = [s.name for s in spans if s.kind == "tool"]\n    if any(tools.count(n) >= 3 for n in tools):\n        return "retries"\n', "")],
        "wrong-root-reporter": [('    return next(s for s in failed if s.id not in parents)\n', '    return failed[0]\n')],
        "wrong-stale-first": [('    failed = [s for s in spans if s.status == "error"]\n    if failed:',
                               '    failed = [s for s in spans if s.status == "error"]\n    for s in spans:\n        if s.kind == "retrieval" and s.note in ("stale", "no-hits"):\n            return {"layer": "retrieval", "name": s.name, "why": s.note, "path": [spans[0].name, s.name]}\n    if failed:')],
        "wrong-drift-up-only": [("abs(now - base) * 100 // base", "max(now - base, 0) * 100 // base")],
        "wrong-alert-no-reset": [("run = run + 1 if value > threshold else 0", "run = run + 1 if value > threshold else run")],
        "wrong-redact-keeps-content": [("if k not in CONTENT or k in allowed}", "if True}")],
        "wrong-redact-ignores-allowed": [("if k not in CONTENT or k in allowed}", "if k not in CONTENT}")],
        "wrong-trail-unsorted": [("sorted((e for e in events if e.request == request), key=lambda e: e.ts)", "(e for e in events if e.request == request)")],
        "wrong-stale-first": [('    failed = [s for s in spans if s.status == "error"]\n    if failed:', '    failed = [s for s in spans if s.status == "error"]\n    b = _blamed_retrieval(spans)\n    if b is not None:\n        return {"layer": "retrieval", "name": b.name, "why": b.note, "path": [spans[0].name, b.name]}\n    if failed:')],
    }),
    "typescript": ("triage.ts", {
        "wrong-error-after-slow": [('  if (spans.some((s) => s.status === "error")) return "error";\n  if (spans[0].ms > slowMs) return "slow";\n',
                                    '  if (spans[0].ms > slowMs) return "slow";\n  if (spans.some((s) => s.status === "error")) return "error";\n')],
        "wrong-no-feedback": [('  if (feedback) return "feedback";\n', "")],
        "wrong-retries-ignored": [('  const tools = spans.filter((s) => s.kind === "tool").map((s) => s.name);\n  if (tools.some((n) => tools.filter((m) => m === n).length >= 3)) return "retries";\n', "")],
        "wrong-root-reporter": [('return failed.find((s) => !parents.has(s.id))!;', 'return failed[0];')],
        "wrong-stale-first": [('  const failed = spans.filter((s) => s.status === "error");\n  if (failed.length > 0) {',
                               '  const failed = spans.filter((s) => s.status === "error");\n  for (const s of spans) if (s.kind === "retrieval" && (s.note === "stale" || s.note === "no-hits")) return { layer: "retrieval", name: s.name, why: s.note, path: [spans[0].name, s.name] };\n  if (failed.length > 0) {')],
        "wrong-drift-up-only": [("Math.floor((Math.abs(now - base) * 100) / base)", "Math.floor((Math.max(now - base, 0) * 100) / base)")],
        "wrong-alert-no-reset": [("run = series[i] > threshold ? run + 1 : 0;", "run = series[i] > threshold ? run + 1 : run;")],
        "wrong-redact-keeps-content": [(".filter(([k]) => !CONTENT.has(k) || allowed.includes(k))", ".filter(() => true)")],
        "wrong-redact-ignores-allowed": [(".filter(([k]) => !CONTENT.has(k) || allowed.includes(k))", ".filter(([k]) => !CONTENT.has(k))")],
        "wrong-trail-unsorted": [(".sort((a, b) => a.ts - b.ts)", "")],
        "wrong-stale-first": [('  const failed = spans.filter((s) => s.status === "error");\n  if (failed.length > 0) {', '  const failed = spans.filter((s) => s.status === "error");\n  const b = blamedRetrieval(spans);\n  if (b !== undefined) return { layer: "retrieval", name: b.name, why: b.note, path: [spans[0].name, b.name] };\n  if (failed.length > 0) {')],
    }),
    "java": ("Triage.java", {
        "wrong-error-after-slow": [('        for (Span s : spans) if (s.status().equals("error")) return "error";\n        if (spans.get(0).ms() > slowMs) return "slow";\n',
                                    '        if (spans.get(0).ms() > slowMs) return "slow";\n        for (Span s : spans) if (s.status().equals("error")) return "error";\n')],
        "wrong-no-feedback": [('        if (feedback) return "feedback";\n', "")],
        "wrong-retries-ignored": [('        for (int n : tools.values()) if (n >= 3) return "retries";\n', "")],
        "wrong-root-reporter": [('return failed.stream().filter(s -> failed.stream().noneMatch(o -> o.parent().equals(s.id()))).findFirst().orElse(failed.get(0));', 'return failed.get(0);')],
        "wrong-stale-first": [("        if (!failed.isEmpty()) {\n",
                               '        for (Span s : spans) {\n            if (s.kind().equals("retrieval") && (s.note().equals("stale") || s.note().equals("no-hits"))) return new Cause("retrieval", s.name(), s.note(), List.of(spans.get(0).name(), s.name()));\n        }\n        if (!failed.isEmpty()) {\n')],
        "wrong-drift-up-only": [("Math.abs(now - base) * 100 / base", "Math.max(now - base, 0) * 100 / base")],
        "wrong-alert-no-reset": [("run = series.get(i) > threshold ? run + 1 : 0;", "run = series.get(i) > threshold ? run + 1 : run;")],
        "wrong-redact-keeps-content": [("if (!CONTENT.contains(k) || allowed.contains(k)) out.put(k, v);", "out.put(k, v);")],
        "wrong-redact-ignores-allowed": [("if (!CONTENT.contains(k) || allowed.contains(k)) out.put(k, v);", "if (!CONTENT.contains(k)) out.put(k, v);")],
        "wrong-trail-unsorted": [('.sorted(Comparator.comparingInt(Event::ts))', '')],
        "wrong-stale-first": [('        if (!failed.isEmpty()) {\n', '        Span b = blamedRetrieval(spans);\n        if (b != null) return new Cause("retrieval", b.name(), b.note(), List.of(spans.get(0).name(), b.name()));\n        if (!failed.isEmpty()) {\n')],
    }),
    "kotlin": ("Triage.kt", {
        "wrong-error-after-slow": [('    if (spans.any { it.status == "error" }) return "error"\n    if (spans[0].ms > slowMs) return "slow"\n',
                                    '    if (spans[0].ms > slowMs) return "slow"\n    if (spans.any { it.status == "error" }) return "error"\n')],
        "wrong-no-feedback": [('    if (feedback) return "feedback"\n', "")],
        "wrong-retries-ignored": [('    val tools = spans.filter { it.kind == "tool" }.map { it.name }\n    if (tools.any { n -> tools.count { it == n } >= 3 }) return "retries"\n', "")],
        "wrong-root-reporter": [('return failed.first { it.id !in parents }', 'return failed[0]')],
        "wrong-stale-first": [('    val failed = spans.filter { it.status == "error" }\n    if (failed.isNotEmpty()) {',
                               '    val failed = spans.filter { it.status == "error" }\n    for (s in spans) if (s.kind == "retrieval" && (s.note == "stale" || s.note == "no-hits")) return Cause("retrieval", s.name, s.note, listOf(spans[0].name, s.name))\n    if (failed.isNotEmpty()) {')],
        "wrong-drift-up-only": [("Math.abs(now - base) * 100 / base", "Math.max(now - base, 0) * 100 / base")],
        "wrong-alert-no-reset": [("run = if (value > threshold) run + 1 else 0", "run = if (value > threshold) run + 1 else run")],
        "wrong-redact-keeps-content": [("event.filter { it.key !in CONTENT || it.key in allowed }", "event.filter { true }")],
        "wrong-redact-ignores-allowed": [("event.filter { it.key !in CONTENT || it.key in allowed }", "event.filter { it.key !in CONTENT }")],
        "wrong-trail-unsorted": [(".sortedBy { it.ts }", "")],
        "wrong-stale-first": [('    val failed = spans.filter { it.status == "error" }\n    if (failed.isNotEmpty()) {', '    val failed = spans.filter { it.status == "error" }\n    val b = blamedRetrieval(spans)\n    if (b != null) return Cause("retrieval", b.name, b.note, listOf(spans[0].name, b.name))\n    if (failed.isNotEmpty()) {')],
    }),
}
