# Planted wrong solutions of module 89-migration-and-model-upgrades-at-scale: exact replacements against the practice's reference (see tools/make_plants.py).
# Runs with PLANTS, X and both() in scope; names defined here are local to this file.

PLANTS[f"{X}/89-migration-and-model-upgrades-at-scale/unit-01/practice-1"] = {
    "python": ("rollout.py", {
        "wrong-must-pass-ignored": [('return ["must-pass failed: " + ", ".join(failed)] if failed else []', "return []")],
        "wrong-protected-ignored": [('return ["protected segment lost answers: " + ", ".join(hit)] if hit else []', "return []")],
        "wrong-net-loss-ignored": [('return [f"net loss: lost {lost}, gained {gained}"] if lost > gained else []', "return []")],
        "wrong-cost-at-limit": [("if up > max_cost_up else", "if up >= max_cost_up else")],
        "wrong-cost-rounded": [("up = (new_total - old_total) * 100 // old_total if", "up = round((new_total - old_total) * 100 / old_total) if")],
        "wrong-p95-max": [("p95 = percentile([c.new_ms for c in cases], 95)", "p95 = max(c.new_ms for c in cases)")],
        "wrong-rollout-min-ignored": [('    if requests < min_requests:\n        return f"hold at {stage}"\n', "")],
        "wrong-rollout-no-rollback": [('    if errors * 1000 // requests > max_errors_per_1000:\n        return "rollback to 0"\n', "")],
        "wrong-days-by-name": [("rows = sorted((days_until(today, when), name, tentative) for name, when, tentative in models)", "rows = sorted(((days_until(today, when), name, tentative) for name, when, tentative in models), key=lambda r: r[1])")],
        "wrong-level-boundary": [('"urgent" if days <= 14', '"urgent" if days < 14')],
        "wrong-migrate-keeps-sampling": [("return Request(target, None, None, None, thinking, tool_choice, strict, False), changes", "return Request(target, request.temperature, request.top_p, request.top_k, thinking, tool_choice, strict, False), changes")],
        "wrong-migrate-keeps-forced-tool": [('    if tool_choice in ("any", "tool"):', "    if False:")],
    }),
    "typescript": ("rollout.ts", {
        "wrong-must-pass-ignored": [('return failed.length ? ["must-pass failed: " + failed.join(", ")] : [];', "return [];")],
        "wrong-protected-ignored": [('return hit.length ? ["protected segment lost answers: " + hit.join(", ")] : [];', "return [];")],
        "wrong-net-loss-ignored": [("return lost > gained ? [`net loss: lost ${lost}, gained ${gained}`] : [];", "return [];")],
        "wrong-cost-at-limit": [("return up > maxCostUp ?", "return up >= maxCostUp ?")],
        "wrong-cost-rounded": [("Math.floor(((newTotal - oldTotal) * 100) / oldTotal)", "Math.round(((newTotal - oldTotal) * 100) / oldTotal)")],
        "wrong-p95-max": [("const p95 = percentile(cases.map((c) => c.newMs), 95);", "const p95 = Math.max(...cases.map((c) => c.newMs));")],
        "wrong-rollout-min-ignored": [("  if (requests < minRequests) return `hold at ${stage}`;\n", "")],
        "wrong-rollout-no-rollback": [('  if (Math.floor((errors * 1000) / requests) > maxErrorsPer1000) return "rollback to 0";\n', "")],
        "wrong-days-by-name": [("rows.sort((a, b) => a.days - b.days || (a.name < b.name ? -1 : a.name > b.name ? 1 : Number(a.tentative) - Number(b.tentative)));", "rows.sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0));")],
        "wrong-level-boundary": [('days <= 14 ? "urgent"', 'days < 14 ? "urgent"')],
        "wrong-migrate-keeps-sampling": [("return [{ model: target, temperature: null, topP: null, topK: null, thinking, toolChoice, strict, prefill: false }, changes];", "return [{ model: target, temperature: request.temperature, topP: request.topP, topK: request.topK, thinking, toolChoice, strict, prefill: false }, changes];")],
        "wrong-migrate-keeps-forced-tool": [('if (toolChoice === "any" || toolChoice === "tool") {', "if (false) {")],
    }),
    "java": ("Rollout.java", {
        "wrong-must-pass-ignored": [('return failed.isEmpty() ? List.of() : List.of("must-pass failed: " + String.join(", ", failed));', "return List.of();")],
        "wrong-protected-ignored": [('return hit.isEmpty() ? List.of() : List.of("protected segment lost answers: " + String.join(", ", hit));', "return List.of();")],
        "wrong-net-loss-ignored": [('return lost > gained ? List.of("net loss: lost " + lost + ", gained " + gained) : List.of();', "return List.of();")],
        "wrong-cost-at-limit": [("return up > maxCostUp ?", "return up >= maxCostUp ?")],
        "wrong-cost-rounded": [("(newTotal - oldTotal) * 100 / oldTotal", "Math.round((newTotal - oldTotal) * 100f / oldTotal)")],
        "wrong-p95-max": [("int p95 = percentile(cases.stream().map(Case::newMs).toList(), 95);", "int p95 = cases.stream().mapToInt(Case::newMs).max().orElse(0);")],
        "wrong-rollout-min-ignored": [('        if (requests < minRequests) return "hold at " + stage;\n', "")],
        "wrong-rollout-no-rollback": [('        if (errors * 1000L / requests > maxErrorsPer1000) return "rollback to 0";\n', "")],
        "wrong-days-by-name": [("sorted.sort(Comparator.comparingLong((Model m) -> daysUntil(today, m.date())).thenComparing(Model::name).thenComparing(Model::tentative));", "sorted.sort(Comparator.comparing(Model::name));")],
        "wrong-level-boundary": [('days <= 14 ? "urgent"', 'days < 14 ? "urgent"')],
        "wrong-migrate-keeps-sampling": [("return new Migration(new Request(TARGET, null, null, null, thinking, toolChoice, strict, false), changes);", "return new Migration(new Request(TARGET, request.temperature(), request.topP(), request.topK(), thinking, toolChoice, strict, false), changes);")],
        "wrong-migrate-keeps-forced-tool": [('if (toolChoice.equals("any") || toolChoice.equals("tool")) {', "if (false) {")],
    }),
    "kotlin": ("Rollout.kt", {
        "wrong-must-pass-ignored": [('return if (failed.isNotEmpty()) listOf("must-pass failed: " + failed.joinToString(", ")) else emptyList()', "return emptyList()")],
        "wrong-protected-ignored": [('return if (hit.isNotEmpty()) listOf("protected segment lost answers: " + hit.joinToString(", ")) else emptyList()', "return emptyList()")],
        "wrong-net-loss-ignored": [('return if (lost > gained) listOf("net loss: lost $lost, gained $gained") else emptyList()', "return emptyList()")],
        "wrong-cost-at-limit": [("if (up > maxCostUp)", "if (up >= maxCostUp)")],
        "wrong-cost-rounded": [("(newTotal - oldTotal) * 100 / oldTotal else 0", "Math.round((newTotal - oldTotal) * 100f / oldTotal) else 0")],
        "wrong-p95-max": [("val p95 = percentile(cases.map { it.newMs }, 95)", "val p95 = cases.maxOf { it.newMs }")],
        "wrong-rollout-min-ignored": [('    if (requests < minRequests) return "hold at $stage"\n', "")],
        "wrong-rollout-no-rollback": [('    if (errors * 1000L / requests > maxErrorsPer1000) return "rollback to 0"\n', "")],
        "wrong-days-by-name": [("models.sortedWith(compareBy<Model>({ daysUntil(today, it.date) }, { it.name }, { it.tentative }))", "models.sortedBy { it.name }")],
        "wrong-level-boundary": [('else if (days <= 14) "urgent"', 'else if (days < 14) "urgent"')],
        "wrong-migrate-keeps-sampling": [("return Migration(Request(TARGET, null, null, null, thinking, toolChoice, strict, false), changes)", "return Migration(Request(TARGET, request.temperature, request.topP, request.topK, thinking, toolChoice, strict, false), changes)")],
        "wrong-migrate-keeps-forced-tool": [('if (toolChoice == "any" || toolChoice == "tool") {', "if (false) {")],
    }),
}
