# Planted wrong solutions of module 93-professional-capstone: exact replacements against the practice's reference (see tools/make_plants.py).
# Runs with PLANTS, X and both() in scope; names defined here are local to this file.

PLANTS[f"{X}/93-professional-capstone/unit-01/practice-1"] = {
    "python": ("launch_review.py", {
        "wrong-feedback-rule-dropped": [('    add("feedback_loop" not in f, "high", "P1", "missing-feedback")\n', '')],
        "wrong-autonomy-ignores-path": [('("agent" in f or "team" in f) and "path_known" in f', '("agent" in f or "team" in f)')],
        "wrong-team-price-15": [('"team" in f and n.get("team_value_chats", 0) < 15', '"team" in f and n.get("team_value_chats", 0) <= 15')],
        "wrong-tool-tokens-10000": [('n.get("tool_tokens", 0) > 10000 and "deferral" not in f', 'n.get("tool_tokens", 0) >= 10000 and "deferral" not in f')],
        "wrong-deferral-ignored": [('n.get("tool_tokens", 0) > 10000 and "deferral" not in f', 'n.get("tool_tokens", 0) > 10000')],
        "wrong-eval-20": [('n.get("eval_cases", 0) < 20', 'n.get("eval_cases", 0) <= 20')],
        "wrong-stages-3": [('n.get("rollout_stages", 0) < 3', 'n.get("rollout_stages", 0) <= 3')],
        "wrong-retain-floor": [('n.get("retain_days", 0) < n.get("floor_days", 0) or n.get("retain_days", 0) > n.get("ceiling_days", 0)', 'n.get("retain_days", 0) <= n.get("floor_days", 0) or n.get("retain_days", 0) > n.get("ceiling_days", 0)')],
        "wrong-retain-ceiling": [('n.get("retain_days", 0) < n.get("floor_days", 0) or n.get("retain_days", 0) > n.get("ceiling_days", 0)', 'n.get("retain_days", 0) < n.get("floor_days", 0) or n.get("retain_days", 0) >= n.get("ceiling_days", 0)')],
        "wrong-filter-rule-dropped": [('    add("filter_after_ranking" in f, "high", "P3", "filter-after-ranking")\n', '')],
        "wrong-stale-rule-dropped": [('    add("replace_on_change" not in f, "high", "P3", "stale-index")\n', '')],
        "wrong-rights-rule-dropped": [('    add("agent_rights_only" in f, "high", "P3", "agent-rights-only")\n', '')],
        "wrong-pii-always": [('"pii_reaches_model" in f', 'True')],
        "wrong-residency-always": [('"residency_unmet" in f', 'True')],
        "wrong-irreversible-medium": [('"high", "P5", "irreversible-without-person"', '"medium", "P5", "irreversible-without-person"')],
        "wrong-human-step-ignored": [('"irreversible_action" in f and "human_step" not in f', '"irreversible_action" in f')],
        "wrong-team-size-10": [('n.get("team_size", 0) > 10 and "managed_settings" not in f', 'n.get("team_size", 0) >= 10 and "managed_settings" not in f')],
        "wrong-sla-and": [('n.get("latency_ms", 0) <= 0 or n.get("availability_tenths", 0) <= 0', 'n.get("latency_ms", 0) <= 0 and n.get("availability_tenths", 0) <= 0')],
        "wrong-owner-rule-dropped": [('    add("owner" not in f, "medium", "P6", "no-accountable-owner")\n', '')],
        "wrong-order-by-domain": [('key=lambda s: (SEVERITY[s.split()[0]], s.split()[1], s.split()[2])', 'key=lambda s: (s.split()[1], s.split()[2])')],
        "wrong-verdict-any-finding": [('any(x.startswith("medium ") for x in findings)', 'bool(findings)')],
        "wrong-scorecard-no-p7": [('"P6", "P7"]', '"P6"]')],
        "wrong-ceil-floor": [('needed = -(-100 * review_cost // error_cost)', 'needed = 100 * review_cost // error_cost')],
        "wrong-no-floor-at-zero": [('return max(0, 100 - needed)', 'return 100 - needed')],
    }),
    "typescript": ("launchReview.ts", {
        "wrong-feedback-rule-dropped": [('  add(!f.has("feedback_loop"), "high", "P1", "missing-feedback");\n', '')],
        "wrong-autonomy-ignores-path": [('(f.has("agent") || f.has("team")) && f.has("path_known")', '(f.has("agent") || f.has("team"))')],
        "wrong-team-price-15": [('f.has("team") && (n["team_value_chats"] ?? 0) < 15', 'f.has("team") && (n["team_value_chats"] ?? 0) <= 15')],
        "wrong-tool-tokens-10000": [('(n["tool_tokens"] ?? 0) > 10000 && !f.has("deferral")', '(n["tool_tokens"] ?? 0) >= 10000 && !f.has("deferral")')],
        "wrong-deferral-ignored": [('(n["tool_tokens"] ?? 0) > 10000 && !f.has("deferral")', '(n["tool_tokens"] ?? 0) > 10000')],
        "wrong-eval-20": [('(n["eval_cases"] ?? 0) < 20', '(n["eval_cases"] ?? 0) <= 20')],
        "wrong-stages-3": [('(n["rollout_stages"] ?? 0) < 3', '(n["rollout_stages"] ?? 0) <= 3')],
        "wrong-retain-floor": [('(n["retain_days"] ?? 0) < (n["floor_days"] ?? 0) || (n["retain_days"] ?? 0) > (n["ceiling_days"] ?? 0)', '(n["retain_days"] ?? 0) <= (n["floor_days"] ?? 0) || (n["retain_days"] ?? 0) > (n["ceiling_days"] ?? 0)')],
        "wrong-retain-ceiling": [('(n["retain_days"] ?? 0) < (n["floor_days"] ?? 0) || (n["retain_days"] ?? 0) > (n["ceiling_days"] ?? 0)', '(n["retain_days"] ?? 0) < (n["floor_days"] ?? 0) || (n["retain_days"] ?? 0) >= (n["ceiling_days"] ?? 0)')],
        "wrong-filter-rule-dropped": [('  add(f.has("filter_after_ranking"), "high", "P3", "filter-after-ranking");\n', '')],
        "wrong-stale-rule-dropped": [('  add(!f.has("replace_on_change"), "high", "P3", "stale-index");\n', '')],
        "wrong-rights-rule-dropped": [('  add(f.has("agent_rights_only"), "high", "P3", "agent-rights-only");\n', '')],
        "wrong-pii-always": [('f.has("pii_reaches_model")', 'true')],
        "wrong-residency-always": [('f.has("residency_unmet")', 'true')],
        "wrong-irreversible-medium": [('"high", "P5", "irreversible-without-person"', '"medium", "P5", "irreversible-without-person"')],
        "wrong-human-step-ignored": [('f.has("irreversible_action") && !f.has("human_step")', 'f.has("irreversible_action")')],
        "wrong-team-size-10": [('(n["team_size"] ?? 0) > 10 && !f.has("managed_settings")', '(n["team_size"] ?? 0) >= 10 && !f.has("managed_settings")')],
        "wrong-sla-and": [('(n["latency_ms"] ?? 0) <= 0 || (n["availability_tenths"] ?? 0) <= 0', '(n["latency_ms"] ?? 0) <= 0 && (n["availability_tenths"] ?? 0) <= 0')],
        "wrong-owner-rule-dropped": [('  add(!f.has("owner"), "medium", "P6", "no-accountable-owner");\n', '')],
        "wrong-order-by-domain": [('SEVERITY[part(a, 0)] - SEVERITY[part(b, 0)] || ', '')],
        "wrong-verdict-any-finding": [('findings.some((x) => x.startsWith("medium "))', 'findings.length > 0')],
        "wrong-scorecard-no-p7": [('"P6", "P7"];', '"P6"];')],
        "wrong-ceil-floor": [('Math.ceil((100 * reviewCost) / errorCost)', 'Math.floor((100 * reviewCost) / errorCost)')],
        "wrong-no-floor-at-zero": [('return Math.max(0, 100 - needed);', 'return 100 - needed;')],
    }),
    "java": ("LaunchReview.java", {
        "wrong-feedback-rule-dropped": [('        add(found, !f.contains("feedback_loop"), "high", "P1", "missing-feedback");\n', '')],
        "wrong-autonomy-ignores-path": [('(f.contains("agent") || f.contains("team")) && f.contains("path_known")', '(f.contains("agent") || f.contains("team"))')],
        "wrong-team-price-15": [('f.contains("team") && n.getOrDefault("team_value_chats", 0) < 15', 'f.contains("team") && n.getOrDefault("team_value_chats", 0) <= 15')],
        "wrong-tool-tokens-10000": [('n.getOrDefault("tool_tokens", 0) > 10000 && !f.contains("deferral")', 'n.getOrDefault("tool_tokens", 0) >= 10000 && !f.contains("deferral")')],
        "wrong-deferral-ignored": [('n.getOrDefault("tool_tokens", 0) > 10000 && !f.contains("deferral")', 'n.getOrDefault("tool_tokens", 0) > 10000')],
        "wrong-eval-20": [('n.getOrDefault("eval_cases", 0) < 20', 'n.getOrDefault("eval_cases", 0) <= 20')],
        "wrong-stages-3": [('n.getOrDefault("rollout_stages", 0) < 3', 'n.getOrDefault("rollout_stages", 0) <= 3')],
        "wrong-retain-floor": [('n.getOrDefault("retain_days", 0) < n.getOrDefault("floor_days", 0) || n.getOrDefault("retain_days", 0) > n.getOrDefault("ceiling_days", 0)', 'n.getOrDefault("retain_days", 0) <= n.getOrDefault("floor_days", 0) || n.getOrDefault("retain_days", 0) > n.getOrDefault("ceiling_days", 0)')],
        "wrong-retain-ceiling": [('n.getOrDefault("retain_days", 0) < n.getOrDefault("floor_days", 0) || n.getOrDefault("retain_days", 0) > n.getOrDefault("ceiling_days", 0)', 'n.getOrDefault("retain_days", 0) < n.getOrDefault("floor_days", 0) || n.getOrDefault("retain_days", 0) >= n.getOrDefault("ceiling_days", 0)')],
        "wrong-filter-rule-dropped": [('        add(found, f.contains("filter_after_ranking"), "high", "P3", "filter-after-ranking");\n', '')],
        "wrong-stale-rule-dropped": [('        add(found, !f.contains("replace_on_change"), "high", "P3", "stale-index");\n', '')],
        "wrong-rights-rule-dropped": [('        add(found, f.contains("agent_rights_only"), "high", "P3", "agent-rights-only");\n', '')],
        "wrong-pii-always": [('f.contains("pii_reaches_model")', 'true')],
        "wrong-residency-always": [('f.contains("residency_unmet")', 'true')],
        "wrong-irreversible-medium": [('"high", "P5", "irreversible-without-person"', '"medium", "P5", "irreversible-without-person"')],
        "wrong-human-step-ignored": [('f.contains("irreversible_action") && !f.contains("human_step")', 'f.contains("irreversible_action")')],
        "wrong-team-size-10": [('n.getOrDefault("team_size", 0) > 10 && !f.contains("managed_settings")', 'n.getOrDefault("team_size", 0) >= 10 && !f.contains("managed_settings")')],
        "wrong-sla-and": [('n.getOrDefault("latency_ms", 0) <= 0 || n.getOrDefault("availability_tenths", 0) <= 0', 'n.getOrDefault("latency_ms", 0) <= 0 && n.getOrDefault("availability_tenths", 0) <= 0')],
        "wrong-owner-rule-dropped": [('        add(found, !f.contains("owner"), "medium", "P6", "no-accountable-owner");\n', '')],
        "wrong-order-by-domain": [('Comparator.comparing((String s) -> SEVERITY.get(s.split(" ")[0])).thenComparing(s -> s.split(" ")[1])', 'Comparator.comparing((String s) -> s.split(" ")[1])')],
        "wrong-verdict-any-finding": [('findings.stream().anyMatch(x -> x.startsWith("medium "))', '!findings.isEmpty()')],
        "wrong-scorecard-no-p7": [('"P6", "P7");', '"P6");')],
        "wrong-ceil-floor": [('(100 * reviewCost + errorCost - 1) / errorCost', '(100 * reviewCost) / errorCost')],
        "wrong-no-floor-at-zero": [('return Math.max(0, 100 - needed);', 'return 100 - needed;')],
    }),
    "kotlin": ("LaunchReview.kt", {
        "wrong-feedback-rule-dropped": [('    add("feedback_loop" !in f, "high", "P1", "missing-feedback")\n', '')],
        "wrong-autonomy-ignores-path": [('("agent" in f || "team" in f) && "path_known" in f', '("agent" in f || "team" in f)')],
        "wrong-team-price-15": [('"team" in f && (n["team_value_chats"] ?: 0) < 15', '"team" in f && (n["team_value_chats"] ?: 0) <= 15')],
        "wrong-tool-tokens-10000": [('(n["tool_tokens"] ?: 0) > 10000 && "deferral" !in f', '(n["tool_tokens"] ?: 0) >= 10000 && "deferral" !in f')],
        "wrong-deferral-ignored": [('(n["tool_tokens"] ?: 0) > 10000 && "deferral" !in f', '(n["tool_tokens"] ?: 0) > 10000')],
        "wrong-eval-20": [('(n["eval_cases"] ?: 0) < 20', '(n["eval_cases"] ?: 0) <= 20')],
        "wrong-stages-3": [('(n["rollout_stages"] ?: 0) < 3', '(n["rollout_stages"] ?: 0) <= 3')],
        "wrong-retain-floor": [('(n["retain_days"] ?: 0) < (n["floor_days"] ?: 0) || (n["retain_days"] ?: 0) > (n["ceiling_days"] ?: 0)', '(n["retain_days"] ?: 0) <= (n["floor_days"] ?: 0) || (n["retain_days"] ?: 0) > (n["ceiling_days"] ?: 0)')],
        "wrong-retain-ceiling": [('(n["retain_days"] ?: 0) < (n["floor_days"] ?: 0) || (n["retain_days"] ?: 0) > (n["ceiling_days"] ?: 0)', '(n["retain_days"] ?: 0) < (n["floor_days"] ?: 0) || (n["retain_days"] ?: 0) >= (n["ceiling_days"] ?: 0)')],
        "wrong-filter-rule-dropped": [('    add("filter_after_ranking" in f, "high", "P3", "filter-after-ranking")\n', '')],
        "wrong-stale-rule-dropped": [('    add("replace_on_change" !in f, "high", "P3", "stale-index")\n', '')],
        "wrong-rights-rule-dropped": [('    add("agent_rights_only" in f, "high", "P3", "agent-rights-only")\n', '')],
        "wrong-pii-always": [('"pii_reaches_model" in f', 'true')],
        "wrong-residency-always": [('"residency_unmet" in f', 'true')],
        "wrong-irreversible-medium": [('"high", "P5", "irreversible-without-person"', '"medium", "P5", "irreversible-without-person"')],
        "wrong-human-step-ignored": [('"irreversible_action" in f && "human_step" !in f', '"irreversible_action" in f')],
        "wrong-team-size-10": [('(n["team_size"] ?: 0) > 10 && "managed_settings" !in f', '(n["team_size"] ?: 0) >= 10 && "managed_settings" !in f')],
        "wrong-sla-and": [('(n["latency_ms"] ?: 0) <= 0 || (n["availability_tenths"] ?: 0) <= 0', '(n["latency_ms"] ?: 0) <= 0 && (n["availability_tenths"] ?: 0) <= 0')],
        "wrong-owner-rule-dropped": [('    add("owner" !in f, "medium", "P6", "no-accountable-owner")\n', '')],
        "wrong-order-by-domain": [('compareBy({ SEVERITY.getValue(it.split(" ")[0]) }, { it.split(" ")[1] }, { it.split(" ")[2] })', 'compareBy({ it.split(" ")[1] }, { it.split(" ")[2] })')],
        "wrong-verdict-any-finding": [('findings.any { it.startsWith("medium ") }', 'findings.isNotEmpty()')],
        "wrong-scorecard-no-p7": [('"P6", "P7")', '"P6")')],
        "wrong-ceil-floor": [('(100 * reviewCost + errorCost - 1) / errorCost', '(100 * reviewCost) / errorCost')],
        "wrong-no-floor-at-zero": [('return maxOf(0, 100 - needed)', 'return 100 - needed')],
    }),
}
