"""Reading a review process honestly: one accuracy figure hides the weak segment, and a confidence score is only worth what a calibration table says it is.

The exam guide (task 5.5) says that stratified random sampling of high-confidence extractions measures the error rate and catches new patterns, that aggregate accuracy can mask poor performance on specific document types or fields,
and that field-level confidence scores should be calibrated using labelled validation sets. Below, 200 extractions are generated by a fixed rule (nothing here calls a model): the invoices are mostly right, the handwritten
documents are wrong more often, and the confidence says one thing while the labels say another. The numbers are invented for the illustration; the arithmetic is the lesson.
"""


def make_records(n=200):
    """(document type, stated confidence, was it correct) for n extractions, from a fixed rule."""
    records = []
    for i in range(n):
        doc_type = "handwritten" if i % 5 == 0 else "invoice"
        confidence = 50 + (i * 37) % 51
        penalty = 30 if doc_type == "handwritten" else 0
        records.append((doc_type, confidence, (i * 53) % 100 < confidence - 12 - penalty))
    return records


def ratio(part, whole):
    """A whole-number percentage, rounded half up; 0 for an empty whole."""
    return (200 * part + whole) // (2 * whole) if whole else 0


def overall_accuracy(records):
    return ratio(sum(1 for _, _, ok in records if ok), len(records))


def accuracy_by_type(records):
    groups = {}
    for doc_type, _, ok in records:
        c, n = groups.get(doc_type, (0, 0))
        groups[doc_type] = (c + (1 if ok else 0), n + 1)
    return [(t, c, n, ratio(c, n)) for t, (c, n) in sorted(groups.items())]


def calibration_table(records):
    """One row per non-empty confidence bucket: (label, count, confidence it claimed, how often it was right)."""
    buckets = {}
    for _, confidence, ok in records:
        low = min(confidence // 10 * 10, 90)
        count, conf_sum, right = buckets.get(low, (0, 0, 0))
        buckets[low] = (count + 1, conf_sum + confidence, right + (1 if ok else 0))
    rows = []
    for low in sorted(buckets):
        count, conf_sum, right = buckets[low]
        label = "90-100" if low == 90 else f"{low}-{low + 9}"
        rows.append((label, count, ratio(conf_sum, 100 * count), ratio(right, count)))
    return rows


def precision_above(records, threshold):
    """(how many extractions would be accepted without review, how often those are right)."""
    kept = [ok for _, confidence, ok in records if confidence >= threshold]
    return len(kept), ratio(sum(1 for ok in kept if ok), len(kept))


def main():
    records = make_records()
    print(f"overall accuracy: {overall_accuracy(records)}%")
    for doc_type, correct, total, percent in accuracy_by_type(records):
        print(f"{doc_type}: {correct} of {total} correct, {percent}%")
    for label, count, said, right in calibration_table(records):
        print(f"bucket {label}: {count} extractions, said {said}%, right {right}%")
    for threshold in (60, 70, 80, 90):
        kept, precision = precision_above(records, threshold)
        print(f"accept at {threshold} or above: {kept} extractions, {precision}% right")


if __name__ == "__main__":
    main()
