/**
 * Reading a review process honestly: one accuracy figure hides the weak segment, and a confidence score is only worth what a calibration table says it is.
 *
 * The exam guide (task 5.5) says that stratified random sampling of high-confidence extractions measures the error rate and catches new patterns, that aggregate accuracy can mask poor performance on specific document types or fields,
 * and that field-level confidence scores should be calibrated using labelled validation sets. Below, 200 extractions are generated by a fixed rule (nothing here calls a model): the invoices are mostly right, the handwritten
 * documents are wrong more often, and the confidence says one thing while the labels say another. The numbers are invented for the illustration; the arithmetic is the lesson.
 */
export type Rec = [string, number, boolean];

/** (document type, stated confidence, was it correct) for n extractions, from a fixed rule. */
export function makeRecords(n = 200): Rec[] {
  const records: Rec[] = [];
  for (let i = 0; i < n; i++) {
    const docType = i % 5 === 0 ? "handwritten" : "invoice";
    const confidence = 50 + ((i * 37) % 51);
    const penalty = docType === "handwritten" ? 30 : 0;
    records.push([docType, confidence, (i * 53) % 100 < confidence - 12 - penalty]);
  }
  return records;
}

/** A whole-number percentage, rounded half up; 0 for an empty whole. */
export function ratio(part: number, whole: number): number {
  return whole ? Math.floor((200 * part + whole) / (2 * whole)) : 0;
}

export function overallAccuracy(records: Rec[]): number {
  return ratio(records.filter(([, , ok]) => ok).length, records.length);
}

export function accuracyByType(records: Rec[]): Array<[string, number, number, number]> {
  const groups = new Map<string, [number, number]>();
  for (const [docType, , ok] of records) {
    const [c, n] = groups.get(docType) ?? [0, 0];
    groups.set(docType, [c + (ok ? 1 : 0), n + 1]);
  }
  return [...groups.keys()].sort().map((t) => [t, groups.get(t)![0], groups.get(t)![1], ratio(groups.get(t)![0], groups.get(t)![1])]);
}

/** One row per non-empty confidence bucket: (label, count, confidence it claimed, how often it was right). */
export function calibrationTable(records: Rec[]): Array<[string, number, number, number]> {
  const buckets = new Map<number, [number, number, number]>();
  for (const [, confidence, ok] of records) {
    const low = Math.min(Math.floor(confidence / 10) * 10, 90);
    const [count, confSum, right] = buckets.get(low) ?? [0, 0, 0];
    buckets.set(low, [count + 1, confSum + confidence, right + (ok ? 1 : 0)]);
  }
  return [...buckets.keys()].sort((a, b) => a - b).map((low) => {
    const [count, confSum, right] = buckets.get(low)!;
    return [low === 90 ? "90-100" : `${low}-${low + 9}`, count, ratio(confSum, 100 * count), ratio(right, count)];
  });
}

/** (how many extractions would be accepted without review, how often those are right). */
export function precisionAbove(records: Rec[], threshold: number): [number, number] {
  const kept = records.filter(([, confidence]) => confidence >= threshold);
  return [kept.length, ratio(kept.filter(([, , ok]) => ok).length, kept.length)];
}

export function main(): void {
  const records = makeRecords();
  console.log(`overall accuracy: ${overallAccuracy(records)}%`);
  for (const [docType, correct, total, percent] of accuracyByType(records)) console.log(`${docType}: ${correct} of ${total} correct, ${percent}%`);
  for (const [label, count, said, right] of calibrationTable(records)) console.log(`bucket ${label}: ${count} extractions, said ${said}%, right ${right}%`);
  for (const threshold of [60, 70, 80, 90]) {
    const [kept, precision] = precisionAbove(records, threshold);
    console.log(`accept at ${threshold} or above: ${kept} extractions, ${precision}% right`);
  }
}

if (import.meta.main) main();
